export default [
  // Create and populate the crime_scene table
  `CREATE TABLE crime_scene (
      id INTEGER PRIMARY KEY,
      date INTEGER,
      type TEXT,
      location TEXT,
      description TEXT
    );`,
  `INSERT INTO crime_scene (id, date, type, location, description) VALUES
      (1, 20120909, 'furto', 'City Street', 'Um hóspede foi encontrado morto em seu quarto de hotel. Havia sinais de luta e sangue perto da cama.'),
      (2, 19920415, 'furto', 'Downtown Bank', 'Uma maleta foi roubada durante um assalto. Um homem de terno foi visto saindo do local com ela.'),
      (3, 20010702, 'assassinato', 'Corner Café', 'Um corpo foi encontrado atrás do café. Nenhuma testemunha relatou nada, mas havia uma ferida de faca nas costas.'),
      (4, 19980328, 'suborno', 'Metro Station', NULL),
      (5, 20091113, 'furto', 'Park Avenue Office', 'Uma maleta com documentos confidenciais foi roubada. Uma testemunha mencionou uma pessoa de blazer fugindo da cena.'),
      (6, 20050716, 'assassinato', 'Grand Hotel', 'Um hóspede foi encontrado morto em seu quarto com sinais de crime. A porta estava trancada por dentro, sem sinais de arrombamento.'),
      (7, 19960205, 'furto', 'City Library', 'Uma maleta contendo papéis confidenciais desapareceu. O ladrão foi capturado na câmera de segurança, usando uma jaqueta.'),
      (8, 20080422, 'suborno', 'Main Street Mall', NULL),
      (9, 20110630, 'furto', 'Old Town Square', 'Um homem foi visto fugindo com uma maleta. Ele tinha uma cicatriz na mão direita e usava um casaco.'),
      (10, 20031218, 'assassinato', 'Central Park', 'O corpo de uma mulher foi descoberto no parque com sinais de estrangulamento. Uma testemunha viu um homem usando um boné perto da cena.'),
      (11, 20120909, 'furto', 'City Museum', 'Uma maleta contendo artefatos valiosos foi levada. Um homem de sobretudo foi visto saindo da cena.'),
      (12, 20140512, 'furto', 'Airport Terminal', NULL),
      (13, 19950521, 'assassinato', 'Museum of Modern Art', 'Um artista proeminente foi encontrado morto em seu estúdio com múltiplas facadas. Nenhum suspeito foi identificado ainda.'),
      (14, 20060907, 'furto', 'Luxury Hotel', 'Uma maleta foi roubada de um hóspede. O ladrão usava um terno escuro e tinha uma cicatriz na bochecha direita.'),
      (15, 19980211, 'furto', 'Subway Station', 'Uma maleta desapareceu da plataforma. Um homem de jaqueta de couro foi visto com ela.'),
      (16, 20021225, 'suborno', 'Downtown Restaurant', NULL),
      (17, 20160114, 'assassinato', 'University Library', 'Um estudante foi encontrado morto perto da entrada da biblioteca. A causa da morte foi um tiro na cabeça.'),
      (18, 19910730, 'furto', 'Art Gallery', NULL),
      (19, 20050710, 'assassinato', 'Beachside Hotel', 'Um hóspede foi encontrado morto em seu quarto de hotel. Havia sinais de luta e sangue perto da cama.'),
      (20, 19990416, 'furto', 'City Plaza', 'Uma maleta desapareceu após um evento. Nenhum suspeito claro foi identificado, mas um homem de casaco cinza foi visto na área.'),
      (21, 20080312, 'furto', 'Luxury Mall', 'Uma maleta com bens valiosos foi roubada. O ladrão foi descrito usando uma jaqueta escura e tinha uma cicatriz visível.'),
      (22, 20100122, 'suborno', 'Highway Rest Stop', NULL),
      (23, 20151203, 'assassinato', 'Coffee Shop', 'Um barista foi encontrado morto atrás do balcão com um tiro. O suspeito foi visto saindo em um carro vermelho.'),
      (24, 20180418, 'suborno', 'City Hall', 'Um oficial corrupto da cidade foi pego aceitando suborno. Uma fita de vídeo mostrou a transação em um escritório privado.'),
      (25, 20120719, 'furto', 'Warehouse District', NULL),
      (26, 19980903, 'assassinato', 'Luxury Condo', 'Um corpo foi descoberto em um apartamento de luxo. A vítima tinha múltiplos ferimentos por arma de fogo.'),
      (27, 20060522, 'furto', 'Shopping Mall', 'Uma bolsa foi roubada da bolsa de uma mulher na praça de alimentação. Um homem de moletom vermelho foi visto na área.'),
      (28, 19941030, 'suborno', 'Corporate Office', 'Um CEO foi visto aceitando pagamentos ilegais de um empreiteiro. O contrato foi posteriormente cancelado sob circunstâncias suspeitas.'),
      (29, 20150914, 'furto', 'Train Station', NULL),
      (30, 20070426, 'suborno', 'Golf Club', 'Um escândalo de suborno envolvendo vários oficiais de alto escalão no clube. Um vídeo surgiu mostrando a troca de dinheiro.'),
      (31, 20010212, 'assassinato', 'Dark Alley', 'Um homem foi encontrado morto em um beco escuro com uma faca cravada no peito. Sem suspeitos ainda.'),
      (32, 20180125, 'furto', 'Bank Vault', 'Um cofre de banco foi arrombado durante a noite. Câmeras de segurança foram adulteradas e o culpado permanece não identificado.'),
      (33, 19961118, 'assassinato', 'Luxury Yacht', NULL),
      (34, 20030705, 'suborno', 'Subway Station', 'Um suborno foi oferecido a um oficial do metrô em troca de pular a catraca. O oficial relatou o incidente imediatamente.'),
      (35, 19921221, 'furto', 'Fashion Boutique', 'Um colar valendo milhares foi roubado durante um desfile de moda. Uma mulher foi vista saindo com ele na bolsa.'),
      (36, 20081008, 'assassinato', 'City Park', 'Um corpo foi descoberto no parque. A vítima foi atropelada por um carro, e a polícia investiga se foi intencional.'),
      (37, 20150203, 'furto', 'Corporate Office', 'Um laptop contendo segredos da empresa foi roubado de um escritório seguro. Sem sinais de arrombamento.'),
      (38, 19950627, 'furto', 'Luxury Mall', 'Uma bolsa de grife foi roubada de uma vitrine. Um suspeito de terno foi visto nas imagens de vigilância.'),
      (39, 20030410, 'suborno', 'Construction Site', 'Um empreiteiro foi subornado para ignorar violações de segurança. A transação foi capturada em câmera.'),
      (40, 20091206, 'furto', 'Parking Garage', 'Um carro foi roubado de um estacionamento. Imagens de segurança mostram uma pessoa de moletom arrombando o veículo.'),
      (41, 20150722, 'assassinato', 'Street Corner', 'Um jovem foi encontrado morto perto de uma rua movimentada. A polícia investiga a causa da morte, possivelmente relacionada a drogas.'),
      (42, 19980305, 'furto', 'Shopping Mall', 'Uma maleta contendo dinheiro foi roubada de uma vitrine. Um suspeito de jaqueta vermelha foi visto perto da cena.'),
      (43, 20060119, 'suborno', 'Airport Lounge', 'Uma comissária de bordo foi pega aceitando suborno para deixar passageiros burlarem a segurança.'),
      (44, 20171003, 'furto', 'Car Dealership', NULL),
      (45, 20080409, 'assassinato', 'Night Club', 'Um homem foi encontrado morto no banheiro da boate. A polícia investiga se foi um negócio de drogas que deu errado.'),
      (46, 20140822, 'suborno', 'Public Office', 'Um oficial da cidade foi pego aceitando subornos de empreiteiros em troca de contratos governamentais.'),
      (47, 20031014, 'assassinato', 'Back Alley', 'Uma mulher foi encontrada morta com o pescoço quebrado. Nenhuma testemunha estava presente e nenhum suspeito foi identificado.'),
      (48, 20151209, 'furto', 'Restaurant', 'A bolsa de uma mulher foi roubada enquanto ela jantava. Um homem de jaqueta preta foi visto perto da mesa.'),
      (49, 19990217, 'suborno', 'Government Building', 'Um político foi pego recebendo subornos de um lobista. O acordo foi ouvido por um guarda de segurança.'),
      (50, 20100115, 'furto', 'Jewelry Store', 'Um anel de diamante foi roubado de uma joalheria de luxo. O ladrão usava um casaco preto e luvas.'),
      (51, 20090222, 'suborno', 'Courtroom', NULL),
      (52, 20061214, 'assassinato', 'Luxury Hotel', 'Um empresário foi encontrado morto em seu quarto de hotel. A polícia suspeita de crime, mas nenhum suspeito foi nomeado ainda.'),
      (53, 19980718, 'furto', 'Art Gallery', 'Uma pintura valiosa foi roubada durante uma exposição. Uma mulher de vestido vermelho foi vista saindo da galeria.'),
      (54, 20080304, 'suborno', 'Construction Site', NULL),
      (55, 19971005, 'assassinato', 'City Hospital', 'Uma enfermeira foi encontrada morta em um depósito do hospital. A polícia investiga o envolvimento de funcionários.'),
      (56, 20011117, 'suborno', 'Financial District', 'Um corretor foi pego subornando clientes para inflar seus investimentos.'),
      (57, 20070315, 'furto', 'Corporate Office', 'Um laptop da empresa com informações confidenciais foi roubado. Um homem de terno foi visto saindo do escritório com ele.'),
      (58, 20130321, 'assassinato', 'City Street', NULL),
      (59, 20141011, 'furto', 'Airport Terminal', 'A mala de um passageiro foi trocada com outra no terminal. O suspeito usava uma camisa vermelha.'),
      (60, 20100518, 'suborno', 'Public Office', 'Um oficial foi pego aceitando subornos para aprovar um projeto de construção sem inspeção adequada.'),
      (61, 19941122, 'assassinato', 'City Bar', 'Um homem foi encontrado morto após uma briga em um bar local. O suspeito fugiu da cena.'),
      (62, 20050329, 'furto', 'Luxury Mall', 'A bolsa de uma mulher foi roubada de uma loja de luxo. Um homem de jaqueta cinza foi visto saindo com ela.'),
      (63, 20170704, 'assassinato', 'Restaurant', 'Um chef foi encontrado morto na cozinha. Sem ferimentos óbvios, mas há suspeita de crime.'),
      (64, 20020301, 'suborno', 'Construction Site', 'Um empreiteiro foi subornado para ignorar violações de segurança em um novo projeto de construção.'),
      (65, 20061103, 'furto', 'Public Library', 'Um cartão de biblioteca com informações pessoais foi roubado da mesa do bibliotecário. Um suspeito foi visto saindo com ele.'),
      (66, 20121118, 'furto', 'Casino', 'Um homem foi visto pegando fichas de uma mesa desprotegida. O suspeito usava um moletom preto.'),
      (67, 19990514, 'assassinato', 'City Park', 'Um corpo foi descoberto perto do banco do parque. A causa da morte foi um tiro.'),
      (68, 20190906, 'suborno', 'University', 'Um professor foi pego aceitando subornos de alunos em troca de notas melhores.'),
      (69, 20071220, 'furto', 'Train Station', 'Um homem roubou uma mala de um passageiro na estação de trem. O suspeito usava jaqueta e chapéu.'),
      (70, 19990410, 'assassinato', 'Street Corner', NULL),
      (71, 20080111, 'furto', 'Restaurant', 'Uma bolsa foi roubada enquanto a vítima jantava. O suspeito foi visto saindo rapidamente.'),
      (72, 20180228, 'suborno', 'Municipal Office', 'Um oficial da cidade foi visto aceitando dinheiro de um empreiteiro local para acelerar seus projetos.'),
      (73, 20030504, 'furto', 'Library', 'Um livro raro foi roubado da biblioteca. O suspeito foi visto entrando e saindo da área restrita.'),
      (74, 20160622, 'assassinato', 'Downtown Alley', 'Uma mulher foi encontrada morta em um beco com sinais de trauma por objeto contundente na cabeça.'),
      (75, 19930310, 'furto', 'Parking Lot', NULL),
      (76, 19851120, 'furto', 'Blue Note Lounge', 'Uma maleta contendo documentos confidenciais desapareceu. Uma testemunha relatou um homem de sobretudo com uma cicatriz na bochecha esquerda fugindo da cena.'),
      (77, 20151019, 'assassinato', 'Office Building', 'Um gerente foi encontrado morto em seu escritório. A polícia suspeita que uma disputa no trabalho pode ter levado ao assassinato.'),
      (78, 20110225, 'furto', 'Art Auction', 'Uma pintura foi roubada durante um leilão. O ladrão foi visto fugindo da cena.'),
      (79, 19980507, 'suborno', 'Medical Center', NULL),
      (80, 20091229, 'furto', 'Airport Security', 'Uma bolsa contendo itens valiosos foi roubada durante a verificação de segurança.'),
      (81, 19941021, 'assassinato', 'Rooftop Bar', 'Um homem foi encontrado morto após uma discussão com outro cliente. Nenhuma arma foi encontrada na cena.'),
      (82, 20081116, 'furto', 'Corporate Office', 'Um laptop com informações confidenciais foi roubado. Sem sinais de arrombamento, mas um suspeito de terno foi visto.'),
      (83, 20030613, 'suborno', 'Hospital', 'Um médico foi pego aceitando dinheiro para fornecer laudos médicos falsos para seguros.'),
      (84, 20150607, 'assassinato', 'Woods', 'Um corpo foi descoberto na floresta com um ferimento de bala no peito. A polícia ainda procura suspeitos.'),
      (85, 20081005, 'furto', 'Shopping Mall', 'Uma carteira foi roubada de um comprador. O ladrão foi capturado na câmera usando um boné.'),
      (86, 20131011, 'suborno', 'City Council', 'Um vereador foi pego aceitando subornos para aprovar leis de zoneamento.'),
      (87, 20180503, 'furto', 'Luxury Store', 'Um homem foi visto pegando uma pulseira sem pagar.'),
      (88, 19921214, 'assassinato', 'Train Station', 'Um corpo foi encontrado perto dos trilhos. Investigadores acreditam que pode ter sido acidente ou crime.'),
      (89, 20070911, 'suborno', 'Corporate Office', NULL),
      (90, 20140206, 'furto', 'Tech Conference', 'Um laptop foi roubado durante a conferência. Um homem de moletom preto foi visto saindo da área.'),
      (91, 20100817, 'furto', 'Bookstore', 'Um livro de edição rara foi roubado da vitrine de uma livraria.'),
      (92, 19970103, 'suborno', 'Police Station', 'Um policial foi pego aceitando subornos de criminosos locais para ignorar suas atividades.'),
      (93, 20091129, 'assassinato', 'House', 'Um corpo foi encontrado em uma casa com sinais de estrangulamento.'),
      (94, 19960521, 'furto', 'Gallery', 'Uma pintura foi roubada durante uma exposição.'),
      (95, 20131028, 'suborno', 'Post Office', 'Um funcionário dos correios foi pego aceitando dinheiro para adulterar correspondências.'),
      (96, 20080303, 'assassinato', 'Lakeside', NULL),
      (97, 20030512, 'furto', 'Gas Station', 'Um caixa foi roubado à mão armada. O ladrão levou o dinheiro do caixa registrador.'),
      (98, 20150717, 'suborno', 'School', 'Um professor foi pego aceitando subornos de pais para dar notas melhores a seus filhos.'),
      (99, 20090611, 'furto', 'Construction Site', 'Um caminhão cheio de equipamentos foi roubado de um canteiro de obras.'),
      (100, 20180320, 'assassinato', 'Club', 'Um homem foi morto durante uma briga dentro de uma boate. O suspeito foi visto saindo da cena.')
    ;`,

  // Create and populate the suspects table
  `CREATE TABLE suspects (
      id INTEGER PRIMARY KEY,
      name TEXT,
      attire TEXT,
      scar TEXT
    );`,
  `INSERT INTO suspects (id, name, attire, scar) VALUES
      (1, 'Michael Johnson', 'nenhum', 'nenhuma'),
      (2, 'Tony DeMarco', 'terno', 'nenhuma'),
      (3, 'Frankie Lombardi', 'sobretudo', 'bochecha esquerda'),
      (4, 'Carlos Garcia', 'jaqueta', 'braço direito'),
      (5, 'Marko Shvets', 'camiseta', 'nenhuma'),
      (6, 'Amanda Taylor', 'blusa', 'perna direita'),
      (7, 'Richard Brown', 'smoking', 'nenhuma'),
      (8, 'Heather Williams', 'vestido', 'mão esquerda'),
      (9, 'Joshua Smith', 'terno', 'nenhuma'),
      (10, 'Claire Green', 'cardigã', 'nenhuma'),
      (11, 'Evan Davis', 'suéter', 'ombro direito'),
      (12, 'Nina Patel', 'saia', 'braço esquerdo'),
      (13, 'Sam Johnson', 'jaqueta', 'nenhuma'),
      (14, 'Maya Nguyen', 'camiseta', 'nenhuma'),
      (15, 'Daniel King', 'blazer', 'coxa esquerda'),
      (16, 'Laura Wright', 'terno', 'nenhuma'),
      (17, 'Chris Scott', 'moletom', 'pulso direito'),
      (18, 'Sophie Harris', 'suéter', 'pé esquerdo'),
      (19, 'Tommy Walker', 'smoking', 'nenhuma'),
      (20, 'Ava Lewis', 'vestido', 'joelho esquerdo'),
      (21, 'Victor Carter', 'terno', 'nenhuma'),
      (22, 'Mason Clark', 'jaqueta', 'orelha esquerda'),
      (23, 'Zoe Mitchell', 'cardigã', 'nenhuma'),
      (24, 'Oliver Hall', 'suéter', 'nenhuma'),
      (25, 'Ellie Anderson', 'camiseta', 'pé direito'),
      (26, 'Andrew Moore', 'blazer', 'bochecha direita'),
      (27, 'Penny Turner', 'terno', 'nenhuma'),
      (28, 'Benjamin Lopez', 'jaqueta', 'nenhuma'),
      (29, 'Sophia Martin', 'vestido', 'ombro esquerdo'),
      (30, 'Matthew Collins', 'smoking', 'nenhuma'),
      (31, 'Emily Adams', 'moletom', 'nenhuma'),
      (32, 'Lucas Stewart', 'blusa', 'nenhuma'),
      (33, 'Chloe Baker', 'saia', 'nenhuma'),
      (34, 'Liam Mitchell', 'camiseta', 'pulso esquerdo'),
      (35, 'Charlotte White', 'blazer', 'nenhuma'),
      (36, 'James Young', 'cardigã', 'perna direita'),
      (37, 'Ella King', 'terno', 'nenhuma'),
      (38, 'Lucas Scott', 'jaqueta', 'bochecha esquerda'),
      (39, 'Aiden Gonzalez', 'moletom', 'nenhuma'),
      (40, 'Amelia Green', 'vestido', 'pulso esquerdo'),
      (41, 'William Johnson', 'smoking', 'nenhuma'),
      (42, 'Mila Roberts', 'suéter', 'mão direita'),
      (43, 'Jackson Mitchell', 'blazer', 'nenhuma'),
      (44, 'Grace Moore', 'camiseta', 'joelho direito'),
      (45, 'John Lee', 'cardigã', 'nenhuma'),
      (46, 'Lily Jackson', 'jaqueta', 'nenhuma'),
      (47, 'Daniel Taylor', 'moletom', 'nenhuma'),
      (48, 'Sophie Harris', 'blazer', 'nenhuma'),
      (49, 'Benjamin White', 'terno', 'nenhuma'),
      (50, 'Dylan Walker', 'smoking', 'nenhuma'),
      (51, 'Gabriella Cooper', 'suéter', 'nenhuma'),
      (52, 'Sebastian Smith', 'jaqueta', 'mão esquerda'),
      (53, 'Sophie Jones', 'cardigã', 'nenhuma'),
      (54, 'Ethan Brown', 'camiseta', 'ombro direito'),
      (55, 'Elijah Johnson', 'moletom', 'nenhuma'),
      (56, 'Charlotte Robinson', 'blazer', 'nenhuma'),
      (57, 'Maddison Lewis', 'terno', 'nenhuma'),
      (58, 'Alexander Campbell', 'vestido', 'joelho esquerdo'),
      (59, 'Mia Cooper', 'saia', 'braço direito'),
      (60, 'Ethan Carter', 'blusa', 'nenhuma'),
      (61, 'Sophia Harris', 'jaqueta', 'coxa esquerda'),
      (62, 'Grace Scott', 'blazer', 'nenhuma'),
      (63, 'Benjamin Miller', 'terno', 'bochecha direita'),
      (64, 'Madeline Taylor', 'suéter', 'nenhuma'),
      (65, 'Olivia Young', 'camiseta', 'nenhuma'),
      (66, 'Jack Mitchell', 'jaqueta', 'pulso direito'),
      (67, 'Isabella Wilson', 'vestido', 'braço esquerdo'),
      (68, 'Aiden Turner', 'blusa', 'perna direita'),
      (69, 'Aria Morgan', 'suéter', 'nenhuma'),
      (70, 'Ryan Nelson', 'moletom', 'joelho esquerdo'),
      (71, 'Lily White', 'terno', 'nenhuma'),
      (72, 'James Carter', 'cardigã', 'nenhuma'),
      (73, 'Chloe Anderson', 'smoking', 'nenhuma'),
      (74, 'Ava Moore', 'blazer', 'nenhuma'),
      (75, 'Michael Scott', 'vestido', 'bochecha esquerda'),
      (76, 'Emma Hall', 'jaqueta', 'nenhuma'),
      (77, 'David Davis', 'suéter', 'mão direita'),
      (78, 'Lucas White', 'camiseta', 'pulso esquerdo'),
      (79, 'Lily Smith', 'moletom', 'nenhuma'),
      (80, 'Mason Turner', 'blazer', 'joelho direito'),
      (81, 'Matthew Jackson', 'terno', 'nenhuma'),
      (82, 'Sophie Robinson', 'cardigã', 'nenhuma'),
      (83, 'Isaac Martin', 'jaqueta', 'nenhuma'),
      (84, 'Maya Green', 'suéter', 'mão esquerda'),
      (85, 'James Lee', 'camiseta', 'bochecha direita'),
      (86, 'Jack Robinson', 'blazer', 'nenhuma'),
      (87, 'Olivia Walker', 'vestido', 'nenhuma'),
      (88, 'Ella Cooper', 'suéter', 'pulso direito'),
      (89, 'Liam Davis', 'blusa', 'nenhuma'),
      (90, 'Oliver Harris', 'cardigã', 'nenhuma'),
      (91, 'Charlotte King', 'jaqueta', 'nenhuma'),
      (92, 'David Young', 'terno', 'nenhuma'),
      (93, 'Sebastian Lewis', 'smoking', 'nenhuma'),
      (94, 'Emma Carter', 'vestido', 'nenhuma'),
      (95, 'Maxwell Taylor', 'jaqueta', 'orelha esquerda'),
      (96, 'Benjamin White', 'moletom', 'nenhuma'),
      (97, 'Chloe Lee', 'blazer', 'nenhuma'),
      (98, 'Amelia Walker', 'camiseta', 'nenhuma'),
      (99, 'Dylan Lewis', 'blusa', 'perna direita'),
      (100, 'Ryan Green', 'cardigã', 'nenhuma'),
      (101, 'Sophie Turner', 'terno', 'nenhuma'),
      (102, 'Lucas Scott', 'suéter', 'pulso esquerdo'),
      (103, 'Maddison Carter', 'jaqueta', 'ombro direito'),
      (104, 'Jackson Brown', 'blazer', 'nenhuma'),
      (105, 'Victoria Cooper', 'vestido', 'nenhuma'),
      (106, 'Evan Lewis', 'camiseta', 'nenhuma'),
      (107, 'David Wilson', 'blusa', 'bochecha esquerda'),
      (108, 'Sophia Green', 'cardigã', 'nenhuma'),
      (109, 'Charlotte Harris', 'jaqueta', 'nenhuma'),
      (110, 'Oliver Carter', 'suéter', 'mão direita'),
      (111, 'Emily Taylor', 'smoking', 'nenhuma'),
      (112, 'John White', 'blazer', 'nenhuma'),
      (113, 'Amelia Brown', 'moletom', 'nenhuma'),
      (114, 'Lucas Moore', 'vestido', 'joelho esquerdo'),
      (115, 'David Cooper', 'terno', 'nenhuma'),
      (116, 'Oliver Harris', 'camiseta', 'nenhuma'),
      (117, 'Maya Walker', 'cardigã', 'pé direito'),
      (118, 'Sophia Green', 'blusa', 'nenhuma'),
      (119, 'James Taylor', 'suéter', 'nenhuma'),
      (120, 'Mason Brown', 'jaqueta', 'nenhuma'),
      (121, 'Olivia King', 'camiseta', 'coxa esquerda'),
      (122, 'Charlotte White', 'moletom', 'nenhuma'),
      (123, 'Mia Davis', 'vestido', 'nenhuma'),
      (124, 'Maddison Turner', 'jaqueta', 'pulso direito'),
      (125, 'Isabella Martin', 'terno', 'nenhuma'),
      (126, 'Benjamin White', 'blazer', 'nenhuma'),
      (127, 'David Lewis', 'suéter', 'nenhuma'),
      (128, 'Sophie Green', 'cardigã', 'bochecha esquerda'),
      (129, 'Liam Martin', 'smoking', 'nenhuma'),
      (130, 'Ella Turner', 'jaqueta', 'nenhuma'),
      (131, 'Chloe King', 'camiseta', 'pé direito'),
      (132, 'Sebastian Walker', 'blusa', 'nenhuma'),
      (133, 'Olivia White', 'terno', 'nenhuma'),
      (134, 'Mason Turner', 'vestido', 'nenhuma'),
      (135, 'Victor Brown', 'suéter', 'nenhuma'),
      (136, 'Benjamin Harris', 'blazer', 'nenhuma'),
      (137, 'Isabella Davis', 'camiseta', 'nenhuma'),
      (138, 'Mia Green', 'cardigã', 'braço direito'),
      (139, 'Liam Brown', 'jaqueta', 'nenhuma'),
      (140, 'Emily White', 'suéter', 'nenhuma'),
      (141, 'Olivia Turner', 'smoking', 'nenhuma'),
      (142, 'David King', 'blazer', 'nenhuma'),
      (143, 'Matthew Scott', 'suéter', 'ombro direito'),
      (144, 'Isabella White', 'vestido', 'nenhuma'),
      (145, 'Aiden Harris', 'cardigã', 'nenhuma'),
      (146, 'Benjamin Green', 'jaqueta', 'nenhuma'),
      (147, 'Sophia Turner', 'moletom', 'nenhuma'),
      (148, 'Oliver Harris', 'camiseta', 'nenhuma'),
      (149, 'Ethan King', 'blazer', 'nenhuma'),
      (150, 'Chloe Brown', 'cardigã', 'nenhuma'),
      (151, 'Zoe Taylor', 'jaqueta', 'nenhuma'),
      (152, 'Lucas Carter', 'blusa', 'nenhuma'),
      (153, 'Sophia Martin', 'terno', 'nenhuma'),
      (154, 'Mason Lee', 'camiseta', 'nenhuma'),
      (155, 'Olivia White', 'cardigã', 'nenhuma'),
      (156, 'Benjamin Scott', 'moletom', 'nenhuma'),
      (157, 'Chloe Davis', 'vestido', 'nenhuma'),
      (158, 'Liam Young', 'suéter', 'nenhuma'),
      (159, 'David Green', 'blazer', 'nenhuma'),
      (160, 'Ethan Taylor', 'jaqueta', 'nenhuma'),
      (161, 'Olivia King', 'smoking', 'nenhuma'),
      (162, 'Sophie Harris', 'suéter', 'nenhuma'),
      (163, 'Lily Brown', 'cardigã', 'nenhuma'),
      (164, 'Benjamin Walker', 'terno', 'nenhuma'),
      (165, 'Matthew Davis', 'camiseta', 'nenhuma'),
      (166, 'Victor Young', 'jaqueta', 'nenhuma'),
      (167, 'Isabella White', 'blusa', 'nenhuma'),
      (168, 'David Brown', 'suéter', 'nenhuma'),
      (169, 'Chloe Walker', 'cardigã', 'nenhuma'),
      (170, 'Olivia Green', 'smoking', 'nenhuma'),
      (171, 'Zoe Harris', 'vestido', 'nenhuma'),
      (172, 'Liam White', 'terno', 'nenhuma'),
      (173, 'Benjamin Carter', 'suéter', 'nenhuma'),
      (174, 'Sophie Turner', 'jaqueta', 'nenhuma'),
      (175, 'Lucas Brown', 'blusa', 'nenhuma'),
      (176, 'Mason White', 'camiseta', 'nenhuma'),
      (177, 'David Harris', 'cardigã', 'nenhuma'),
      (178, 'Olivia King', 'vestido', 'nenhuma'),
      (179, 'Liam Turner', 'blazer', 'nenhuma'),
      (180, 'Sophie Davis', 'moletom', 'nenhuma'),
      (181, 'Victor Green', 'smoking', 'nenhuma'),
      (182, 'Sophia Taylor', 'suéter', 'nenhuma'),
      (183, 'Vincent Malone', 'sobretudo', 'bochecha esquerda'),
      (184, 'Benjamin Young', 'blusa', 'nenhuma'),
      (185, 'Olivia White', 'cardigã', 'nenhuma'),
      (186, 'Mason Davis', 'terno', 'nenhuma'),
      (187, 'David King', 'camiseta', 'nenhuma'),
      (188, 'Chloe Brown', 'jaqueta', 'nenhuma'),
      (189, 'Victor Harris', 'moletom', 'nenhuma'),
      (190, 'Sophie King', 'blusa', 'nenhuma'),
      (191, 'Olivia Green', 'smoking', 'nenhuma'),
      (192, 'Isabella Walker', 'vestido', 'nenhuma'),
      (193, 'Benjamin White', 'cardigã', 'nenhuma'),
      (194, 'Ethan Turner', 'suéter', 'nenhuma'),
      (195, 'David Brown', 'jaqueta', 'nenhuma'),
      (196, 'Chloe Walker', 'blusa', 'nenhuma'),
      (197, 'Liam Davis', 'camiseta', 'nenhuma'),
      (198, 'Olivia White', 'terno', 'nenhuma'),
      (199, 'Victor Green', 'cardigã', 'nenhuma'),
      (200, 'Sophie Taylor', 'blazer', 'nenhuma'),
      (201, 'Mason Walker', 'smoking', 'nenhuma'),
      (202, 'David White', 'suéter', 'nenhuma'),
      (203, 'Olivia Brown', 'jaqueta', 'nenhuma'),
      (204, 'Zoe King', 'blusa', 'nenhuma'),
      (205, 'Liam Young', 'cardigã', 'nenhuma'),
      (206, 'Sophie Green', 'terno', 'nenhuma'),
      (207, 'Victor White', 'camiseta', 'nenhuma'),
      (208, 'Olivia Davis', 'blazer', 'nenhuma'),
      (209, 'Lucas Brown', 'moletom', 'nenhuma'),
      (210, 'David Harris', 'jaqueta', 'nenhuma'),
      (211, 'Sophie Turner', 'suéter', 'nenhuma'),
      (212, 'Isabella King', 'blusa', 'nenhuma'),
      (213, 'Benjamin Green', 'cardigã', 'nenhuma'),
      (214, 'Ethan Davis', 'smoking', 'nenhuma'),
      (215, 'Victor Brown', 'terno', 'nenhuma'),
      (216, 'Lily White', 'jaqueta', 'nenhuma'),
      (217, 'Mason King', 'camiseta', 'nenhuma'),
      (218, 'David Taylor', 'blazer', 'nenhuma'),
      (219, 'Olivia Walker', 'moletom', 'nenhuma'),
      (220, 'Lucas Davis', 'suéter', 'nenhuma'),
      (221, 'Zoe Brown', 'cardigã', 'nenhuma'),
      (222, 'Sophia Taylor', 'blusa', 'nenhuma'),
      (223, 'Victor Walker', 'jaqueta', 'nenhuma'),
      (224, 'Mason Green', 'camiseta', 'nenhuma'),
      (225, 'Ethan Brown', 'blazer', 'nenhuma'),
      (226, 'David Harris', 'vestido', 'nenhuma'),
      (227, 'Olivia Walker', 'terno', 'nenhuma'),
      (228, 'Zoe Taylor', 'moletom', 'nenhuma'),
      (229, 'Lucas Green', 'cardigã', 'nenhuma'),
      (230, 'Victor King', 'blusa', 'nenhuma'),
      (231, 'Isabella Harris', 'terno', 'nenhuma'),
      (232, 'Benjamin Green', 'jaqueta', 'nenhuma'),
      (233, 'Olivia Brown', 'camiseta', 'nenhuma'),
      (234, 'David Walker', 'moletom', 'nenhuma'),
      (235, 'Victor Davis', 'blazer', 'nenhuma'),
      (236, 'Sophie King', 'vestido', 'nenhuma'),
      (237, 'Christopher Black', 'sobretudo', 'bochecha direita'),
      (238, 'Mason Taylor', 'suéter', 'nenhuma'),
      (239, 'Olivia Green', 'cardigã', 'nenhuma'),
      (240, 'Victor Brown', 'blusa', 'nenhuma'),
      (241, 'Liam White', 'camiseta', 'nenhuma'),
      (242, 'Ethan King', 'terno', 'nenhuma'),
      (243, 'Sophia Brown', 'moletom', 'nenhuma'),
      (244, 'Olivia Taylor', 'blazer', 'nenhuma'),
      (245, 'David Walker', 'jaqueta', 'nenhuma'),
      (246, 'Benjamin Green', 'cardigã', 'nenhuma'),
      (247, 'Victor White', 'camiseta', 'nenhuma'),
      (248, 'Zoe Brown', 'blusa', 'nenhuma'),
      (249, 'Lucas Green', 'terno', 'nenhuma'),
      (250, 'Mason King', 'moletom', 'nenhuma'),
      (251, 'David Brown', 'terno', 'nenhuma'),
      (252, 'Olivia Green', 'blazer', 'perna esquerda'),
      (253, 'Victor Taylor', 'jaqueta', 'nenhuma'),
      (254, 'Mason Walker', 'blusa', 'nenhuma'),
      (255, 'Zoe Harris', 'suéter', 'nenhuma'),
      (256, 'Isabella Brown', 'cardigã', 'nenhuma'),
      (257, 'Ethan Green', 'camiseta', 'bochecha esquerda'),
      (258, 'Sophie White', 'moletom', 'nenhuma'),
      (259, 'Olivia Brown', 'vestido', 'nenhuma'),
      (260, 'David King', 'blazer', 'nenhuma'),
      (261, 'Zoe Green', 'terno', 'nenhuma'),
      (262, 'Mason White', 'camiseta', 'nenhuma'),
      (263, 'Benjamin Walker', 'jaqueta', 'mão direita'),
      (264, 'Olivia Brown', 'moletom', 'nenhuma'),
      (265, 'Victor Green', 'suéter', 'joelho esquerdo'),
      (266, 'Sophie Harris', 'smoking', 'nenhuma'),
      (267, 'Isabella Brown', 'vestido', 'nenhuma'),
      (268, 'Mason King', 'blusa', 'pé direito'),
      (269, 'Zoe White', 'cardigã', 'nenhuma'),
      (270, 'David Taylor', 'jaqueta', 'nenhuma'),
      (271, 'Lucas Green', 'camiseta', 'pulso esquerdo'),
      (272, 'Victor Brown', 'terno', 'nenhuma'),
      (273, 'Benjamin White', 'blazer', 'nenhuma'),
      (274, 'Isabella Harris', 'suéter', 'nenhuma'),
      (275, 'Sophie Brown', 'jaqueta', 'nenhuma'),
      (276, 'Olivia Green', 'camiseta', 'nenhuma'),
      (277, 'David White', 'blusa', 'nenhuma'),
      (278, 'Victor Taylor', 'terno', 'nenhuma'),
      (279, 'Liam Green', 'cardigã', 'nenhuma'),
      (280, 'Mason Brown', 'moletom', 'nenhuma'),
      (281, 'Sophia White', 'vestido', 'nenhuma'),
      (282, 'Zoe King', 'blazer', 'nenhuma'),
      (283, 'David Harris', 'jaqueta', 'ombro esquerdo'),
      (284, 'Victor White', 'smoking', 'nenhuma'),
      (285, 'Olivia Brown', 'suéter', 'nenhuma'),
      (286, 'Lucas King', 'blusa', 'nenhuma'),
      (287, 'Mason White', 'cardigã', 'nenhuma'),
      (288, 'Sophia Taylor', 'camiseta', 'nenhuma'),
      (289, 'Isabella Harris', 'jaqueta', 'nenhuma'),
      (290, 'Ethan Green', 'blazer', 'nenhuma'),
      (291, 'David Brown', 'terno', 'nenhuma'),
      (292, 'Olivia King', 'moletom', 'nenhuma'),
      (293, 'Mason Green', 'vestido', 'nenhuma'),
      (294, 'Victor Brown', 'blusa', 'nenhuma'),
      (295, 'Sophia White', 'blazer', 'nenhuma'),
      (296, 'Isabella King', 'jaqueta', 'mão esquerda'),
      (297, 'Zoe Brown', 'cardigã', 'nenhuma'),
      (298, 'Mason Taylor', 'suéter', 'nenhuma'),
      (299, 'David Harris', 'blusa', 'nenhuma'),
      (300, 'Olivia Green', 'terno', 'nenhuma'),
      (301, 'Zoe White', 'jaqueta', 'nenhuma'),
      (302, 'Victor Brown', 'suéter', 'nenhuma'),
      (303, 'Mason Harris', 'moletom', 'nenhuma'),
      (304, 'Lucas White', 'blazer', 'nenhuma'),
      (305, 'Benjamin King', 'camiseta', 'nenhuma'),
      (306, 'Isabella Green', 'terno', 'nenhuma'),
      (307, 'David Brown', 'blusa', 'nenhuma'),
      (308, 'Olivia Walker', 'moletom', 'nenhuma'),
      (309, 'Sophia White', 'blazer', 'nenhuma'),
      (310, 'Zoe Taylor', 'vestido', 'nenhuma'),
      (311, 'Mason Brown', 'suéter', 'nenhuma'),
      (312, 'Victor Harris', 'jaqueta', 'nenhuma'),
      (313, 'Sophia Green', 'camiseta', 'nenhuma'),
      (314, 'Benjamin Taylor', 'blazer', 'nenhuma'),
      (315, 'Zoe Walker', 'moletom', 'nenhuma'),
      (316, 'David King', 'terno', 'nenhuma'),
      (317, 'Isabella White', 'blusa', 'nenhuma'),
      (318, 'Mason Taylor', 'jaqueta', 'nenhuma'),
      (319, 'Victor Green', 'blazer', 'nenhuma'),
      (320, 'Sophia King', 'cardigã', 'nenhuma'),
      (321, 'Lucas White', 'suéter', 'nenhuma'),
      (322, 'Benjamin Green', 'blusa', 'nenhuma'),
      (323, 'Olivia Brown', 'jaqueta', 'nenhuma'),
      (324, 'Victor King', 'moletom', 'nenhuma'),
      (325, 'Zoe Brown', 'terno', 'nenhuma'),
      (326, 'Mason Harris', 'blazer', 'nenhuma'),
      (327, 'David White', 'cardigã', 'nenhuma'),
      (328, 'Olivia King', 'suéter', 'nenhuma'),
      (329, 'Sophie Taylor', 'jaqueta', 'nenhuma'),
      (330, 'Isabella Brown', 'blusa', 'nenhuma'),
      (331, 'Mason Green', 'camiseta', 'nenhuma'),
      (332, 'Lucas White', 'vestido', 'nenhuma'),
      (333, 'David Harris', 'cardigã', 'nenhuma'),
      (334, 'Victor Green', 'jaqueta', 'nenhuma'),
      (335, 'Sophie White', 'blazer', 'nenhuma'),
      (336, 'Benjamin Brown', 'terno', 'nenhuma'),
      (337, 'Olivia Taylor', 'jaqueta', 'nenhuma'),
      (338, 'Mason Walker', 'blusa', 'nenhuma'),
      (339, 'Victor Harris', 'suéter', 'nenhuma'),
      (340, 'Zoe Green', 'camiseta', 'nenhuma'),
      (341, 'Sophie Taylor', 'moletom', 'nenhuma'),
      (342, 'David White', 'blazer', 'nenhuma'),
      (343, 'Lucas Harris', 'terno', 'nenhuma'),
      (344, 'Olivia Brown', 'jaqueta', 'nenhuma'),
      (345, 'Victor Green', 'camiseta', 'nenhuma'),
      (346, 'Isabella Walker', 'blusa', 'nenhuma'),
      (347, 'Benjamin White', 'terno', 'nenhuma'),
      (348, 'Mason King', 'cardigã', 'nenhuma'),
      (349, 'Sophie Brown', 'vestido', 'nenhuma'),
      (350, 'David King', 'camiseta', 'nenhuma'),
      (351, 'Lucas White', 'blazer', 'nenhuma'),
      (352, 'Isabella Green', 'terno', 'nenhuma'),
      (353, 'Zoe Brown', 'jaqueta', 'nenhuma'),
      (354, 'Sophie White', 'suéter', 'nenhuma'),
      (355, 'Victor Taylor', 'cardigã', 'nenhuma'),
      (356, 'Benjamin Walker', 'blusa', 'nenhuma'),
      (357, 'Olivia Green', 'terno', 'nenhuma'),
      (358, 'Mason White', 'moletom', 'nenhuma'),
      (359, 'David Harris', 'jaqueta', 'nenhuma'),
      (360, 'Victor Brown', 'suéter', 'nenhuma'),
      (361, 'Zoe King', 'camiseta', 'nenhuma'),
      (362, 'Sophia White', 'blusa', 'nenhuma'),
      (363, 'Olivia Brown', 'cardigã', 'nenhuma'),
      (364, 'Isabella Green', 'jaqueta', 'nenhuma'),
      (365, 'David Brown', 'blazer', 'nenhuma'),
      (366, 'Mason White', 'terno', 'nenhuma'),
      (367, 'Victor Green', 'cardigã', 'nenhuma'),
      (368, 'Sophie Harris', 'blusa', 'nenhuma'),
      (369, 'Benjamin Walker', 'vestido', 'nenhuma'),
      (370, 'Olivia Brown', 'suéter', 'nenhuma'),
      (371, 'Victor Green', 'camiseta', 'nenhuma'),
      (372, 'Sophia White', 'blusa', 'nenhuma'),
      (373, 'Isabella Taylor', 'cardigã', 'nenhuma'),
      (374, 'Mason White', 'vestido', 'nenhuma'),
      (375, 'David Brown', 'terno', 'nenhuma'),
      (376, 'Sophie Green', 'blazer', 'nenhuma'),
      (377, 'Lucas White', 'camiseta', 'nenhuma'),
      (378, 'Olivia Harris', 'moletom', 'nenhuma'),
      (379, 'Victor White', 'suéter', 'nenhuma'),
      (380, 'Sophie Walker', 'jaqueta', 'nenhuma'),
      (381, 'Benjamin Brown', 'blusa', 'nenhuma'),
      (382, 'David White', 'cardigã', 'nenhuma'),
      (383, 'Lucas Green', 'smoking', 'nenhuma'),
      (384, 'Sophie Brown', 'vestido', 'nenhuma'),
      (385, 'Olivia King', 'blazer', 'nenhuma'),
      (386, 'Victor Green', 'jaqueta', 'nenhuma'),
      (387, 'Zoe Taylor', 'moletom', 'nenhuma'),
      (388, 'Isabella Walker', 'camiseta', 'nenhuma'),
      (389, 'Benjamin Brown', 'blazer', 'nenhuma'),
      (390, 'Mason Green', 'terno', 'nenhuma'),
      (391, 'David Walker', 'cardigã', 'nenhuma'),
      (392, 'Olivia Brown', 'jaqueta', 'nenhuma'),
      (393, 'Victor White', 'smoking', 'nenhuma'),
      (394, 'Sophia Green', 'vestido', 'nenhuma'),
      (395, 'Isabella Brown', 'terno', 'nenhuma'),
      (396, 'David King', 'blazer', 'nenhuma'),
      (397, 'Mason White', 'moletom', 'nenhuma'),
      (398, 'Victor Taylor', 'cardigã', 'nenhuma'),
      (399, 'Olivia Harris', 'suéter', 'nenhuma'),
      (400, 'Benjamin Walker', 'jaqueta', 'nenhuma')
    ;`,

  // Create and populate the interviews table
  `CREATE TABLE interviews (
      suspect_id INTEGER,
      transcript TEXT,
      FOREIGN KEY(suspect_id) REFERENCES suspects(id)
    );`,
  `INSERT INTO interviews (suspect_id, transcript) VALUES
      (1, NULL),
      (2, 'Eu estava em casa o dia todo, não faço ideia do que aconteceu.'),
      (3, NULL),
      (4, 'Não tenho lembrança desse evento.'),
      (5, 'Eu estava no trabalho, não poderia estar envolvido.'),
      (6, NULL),
      (7, 'Eu estava com amigos em um restaurante.'),
      (8, 'Não sei nada sobre o incidente.'),
      (9, NULL),
      (10, 'Eu nem sabia que algo estava acontecendo.'),
      (11, NULL),
      (12, 'Não vi nada suspeito.'),
      (13, NULL),
      (14, 'Eu estava viajando fora da cidade.'),
      (15, NULL),
      (16, 'Eu estava com a família a noite toda.'),
      (17, 'Eu estava dormindo nessa hora.'),
      (18, NULL),
      (19, 'Não tenho ideia sobre a situação.'),
      (20, NULL),
      (21, 'Não ouvi nada, estava assistindo um filme.'),
      (22, 'Estava preso no trânsito, não vi nada.'),
      (23, NULL),
      (24, 'Não faço ideia sobre esse evento.'),
      (25, NULL),
      (26, 'Eu nem estava na área, desculpe.'),
      (27, 'Não tenho conexão com o incidente.'),
      (28, NULL),
      (29, 'Eu não estava perto do local.'),
      (30, NULL),
      (31, 'Eu não fiz parte de nada disso.'),
      (32, NULL),
      (33, 'Não tive participação em nada.'),
      (34, NULL),
      (35, 'Não estava envolvido em nada suspeito.'),
      (36, 'Estava saindo com amigos, nem ouvi sobre isso.'),
      (37, NULL),
      (38, 'Não tenho certeza do que aconteceu, mas não estava perto.'),
      (39, NULL),
      (40, 'Não tenho ideia sobre a situação.'),
      (41, NULL),
      (42, 'Eu não estava nem perto daquela área.'),
      (43, 'Não sei nada sobre isso, desculpe.'),
      (44, NULL),
      (45, 'Estava ocupado no trabalho, sem tempo para mais nada.'),
      (46, NULL),
      (47, 'Não tive nada a ver com isso, sou inocente.'),
      (48, NULL),
      (49, 'Eu nem sabia que estava acontecendo.'),
      (50, 'Eu estava com um amigo o tempo todo.'),
      (51, NULL),
      (52, 'Eu não estava lá e não sei de nada.'),
      (53, NULL),
      (54, 'Não estou envolvido de forma alguma.'),
      (55, NULL),
      (56, 'Não ouvi nada, estava ocupado.'),
      (57, NULL),
      (58, 'Não vi nada estranho.'),
      (59, NULL),
      (60, 'Não sei nada sobre o que aconteceu.'),
      (61, NULL),
      (62, 'Estava fora da cidade naquele dia, sem ideia.'),
      (63, NULL),
      (64, 'Não vi nada incomum acontecendo.'),
      (65, NULL),
      (66, 'Não estava envolvido, tenho um álibi.'),
      (67, 'Não fiz parte disso, eu juro.'),
      (68, NULL),
      (69, 'Eu nem sabia que havia algo acontecendo.'),
      (70, 'Não tenho nada a ver com isso.'),
      (71, NULL),
      (72, 'Eu estava na loja, nada a ver com isso.'),
      (73, 'Eu não estava na área, tenho provas.'),
      (74, NULL),
      (75, 'Não sei de nada, eu juro.'),
      (76, NULL),
      (77, 'Eu não estava nem perto de lá.'),
      (78, 'Eu estava em casa, cuidando da minha vida.'),
      (79, NULL),
      (80, 'Eu não fiz parte de nada disso.'),
      (81, 'Não ouvi nada naquela noite.'),
      (82, NULL),
      (83, 'Não sei, eu não estava lá.'),
      (84, NULL),
      (85, 'Não fazia ideia do que estava acontecendo.'),
      (86, NULL),
      (87, 'Não vi nada estranho.'),
      (88, NULL),
      (89, 'Não sei nada sobre isso.'),
      (90, 'Eu estava com meus amigos, sem envolvimento.'),
      (91, NULL),
      (92, 'Eu estava em casa, nada aconteceu ao meu redor.'),
      (93, NULL),
      (94, 'Eu nem sei o que aconteceu.'),
      (95, 'Eu estava em outro lugar, não poderia ser eu.'),
      (96, NULL),
      (97, 'Eu não estava perto de lá, eu prometo.'),
      (98, NULL),
      (99, 'Eu nem sei sobre o crime.'),
      (100, 'Eu não estava perto do local, sem ideia.'),
      (101, NULL),
      (102, 'Eu não estava lá, posso provar.'),
      (103, 'Não tenho nada a dizer sobre isso.'),
      (104, NULL),
      (105, 'Não ouvi nem vi nada.'),
      (106, NULL),
      (107, 'Sou inocente, não fiz nada.'),
      (108, NULL),
      (109, 'Eu não estava na cidade durante o incidente.'),
      (110, NULL),
      (111, 'Não sei quem está por trás disso.'),
      (112, 'Eu não estava nem perto de lá, eu juro.'),
      (113, NULL),
      (114, 'Eu nem sabia sobre o crime.'),
      (115, NULL),
      (116, 'Estava ocupado com o trabalho, não percebi nada.'),
      (117, 'Não vi nada, estava fora da cidade.'),
      (118, NULL),
      (119, 'Não estou envolvido, eu prometo.'),
      (120, 'Não sei nada sobre o furto.'),
      (121, NULL),
      (122, 'Eu não estava lá, não poderia ter feito nada.'),
      (123, 'Não tive parte nisso, eu juro.'),
      (124, NULL),
      (125, 'Eu nem sei de quem você está falando.'),
      (126, 'Não estava envolvido, nem ouvi sobre isso.'),
      (127, NULL),
      (128, 'Eu não estava perto daquele lugar, sem conexão alguma.'),
      (129, 'Não estava envolvido, confie em mim.'),
      (130, NULL),
      (131, 'Eu estava com um amigo a noite toda.'),
      (132, NULL),
      (133, 'Eu não estava na cidade naquela noite, de jeito nenhum.'),
      (134, NULL),
      (135, 'Eu nem sabia sobre o incidente.'),
      (136, NULL),
      (137, 'Eu não estava nem perto da área.'),
      (138, 'Eu estava na academia, não posso ser eu.'),
      (139, NULL),
      (140, 'Não vi nada naquela noite.'),
      (141, 'Não sei de nada, desculpe.'),
      (142, NULL),
      (143, 'Não ouvi nem vi nada, eu estava na cama.'),
      (144, 'Eu não estava lá, sou inocente.'),
      (145, NULL),
      (146, 'Eu não estava nem perto da cena do crime.'),
      (147, NULL),
      (148, 'Eu estava com a família, não vi nada.'),
      (149, NULL),
      (150, 'Não estava envolvido, eu juro pela minha vida.'),
      (151, NULL),
      (152, 'Não sei de nada, eu não estava lá.'),
      (153, 'Não tenho conexão com o incidente.'),
      (154, NULL),
      (155, 'Não fiz parte disso, tenho um álibi.'),
      (156, 'Não sei nada sobre o crime.'),
      (157, NULL),
      (158, 'Não vi nada, estava ocupado no trabalho.'),
      (159, 'Não sei nada sobre o furto.'),
      (160, NULL),
      (161, 'Eu não estava perto da cena do crime, eu juro.'),
      (162, NULL),
      (163, 'Eu nem sei sobre isso, desculpe.'),
      (164, NULL),
      (165, 'Eu não estava lá, eu prometo.'),
      (166, NULL),
      (167, 'Não estava envolvido de forma alguma, eu juro.'),
      (168, 'Não vi nada suspeito.'),
      (169, NULL),
      (170, 'Não sei do que você está falando.'),
      (171, NULL),
      (172, 'Eu nem ouvi sobre o crime.'),
      (173, 'Eu não estava perto da cena.'),
      (174, NULL),
      (175, 'Não tenho envolvimento nisso.'),
      (176, 'Não ouvi nada, eu estava dormindo.'),
      (177, NULL),
      (178, 'Não estava envolvido, eu juro.'),
      (179, 'Eu estava trabalhando naquele dia, não posso ser eu.'),
      (180, NULL),
      (181, 'Eu não estava perto do local, não vi nada.'),
      (182, NULL),
      (183, 'Eu não ia roubar, mas roubei.'),
      (184, 'Não faço ideia do que aconteceu.'),
      (185, NULL),
      (186, 'Eu estava em casa naquele dia, não sabia.'),
      (187, 'Não fiz parte disso, eu juro.'),
      (188, NULL),
      (189, 'Não sei nada sobre isso, eu não estava lá.'),
      (190, 'Não estava envolvido em nada disso.'),
      (191, NULL),
      (192, 'Não vi nada, eu juro.'),
      (193, 'Eu não estava por lá, estava ocupado no trabalho.'),
      (194, NULL),
      (195, 'Eu nem sabia sobre o crime.'),
      (196, NULL),
      (197, 'Não faço ideia de quem fez isso.'),
      (198, NULL),
      (199, 'Não estava envolvido, eu estava no parque.'),
      (200, 'Não vi nada suspeito, desculpe.')
    ;`,
];
