export default [
  // 1. Crime Scene Table
  `CREATE TABLE crime_scene (
      id INTEGER PRIMARY KEY,
      date INTEGER,
      type TEXT,
      location TEXT,
      description TEXT
    );`,
  `INSERT INTO crime_scene (id, date, type, location, description) VALUES
      (1, 20120909, 'furto', 'City Street', 'Um hóspede foi encontrado morto em seu quarto de hotel. Havia sinais de luta e sangue perto da cama.'),
      (2, 19920415, 'furto', 'Downtown Bank', 'Uma maleta foi roubada durante um assalto. Um homem de terno foi visto saindo do local com ela.'),
      (3, 20010702, 'assassinato', 'Corner Café', 'Um corpo foi encontrado atrás do café. Nenhuma testemunha relatou nada, mas havia uma ferida de faca nas costas.'),
      (4, 19980328, 'suborno', 'Metro Station', NULL),
      (5, 20091113, 'furto', 'Park Avenue Office', 'Uma maleta com documentos confidenciais foi roubada. Uma testemunha mencionou uma pessoa de blazer fugindo da cena.'),
      (6, 20050716, 'assassinato', 'Grand Hotel', 'Um hóspede foi encontrado morto em seu quarto com sinais de crime. A porta estava trancada por dentro, sem sinais de arrombamento.'),
      (7, 19960205, 'furto', 'City Library', 'Uma maleta contendo papéis confidenciais desapareceu. O ladrão foi capturado na câmera de segurança, usando uma jaqueta.'),
      (8, 20080422, 'suborno', 'Main Street Mall', NULL),
      (9, 20110630, 'furto', 'Old Town Square', 'Um homem foi visto fugindo com uma maleta. Ele tinha uma cicatriz na mão direita e usava um casaco.'),
      (10, 20031218, 'assassinato', 'Central Park', 'O corpo de uma mulher foi descoberto no parque com sinais de estrangulamento. Uma testemunha viu um homem usando um boné perto da cena.'),
      (11, 20120909, 'furto', 'City Museum', 'Uma maleta contendo artefatos valiosos foi levada. Um homem de sobretudo foi visto saindo da cena.'),
      (12, 20140512, 'furto', 'Airport Terminal', NULL),
      (13, 19950521, 'assassinato', 'Museum of Modern Art', 'Um artista proeminente foi encontrado morto em seu estúdio com múltiplas facadas. Nenhum suspeito foi identificado ainda.'),
      (14, 20060907, 'furto', 'Luxury Hotel', 'Uma maleta foi roubada de um hóspede. O ladrão usava um terno escuro e tinha uma cicatriz na bochecha direita.'),
      (15, 19980211, 'furto', 'Subway Station', 'Uma maleta desapareceu da plataforma. Um homem de jaqueta de couro foi visto com ela.'),
      (16, 20021225, 'suborno', 'Downtown Restaurant', NULL),
      (17, 20160114, 'assassinato', 'University Library', 'Um estudante foi encontrado morto perto da entrada da biblioteca. A causa da morte foi um tiro na cabeça.'),
      (18, 19910730, 'furto', 'Art Gallery', NULL),
      (19, 20050710, 'assassinato', 'Beachside Hotel', 'Um hóspede foi encontrado morto em seu quarto de hotel. Havia sinais de luta e sangue perto da cama.'),
      (20, 19990416, 'furto', 'City Plaza', 'Uma maleta desapareceu após um evento. Nenhum suspeito claro foi identificado, mas um homem de casaco cinza foi visto na área.'),
      (21, 20080312, 'furto', 'Luxury Mall', 'Uma maleta com bens valiosos foi roubada. O ladrão foi descrito usando uma jaqueta escura e tinha uma cicatriz visível.'),
      (22, 20100122, 'suborno', 'Highway Rest Stop', NULL),
      (23, 20151203, 'assassinato', 'Coffee Shop', 'Um barista foi encontrado morto atrás do balcão com um tiro. O suspeito foi visto saindo em um carro vermelho.'),
      (24, 20180418, 'suborno', 'City Hall', 'Um oficial corrupto da cidade foi pego aceitando suborno. Uma fita de vídeo mostrou a transação em um escritório privado.'),
      (25, 20120719, 'furto', 'Warehouse District', NULL),
      (26, 19980903, 'assassinato', 'Luxury Condo', 'Um corpo foi descoberto em um apartamento de luxo. A vítima tinha múltiplos ferimentos por arma de fogo.'),
      (27, 20060522, 'furto', 'Shopping Mall', 'Uma bolsa foi roubada da bolsa de uma mulher na praça de alimentação. Um homem de moletom vermelho foi visto na área.'),
      (28, 19941030, 'suborno', 'Corporate Office', 'Um CEO foi visto aceitando pagamentos ilegais de um empreiteiro. O contrato foi posteriormente cancelado sob circunstâncias suspeitas.'),
      (29, 20150914, 'furto', 'Train Station', NULL),
      (30, 20070426, 'suborno', 'Golf Club', 'Um escândalo de suborno envolvendo vários oficiais de alto escalão no clube. Um vídeo surgiu mostrando a troca de dinheiro.'),
      (31, 20010212, 'assassinato', 'Dark Alley', 'Um homem foi encontrado morto em um beco escuro com uma faca cravada no peito. Sem suspeitos ainda.'),
      (32, 20180125, 'furto', 'Bank Vault', 'Um cofre de banco foi arrombado durante a noite. Câmeras de segurança foram adulteradas e o culpado permanece não identificado.'),
      (33, 19961118, 'assassinato', 'Luxury Yacht', NULL),
      (34, 20030705, 'suborno', 'Subway Station', 'Um suborno foi oferecido a um oficial do metrô em troca de pular a catraca. O oficial relatou o incidente imediatamente.'),
      (35, 19921221, 'furto', 'Fashion Boutique', 'Um colar valendo milhares foi roubado durante um desfile de moda. Uma mulher foi vista saindo com ele na bolsa.'),
      (36, 20081008, 'assassinato', 'City Park', 'Um corpo foi descoberto no parque. A vítima foi atropelada por um carro, e a polícia investiga se foi intencional.'),
      (37, 20150203, 'furto', 'Corporate Office', 'Um laptop contendo segredos da empresa foi roubado de um escritório seguro. Sem sinais de arrombamento.'),
      (38, 19950627, 'furto', 'Luxury Mall', 'Uma bolsa de grife foi roubada de uma vitrine. Um suspeito de terno foi visto nas imagens de vigilância.'),
      (39, 20030410, 'suborno', 'Construction Site', 'Um empreiteiro foi subornado para ignorar violações de segurança. A transação foi capturada em câmera.'),
      (40, 20091206, 'furto', 'Parking Garage', 'Um carro foi roubado de um estacionamento. Imagens de segurança mostram uma pessoa de moletom arrombando o veículo.'),
      (41, 20150722, 'assassinato', 'Street Corner', 'Um jovem foi encontrado morto perto de uma rua movimentada. A polícia investiga a causa da morte, possivelmente relacionada a drogas.'),
      (42, 19980305, 'furto', 'Shopping Mall', 'Uma maleta contendo dinheiro foi roubada de uma vitrine. Um suspeito de jaqueta vermelha foi visto perto da cena.'),
      (43, 20060119, 'suborno', 'Airport Lounge', 'Uma comissária de bordo foi pega aceitando suborno para deixar passageiros burlarem a segurança.'),
      (44, 20171003, 'furto', 'Car Dealership', NULL),
      (45, 20080409, 'assassinato', 'Night Club', 'Um homem foi encontrado morto no banheiro da boate. A polícia investiga se foi um negócio de drogas que deu errado.'),
      (46, 20140822, 'suborno', 'Public Office', 'Um oficial da cidade foi pego aceitando subornos de empreiteiros em troca de contratos governamentais.'),
      (47, 20031014, 'assassinato', 'Back Alley', 'Uma mulher foi encontrada morta com o pescoço quebrado. Nenhuma testemunha estava presente e nenhum suspeito foi identificado.'),
      (48, 20151209, 'furto', 'Restaurant', 'A bolsa de uma mulher foi roubada enquanto ela jantava. Um homem de jaqueta preta foi visto perto da mesa.'),
      (49, 19990217, 'suborno', 'Government Building', 'Um político foi pego recebendo subornos de um lobista. O acordo foi ouvido por um guarda de segurança.'),
      (50, 20100115, 'furto', 'Jewelry Store', 'Um anel de diamante foi roubado de uma joalheria de luxo. O ladrão usava um casaco preto e luvas.'),
      (51, 20090222, 'suborno', 'Courtroom', NULL),
      (52, 20061214, 'assassinato', 'Luxury Hotel', 'Um empresário foi encontrado morto em seu quarto de hotel. A polícia suspeita de crime, mas nenhum suspeito foi nomeado ainda.'),
      (53, 19980718, 'furto', 'Art Gallery', 'Uma pintura valiosa foi roubada durante uma exposição. Uma mulher de vestido vermelho foi vista saindo da galeria.'),
      (54, 20080304, 'suborno', 'Construction Site', NULL),
      (55, 19971005, 'assassinato', 'City Hospital', 'Uma enfermeira foi encontrada morta em um depósito do hospital. A polícia investiga o envolvimento de funcionários.'),
      (56, 20011117, 'suborno', 'Financial District', 'Um corretor foi pego subornando clientes para inflar seus investimentos.'),
      (57, 20070315, 'furto', 'Corporate Office', 'Um laptop da empresa com informações confidenciais foi roubado. Um homem de terno foi visto saindo do escritório com ele.'),
      (58, 20130321, 'assassinato', 'City Street', NULL),
      (59, 20141011, 'furto', 'Airport Terminal', 'A mala de um passageiro foi trocada com outra no terminal. O suspeito usava uma camisa vermelha.'),
      (60, 20100518, 'suborno', 'Public Office', 'Um oficial foi pego aceitando subornos para aprovar um projeto de construção sem inspeção adequada.'),
      (61, 19941122, 'assassinato', 'City Bar', 'Um homem foi encontrado morto após uma briga em um bar local. O suspeito fugiu da cena.'),
      (62, 20050329, 'furto', 'Luxury Mall', 'A bolsa de uma mulher foi roubada de uma loja de luxo. Um homem de jaqueta cinza foi visto saindo com ela.'),
      (63, 20170704, 'assassinato', 'Restaurant', 'Um chef foi encontrado morto na cozinha. Sem ferimentos óbvios, mas há suspeita de crime.'),
      (64, 20020301, 'suborno', 'Construction Site', 'Um empreiteiro foi subornado para ignorar violações de segurança em um novo projeto de construção.'),
      (65, 19830715, 'furto', 'West Hollywood Records', 'Um disco de vinil valioso foi roubado da loja durante uma noite movimentada.'),
      (66, 20121118, 'furto', 'Casino', 'Um homem foi visto pegando fichas de uma mesa desprotegida. O suspeito usava um moletom preto.'),
      (67, 19990514, 'assassinato', 'City Park', 'Um corpo foi descoberto perto do banco do parque. A causa da morte foi um tiro.'),
      (68, 20190906, 'suborno', 'University', 'Um professor foi pego aceitando subornos de alunos em troca de notas melhores.'),
      (69, 20071220, 'furto', 'Train Station', 'Um homem roubou uma mala de um passageiro na estação de trem. O suspeito usava jaqueta e chapéu.'),
      (70, 19990410, 'assassinato', 'Street Corner', NULL),
      (71, 20080111, 'furto', 'Restaurant', 'Uma bolsa foi roubada enquanto a vítima jantava. O suspeito foi visto saindo rapidamente.'),
      (72, 20180228, 'suborno', 'Municipal Office', 'Um oficial da cidade foi visto aceitando dinheiro de um empreiteiro local para acelerar seus projetos.'),
      (73, 20030504, 'furto', 'Library', 'Um livro raro foi roubado da biblioteca. O suspeito foi visto entrando e saindo da área restrita.'),
      (74, 20160622, 'assassinato', 'Downtown Alley', 'Uma mulher foi encontrada morta em um beco com sinais de trauma por objeto contundente na cabeça.'),
      (75, 19930310, 'furto', 'Parking Lot', NULL),
      (76, 19851120, 'furto', 'Blue Note Lounge', 'Uma maleta contendo documentos confidenciais desapareceu. Uma testemunha relatou um homem de sobretudo com uma cicatriz na bochecha esquerda fugindo da cena.'),
      (77, 20151019, 'assassinato', 'Office Building', 'Um gerente foi encontrado morto em seu escritório. A polícia suspeita que uma disputa no trabalho pode ter levado ao assassinato.'),
      (78, 20110225, 'furto', 'Art Auction', 'Uma pintura foi roubada durante um leilão. O ladrão foi visto fugindo da cena.'),
      (79, 19980507, 'suborno', 'Medical Center', NULL),
      (80, 20091229, 'furto', 'Airport Security', 'Uma bolsa contendo itens valiosos foi roubada durante a verificação de segurança.'),
      (81, 19941021, 'assassinato', 'Rooftop Bar', 'Um homem foi encontrado morto após uma discussão com outro cliente. Nenhuma arma foi encontrada na cena.'),
      (82, 20081116, 'furto', 'Corporate Office', 'Um laptop com informações confidenciais foi roubado. Sem sinais de arrombamento, mas um suspeito de terno foi visto.'),
      (83, 20030613, 'suborno', 'Hospital', 'Um médico foi pego aceitando dinheiro para fornecer laudos médicos falsos para seguros.'),
      (84, 20150607, 'assassinato', 'Woods', 'Um corpo foi descoberto na floresta com um ferimento de bala no peito. A polícia ainda procura suspeitos.'),
      (85, 20081005, 'furto', 'Shopping Mall', 'Uma carteira foi roubada de um comprador. O ladrão foi capturado na câmera usando um boné.'),
      (86, 20131011, 'suborno', 'City Council', 'Um vereador foi pego aceitando subornos para aprovar leis de zoneamento.'),
      (87, 20180503, 'furto', 'Luxury Store', 'Um homem foi visto pegando uma pulseira sem pagar.'),
      (88, 19921214, 'assassinato', 'Train Station', 'Um corpo foi encontrado perto dos trilhos. Investigadores acreditam que pode ter sido acidente ou crime.'),
      (89, 20070911, 'suborno', 'Corporate Office', NULL),
      (90, 20140206, 'furto', 'Tech Conference', 'Um laptop foi roubado durante a conferência. Um homem de moletom preto foi visto saindo da área.'),
      (91, 20100817, 'furto', 'Bookstore', 'Um livro de edição rara foi roubado da vitrine de uma livraria.'),
      (92, 19970103, 'suborno', 'Police Station', 'Um policial foi pego aceitando subornos de criminosos locais para ignorar suas atividades.'),
      (93, 20091129, 'assassinato', 'House', 'Um corpo foi encontrado em uma casa com sinais de estrangulamento.'),
      (94, 19960521, 'furto', 'Gallery', 'Uma pintura foi roubada durante uma exposição.'),
      (95, 20131028, 'suborno', 'Post Office', 'Um funcionário dos correios foi pego aceitando dinheiro para adulterar correspondências.'),
      (96, 20080303, 'assassinato', 'Lakeside', NULL),
      (97, 20030512, 'furto', 'Gas Station', 'Um caixa foi roubado à mão armada. O ladrão levou o dinheiro do caixa registrador.'),
      (98, 20150717, 'suborno', 'School', 'Um professor foi pego aceitando subornos de pais para dar notas melhores a seus filhos.'),
      (99, 20090611, 'furto', 'Construction Site', 'Um caminhão cheio de equipamentos foi roubado de um canteiro de obras.'),
      (100, 20180320, 'assassinato', 'Club', 'Um homem foi morto durante uma briga dentro de uma boate. O suspeito foi visto saindo da cena.')
    ;`,

  // 2. Witnesses Table
  `CREATE TABLE witnesses (
      id INTEGER PRIMARY KEY,
      crime_scene_id INTEGER,
      clue TEXT,
      FOREIGN KEY (crime_scene_id) REFERENCES crime_scene(id)
    );`,
  `INSERT INTO witnesses (id, crime_scene_id, clue) VALUES
    (1, 66, 'Houve um estrondo e depois vi uma pessoa de jaqueta de couro fugindo.'),
    (2, 78, 'Vi uma mulher usando um cachecol vermelho andando perto da cena.'),
    (3, 44, NULL),
    (4, 75, 'Vi uma pessoa de jaqueta azul parada perto da cena do crime.'),
    (5, 89, 'Havia um carro preto estacionado por perto, acho que tinha vidros escuros.'),
    (6, 35, 'O suspeito tinha uma cicatriz na bochecha esquerda e usava um boné preto.'),
    (7, 55, NULL),
    (8, 12, 'Lembro de ouvir passos atrás de mim, mas não virei.'),
    (9, 44, NULL),
    (10, 78, 'Vi um homem correndo com uma maleta, parecendo muito suspeito.'),
    (11, 102, 'Notei uma mulher de vestido verde saindo da cena.'),
    (12, 67, 'Havia um carro esportivo vermelho estacionado perto do beco quando passei.'),
    (13, 94, NULL),
    (14, 33, 'O suspeito usava uma jaqueta de couro e carregava uma bolsa.'),
    (15, 53, 'Ouvi um estrondo antes de ver um homem saindo rapidamente do prédio.'),
    (16, 81, NULL),
    (17, 25, 'Uma pessoa com uma bandana amarela foi vista saindo da área.'),
    (18, 99, 'Vi uma van preta estacionada em frente ao prédio na hora do crime.'),
    (19, 56, NULL),
    (20, 14, 'O ladrão segurava um objeto brilhante enquanto corria pela rua.'),
    (21, 88, 'Lembro de uma mulher de vestido vermelho andando em direção ao prédio pouco antes do crime.'),
    (22, 101, NULL),
    (23, 63, 'Um homem suspeito de sobretudo estava rondando perto da cena do crime.'),
    (24, 42, 'Notei uma pessoa usando um moletom preto entrando no prédio pouco antes do crime.'),
    (25, 92, NULL),
    (26, 27, 'Vi alguém saindo da cena com uma bolsa de lona.'),
    (27, 48, 'O suspeito tinha um anel de prata no dedo e estava falando com alguém ao telefone.'),
    (28, 65, 'Vi um homem usando uma bandana vermelha saindo apressado da loja.'),
    (29, 39, NULL),
    (30, 59, 'Vi um homem com uma bandana azul e óculos de sol na área.'),
    (31, 83, NULL),
    (32, 28, 'Um homem suspeito de moletom cinza foi visto saindo do local rapidamente.'),
    (33, 77, 'Lembro de ver uma pessoa com uma maleta correndo em direção à saída.'),
    (34, 49, NULL),
    (35, 19, 'Vi uma pessoa com uma tatuagem distinta no pescoço perto da cena.'),
    (36, 18, 'O suspeito tinha uma mochila preta e andava muito rápido.'),
    (37, 24, NULL),
    (38, 9, 'Vi um homem com uma corrente de ouro no pescoço perto da cena do crime.'),
    (39, 74, 'Havia uma mulher de vestido preto perto da cena quando aconteceu.'),
    (40, 95, NULL),
    (41, 40, 'Ouvi alguém gritar e depois vi uma pessoa de casaco branco correndo.'),
    (42, 31, NULL),
    (43, 61, 'Uma pessoa de chapéu vermelho foi vista saindo rapidamente do prédio.'),
    (44, 76, NULL),
    (45, 51, 'Notei uma pessoa de jaqueta de couro andando em direção ao beco.'),
    (46, 86, 'Vi uma pessoa de boné azul passando logo após o incidente.'),
    (47, 62, NULL),
    (48, 41, 'Uma pessoa com uma bolsa de lona preta passou correndo por mim logo após o crime.'),
    (49, 13, NULL),
    (50, 57, 'Vi uma pessoa usando um sobretudo escuro entrando no prédio.'),
    (51, 50, NULL),
    (52, 80, 'Havia um carro prateado estacionado perto da cena do crime quando aconteceu.'),
    (53, 98, 'Notei uma pessoa com um cachecol azul andando rapidamente pela rua.'),
    (54, 4, NULL),
    (55, 46, 'Vi uma mulher de vestido vermelho descendo as escadas correndo logo após o incidente.'),
    (56, 93, 'Vi um homem com uma cicatriz no rosto parado perto do prédio.'),
    (57, 70, 'Uma pessoa usando uma jaqueta de couro marrom foi vista perto da cena do crime.'),
    (58, 103, NULL),
    (59, 71, 'Notei um sedã preto estacionado perto da entrada do prédio.'),
    (60, 2, NULL),
    (61, 100, 'Vi um homem usando um chapéu cinza parado por perto quando o crime ocorreu.'),
    (62, 32, 'Uma pessoa com uma mochila vermelha estava perto da cena pouco antes do crime.'),
    (63, 60, NULL),
    (64, 69, 'Vi uma pessoa de casaco preto saindo do prédio com uma bolsa de lona.'),
    (65, 55, NULL),
    (66, 20, 'Notei um homem de jaqueta amarela saindo da cena do crime.'),
    (67, 64, 'Um homem de boné preto foi visto parado perto da cena do crime.'),
    (68, 21, NULL),
    (69, 45, 'Vi uma pessoa de jaqueta cinza correndo da cena do crime.'),
    (70, 82, 'Uma mulher de vestido branco foi vista perto da cena quando o crime ocorreu.'),
    (71, 73, NULL),
    (72, 30, 'Lembro de ver um homem de moletom preto saindo do prédio.'),
    (73, 58, 'Uma pessoa de jaqueta preta estava parada perto da porta pouco antes do crime.'),
    (74, 15, NULL),
    (75, 65, 'O que mais lembro é que ele tinha um relógio de ouro distinto no pulso.'),
    (76, 17, 'Um homem de jaqueta azul saiu correndo com uma bolsa após o crime.'),
    (77, 60, NULL),
    (78, 79, 'Notei uma pessoa de chapéu verde parada em frente ao prédio.'),
    (79, 38, NULL),
    (80, 22, 'Vi uma pessoa com um colar de prata andando rapidamente pela rua.'),
    (81, 68, 'Uma mulher de vestido roxo estava perto da cena durante o incidente.'),
    (82, 26, NULL),
    (83, 7, 'Vi uma pessoa de jaqueta preta e chapéu perto da cena do crime.'),
    (84, 47, 'Lembro de ver uma pessoa de casaco branco saindo rapidamente do prédio.'),
    (85, 23, NULL),
    (86, 3, 'Vi uma pessoa com um cachecol vermelho andando perto da cena do crime.'),
    (87, 36, 'Notei um homem usando um moletom cinza e uma mochila preta perto da cena do crime.'),
    (88, 68, NULL),
    (89, 29, 'Vi uma mulher de vestido amarelo saindo do prédio.'),
    (90, 12, 'Vi um homem com uma tatuagem distinta no pescoço saindo da cena.'),
    (91, 10, NULL),
    (92, 5, 'Notei uma pessoa de jaqueta branca perto da cena do crime pouco antes de acontecer.'),
    (93, 43, 'Um homem de sobretudo preto foi visto perto do beco durante o crime.'),
    (94, 34, NULL),
    (95, 11, 'Vi um homem de boné vermelho parado perto da cena quando o crime ocorreu.'),
    (96, 27, 'Notei uma pessoa de terno escuro perto da cena do crime.'),
    (97, 42, NULL),
    (98, 18, 'Vi uma pessoa de jaqueta preta parada perto do prédio quando o crime aconteceu.'),
    (99, 74, 'Uma pessoa de casaco verde foi vista saindo da área logo após o crime.'),
    (100, 84, NULL)
    ;`,

  // 3. Suspects Table
  `CREATE TABLE suspects (
      id INTEGER PRIMARY KEY,
      name TEXT,
      bandana_color TEXT,
      accessory TEXT
    );`,
  `INSERT INTO suspects (id, name, bandana_color, accessory) VALUES
    (1, 'Carlos Mendoza', 'verde', 'corrente de prata'),
    (2, 'Javier Silva', 'roxa', 'colar de ouro'),
    (3, 'Luis Garcia', 'amarela', 'luvas pretas'),
    (4, 'Miguel Torres', 'azul', 'jaqueta de couro'),
    (5, 'David Morales', 'preta', 'relógio'),
    (6, 'Juan Sanchez', 'vermelha', 'óculos de sol'),
    (7, 'Oscar Lopez', 'rosa', 'anel de ouro'),
    (8, 'Eddie Castillo', 'marrom', 'pulseira'),
    (9, 'Victor Alvarez', 'cinza', 'brinco de prata'),
    (10, 'Raul Garcia', 'branca', 'chaveiro'),
    (11, 'Francisco Ruiz', 'laranja', 'pingente de prata'),
    (12, 'Manuel Herrera', 'azul', 'cinto de couro'),
    (13, 'Ricardo Gonzalez', 'preta', 'relógio de ouro'),
    (14, 'Daniel Perez', 'verde', 'cachecol'),
    (15, 'Antonio Cruz', 'amarela', 'luvas vermelhas'),
    (16, 'Julio Soto', 'roxa', 'colar de contas'),
    (17, 'Santiago Vargas', 'cinza', 'óculos de sol'),
    (18, 'Diego Mendoza', 'vermelha', 'anel'),
    (19, 'Fernando Ruiz', 'verde', 'abotoaduras de ouro'),
    (20, 'Oscar Ramirez', 'marrom', 'pulseira de prata'),
    (21, 'Carlos Torres', 'azul', 'carteira de couro'),
    (22, 'Adrian Gonzalez', 'rosa', 'colar de prata'),
    (23, 'Sebastian Silva', 'laranja', 'boné preto'),
    (24, 'Luis Martinez', 'vermelha', 'brincos de prata'),
    (25, 'Jorge Herrera', 'preta', 'pulseira de corrente'),
    (26, 'Pedro Ruiz', 'amarela', 'relógio de bolso'),
    (27, 'Carlos Castillo', 'roxa', 'anel de ouro'),
    (28, 'Javier Soto', 'cinza', 'jaqueta de couro'),
    (29, 'Manuel Alvarez', 'azul', 'pulseira de contas'),
    (30, 'Antonio Perez', 'verde', 'colar de ouro'),
    (31, 'Julian Sanchez', 'vermelha', 'luvas de couro'),
    (32, 'David Castillo', 'rosa', 'corrente de prata'),
    (33, 'Victor Soto', 'preta', 'pulseira'),
    (34, 'Francisco Gonzalez', 'marrom', 'relógio de ouro'),
    (35, 'Tony Ramirez', 'vermelha', 'relógio de ouro'),
    (36, 'Diego Soto', 'amarela', 'anel de ouro'),
    (37, 'Oscar Alvarez', 'verde', 'colar de corrente'),
    (38, 'Raul Vega', 'roxa', 'carteira preta'),
    (39, 'Javier Morales', 'vermelha', 'bracelete de couro'),
    (40, 'Manuel Soto', 'cinza', 'brincos de prata'),
    (41, 'Fernando Mendoza', 'preta', 'pulseira de ouro'),
    (42, 'Sebastian Lopez', 'amarela', 'relógio'),
    (43, 'Carlos Ramirez', 'azul', 'pingente de prata'),
    (44, 'Mickey Rivera', 'vermelha', 'relógio de ouro'),
    (45, 'Pedro Vega', 'rosa', 'corrente de ouro'),
    (46, 'Luis Lopez', 'vermelha', 'luvas pretas'),
    (47, 'Jorge Soto', 'marrom', 'fivela de cinto de prata'),
    (48, 'David Morales', 'azul', 'colar de couro'),
    (49, 'Carlos Vega', 'roxa', 'brinco de ouro'),
    (50, 'Julian Cruz', 'vermelha', 'pulseira'),
    (51, 'Santiago Vega', 'verde', 'relógio de ouro'),
    (52, 'Ricardo Herrera', 'cinza', 'colar de contas'),
    (53, 'Antonio Cruz', 'azul', 'chapéu preto'),
    (54, 'Diego Vega', 'amarela', 'pulseira de prata'),
    (55, 'Manuel Lopez', 'verde', 'colar de ouro'),
    (56, 'Francisco Vega', 'marrom', 'pingente de prata'),
    (57, 'Carlos Soto', 'vermelha', 'corrente de ouro'),
    (58, 'Oscar Perez', 'roxa', 'relógio'),
    (59, 'Luis Herrera', 'azul', 'colar de prata'),
    (60, 'David Cruz', 'amarela', 'relógio de ouro'),
    (61, 'Raul Cruz', 'preta', 'pulseira de prata'),
    (62, 'Carlos Soto', 'verde', 'colar de corrente'),
    (63, 'Julio Perez', 'rosa', 'abotoaduras de ouro'),
    (64, 'Victor Vega', 'vermelha', 'pulseira de ouro'),
    (65, 'Pedro Soto', 'marrom', 'brincos de prata'),
    (66, 'Javier Herrera', 'amarela', 'corrente de ouro'),
    (67, 'David Soto', 'verde', 'fivela de cinto de prata'),
    (68, 'Ricardo Cruz', 'azul', 'colar de ouro'),
    (69, 'Fernando Vega', 'vermelha', 'pulseira'),
    (70, 'Manuel Vega', 'cinza', 'luvas pretas'),
    (71, 'Oscar Cruz', 'verde', 'brinco de ouro'),
    (72, 'Julian Lopez', 'amarela', 'pulseira de ouro'),
    (73, 'Luis Soto', 'azul', 'colar de corrente'),
    (74, 'Victor Herrera', 'vermelha', 'pulseira'),
    (75, 'Jorge Vega', 'verde', 'anel de ouro'),
    (76, 'Carlos Cruz', 'marrom', 'pingente de prata'),
    (77, 'Santiago Cruz', 'cinza', 'abotoaduras de ouro'),
    (78, 'Manuel Soto', 'amarela', 'colar de prata'),
    (79, 'David Lopez', 'azul', 'pulseira'),
    (80, 'Fernando Vega', 'verde', 'fivela de cinto de prata'),
    (81, 'Ricardo Soto', 'marrom', 'luvas pretas'),
    (82, 'Pedro Cruz', 'vermelha', 'pingente de prata'),
    (83, 'Oscar Soto', 'verde', 'colar de ouro'),
    (84, 'Carlos Vega', 'roxa', 'pulseira de contas'),
    (85, 'Luis Cruz', 'amarela', 'relógio'),
    (86, 'Victor Lopez', 'azul', 'corrente de ouro'),
    (87, 'Julian Vega', 'cinza', 'pulseira de prata'),
    (88, 'David Cruz', 'verde', 'anel de ouro'),
    (89, 'Raul Soto', 'vermelha', 'brinco de prata'),
    (90, 'Manuel Perez', 'azul', 'pingente de ouro'),
    (91, 'Santiago Soto', 'verde', 'pulseira'),
    (92, 'Ricardo Vega', 'amarela', 'brincos de ouro'),
    (93, 'Oscar Cruz', 'azul', 'corrente de prata'),
    (94, 'David Vega', 'vermelha', 'fivela de cinto de ouro'),
    (95, 'Carlos Herrera', 'verde', 'corrente de prata'),
    (96, 'Luis Vega', 'cinza', 'jaqueta preta'),
    (97, 'Rico Delgado', 'vermelha', 'relógio de ouro'),
    (98, 'Victor Soto', 'amarela', 'relógio de prata'),
    (99, 'Fernando Perez', 'azul', 'pulseira'),
    (100, 'Manuel Cruz', 'verde', 'colar de ouro')
    ;`,

  // 4. Interviews Table
  `CREATE TABLE interviews (
      suspect_id INTEGER,
      transcript TEXT,
      FOREIGN KEY (suspect_id) REFERENCES suspects(id)
    );`,
  `INSERT INTO interviews (suspect_id, transcript) VALUES
      (1, NULL),
      (2, 'Eu estava em casa o dia todo, não faço ideia do que aconteceu.'),
      (3, NULL),
      (4, 'Não tenho lembrança desse evento.'),
      (5, 'Eu estava no trabalho, não poderia estar envolvido.'),
      (6, NULL),
      (7, 'Eu estava com amigos em um restaurante.'),
      (8, 'Não sei nada sobre o incidente.'),
      (9, NULL),
      (10, 'Eu nem sabia que algo estava acontecendo.'),
      (11, NULL),
      (12, 'Não vi nada suspeito.'),
      (13, NULL),
      (14, 'Eu estava viajando fora da cidade.'),
      (15, NULL),
      (16, 'Eu estava com a família a noite toda.'),
      (17, 'Eu estava dormindo nessa hora.'),
      (18, NULL),
      (19, 'Não tenho ideia sobre a situação.'),
      (20, NULL),
      (21, 'Não ouvi nada, estava assistindo um filme.'),
      (22, 'Estava preso no trânsito, não vi nada.'),
      (23, NULL),
      (24, 'Não faço ideia sobre esse evento.'),
      (25, NULL),
      (26, 'Eu nem estava na área, desculpe.'),
      (27, 'Não tenho conexão com o incidente.'),
      (28, NULL),
      (29, 'Eu não estava perto do local.'),
      (30, NULL),
      (31, 'Eu não fiz parte de nada disso.'),
      (32, NULL),
      (33, 'Não tive participação em nada.'),
      (34, NULL),
      (35, 'Eu não estava nem perto da West Hollywood Records naquela noite.'),
      (36, 'Estava saindo com amigos, nem ouvi sobre isso.'),
      (37, NULL),
      (38, 'Não tenho certeza do que aconteceu, mas não estava perto.'),
      (39, NULL),
      (40, 'Não tenho ideia sobre a situação.'),
      (41, NULL),
      (42, 'Eu não estava nem perto daquela área.'),
      (43, 'Não sei nada sobre isso, desculpe.'),
      (44, 'Eu estava ocupado com minha carreira musical; não tenho nada a ver com esse furto.'),
      (45, 'Estava ocupado no trabalho, sem tempo para mais nada.'),
      (46, NULL),
      (47, 'Não tive nada a ver com isso, sou inocente.'),
      (48, NULL),
      (49, 'Eu nem sabia que estava acontecendo.'),
      (50, 'Eu estava com um amigo o tempo todo.'),
      (51, NULL),
      (52, 'Eu não estava lá e não sei de nada.'),
      (53, NULL),
      (54, 'Não estou envolvido de forma alguma.'),
      (55, NULL),
      (56, 'Não ouvi nada, estava ocupado.'),
      (57, NULL),
      (58, 'Não vi nada estranho.'),
      (59, NULL),
      (60, 'Não sei nada sobre o que aconteceu.'),
      (61, NULL),
      (62, 'Estava fora da cidade naquele dia, sem ideia.'),
      (63, NULL),
      (64, 'Não vi nada incomum acontecendo.'),
      (65, NULL),
      (66, 'Não estava envolvido, tenho um álibi.'),
      (67, 'Não fiz parte disso, eu juro.'),
      (68, NULL),
      (69, 'Eu nem sabia que havia algo acontecendo.'),
      (70, 'Não tenho nada a ver com isso.'),
      (71, NULL),
      (72, 'Eu estava na loja, nada a ver com isso.'),
      (73, 'Eu não estava na área, tenho provas.'),
      (74, NULL),
      (75, 'Não sei de nada, eu juro.'),
      (76, NULL),
      (77, 'Eu não estava nem perto de lá.'),
      (78, 'Eu estava em casa, cuidando da minha vida.'),
      (79, NULL),
      (80, 'Eu não fiz parte de nada disso.'),
      (81, 'Não ouvi nada naquela noite.'),
      (82, NULL),
      (83, 'Não sei, eu não estava lá.'),
      (84, NULL),
      (85, 'Não fazia ideia do que estava acontecendo.'),
      (86, NULL),
      (87, 'Não vi nada estranho.'),
      (88, NULL),
      (89, 'Não sei nada sobre isso.'),
      (90, 'Eu estava com meus amigos, sem envolvimento.'),
      (91, NULL),
      (92, 'Eu estava em casa, nada aconteceu ao meu redor.'),
      (93, NULL),
      (94, 'Eu nem sei o que aconteceu.'),
      (95, 'Eu estava em outro lugar, não poderia ser eu.'),
      (96, NULL),
      (97, 'Eu não resisti. Perdi a cabeça e peguei o disco.'),
      (98, NULL),
      (99, 'Eu nem sei sobre o crime.'),
      (100, 'Eu não estava perto do local, sem ideia.'),
      (101, NULL),
      (102, 'Eu não estava lá, posso provar.'),
      (103, 'Não tenho nada a dizer sobre isso.'),
      (104, NULL),
      (105, 'Não ouvi nem vi nada.'),
      (106, NULL),
      (107, 'Sou inocente, não fiz nada.'),
      (108, NULL),
      (109, 'Eu não estava na cidade durante o incidente.'),
      (110, NULL),
      (111, 'Não sei quem está por trás disso.'),
      (112, 'Eu não estava nem perto de lá, eu juro.'),
      (113, NULL),
      (114, 'Eu nem sabia sobre o crime.'),
      (115, NULL),
      (116, 'Estava ocupado com o trabalho, não percebi nada.'),
      (117, 'Não vi nada, estava fora da cidade.'),
      (118, NULL),
      (119, 'Não estou envolvido, eu prometo.'),
      (120, 'Não sei nada sobre o furto.'),
      (121, NULL),
      (122, 'Eu não estava lá, não poderia ter feito nada.'),
      (123, 'Não tive parte nisso, eu juro.'),
      (124, NULL),
      (125, 'Eu nem sei de quem você está falando.'),
      (126, 'Não estava envolvido, nem ouvi sobre isso.'),
      (127, NULL),
      (128, 'Eu não estava perto daquele lugar, sem conexão alguma.'),
      (129, 'Não estava envolvido, confie em mim.'),
      (130, NULL),
      (131, 'Eu estava com um amigo a noite toda.'),
      (132, NULL),
      (133, 'Eu não estava na cidade naquela noite, de jeito nenhum.'),
      (134, NULL),
      (135, 'Eu nem sabia sobre o incidente.'),
      (136, NULL),
      (137, 'Eu não estava nem perto da área.'),
      (138, 'Eu estava na academia, não posso ser eu.'),
      (139, NULL),
      (140, 'Não vi nada naquela noite.'),
      (141, 'Não sei de nada, desculpe.'),
      (142, NULL),
      (143, 'Não ouvi nem vi nada, eu estava na cama.'),
      (144, 'Eu não estava lá, sou inocente.'),
      (145, NULL),
      (146, 'Eu não estava nem perto da cena do crime.'),
      (147, NULL),
      (148, 'Eu estava com a família, não vi nada.'),
      (149, NULL),
      (150, 'Não estava envolvido, eu juro pela minha vida.'),
      (151, NULL),
      (152, 'Não sei de nada, eu não estava lá.'),
      (153, 'Não tenho conexão com o incidente.'),
      (154, NULL),
      (155, 'Não fiz parte disso, tenho um álibi.'),
      (156, 'Não sei nada sobre o crime.'),
      (157, NULL),
      (158, 'Não vi nada, estava ocupado no trabalho.'),
      (159, 'Não sei nada sobre o furto.'),
      (160, NULL),
      (161, 'Eu não estava perto da cena do crime, eu juro.'),
      (162, NULL),
      (163, 'Eu nem sei sobre isso, desculpe.'),
      (164, NULL),
      (165, 'Eu não estava lá, eu prometo.'),
      (166, NULL),
      (167, 'Não estava envolvido de forma alguma, eu juro.'),
      (168, 'Não vi nada suspeito.'),
      (169, NULL),
      (170, 'Não sei do que você está falando.'),
      (171, NULL),
      (172, 'Eu nem ouvi sobre o crime.'),
      (173, 'Eu não estava perto da cena.'),
      (174, NULL),
      (175, 'Não tenho envolvimento nisso.'),
      (176, 'Não ouvi nada, eu estava dormindo.'),
      (177, NULL),
      (178, 'Não estava envolvido, eu juro.'),
      (179, 'Eu estava trabalhando naquele dia, não posso ser eu.'),
      (180, NULL),
      (181, 'Eu não estava perto do local, não vi nada.'),
      (182, NULL),
      (183, 'Eu não ia roubar, mas roubei.'),
      (184, 'Não faço ideia do que aconteceu.'),
      (185, NULL),
      (186, 'Eu estava em casa naquele dia, não sabia.'),
      (187, 'Não fiz parte disso, eu juro.'),
      (188, NULL),
      (189, 'Não sei nada sobre isso, eu não estava lá.'),
      (190, 'Não estava envolvido em nada disso.'),
      (191, NULL),
      (192, 'Não vi nada, eu juro.'),
      (193, 'Eu não estava por lá, estava ocupado no trabalho.'),
      (194, NULL),
      (195, 'Eu nem sabia sobre o crime.'),
      (196, NULL),
      (197, 'Não faço ideia de quem fez isso.'),
      (198, NULL),
      (199, 'Não estava envolvido, eu estava no parque.'),
      (200, 'Não vi nada suspeito, desculpe.')
    ;`,
];
