export default [
  // 1. Crime Scenes
  `CREATE TABLE crime_scene (
    id INTEGER PRIMARY KEY,
    date INTEGER,
    location TEXT,
    description TEXT
  );`,
  `INSERT INTO crime_scene (id, date, location, description) VALUES
    (1, 19871030, 'Miami Beach Botanical Garden', 'Plantas raras foram roubadas da estufa de pesquisa. A segurança reportou uma invasão nos sistemas de monitoramento.'),
    (2, 19871031, 'Coral Gables Country Club', 'Uma reunião suspeita foi relatada por vários frequentadores. As imagens de segurança mostraram atividade incomum nas proximidades.'),
    (3, 19871030, 'South Beach Marina', 'Vários barcos foram danificados durante uma tempestade no final da noite. Os investigadores encontraram evidências de adulteração nas amarras.'),
    (4, 19871031, 'Little Havana Theater', 'Uma apresentação noturna foi interrompida por uma queda de energia. A inspeção técnica revelou sinais de sabotagem deliberada.'),
    (5, 19871030, 'Brickell Financial Center', 'Documentos foram encontrados destruídos nos escritórios executivos. As câmeras de segurança registraram acesso não autorizado após o expediente.'),
    (6, 19871031, 'Vizcaya Museum Gardens', 'Artefatos históricos foram reportados como desaparecidos das vitrines. Os sistemas de alarme foram desativados profissionalmente. O curador foi encontrado morto na sala dos fundos. O segurança foi encontrado morto no estacionamento.'),
    (7, 19871030, 'Coconut Grove Yacht Club', 'Uma embarcação de luxo foi encontrada à deriva na marina. O proprietário relatou sinais de arrombamento e furto.'),
    (8, 19871031, 'Design District Gallery', 'Obras de arte valiosas foram encontradas danificadas durante a exposição. As imagens de vigilância mostraram movimentação suspeita após o fechamento.'),
    (9, 19871030, 'Wynwood Arts Complex', 'Vários estúdios relataram vandalismo durante a madrugada. As evidências sugeriram atividade criminosa coordenada.'),
    (10, 19871031, 'Miami Beach Convention Center', 'Um leilão de alto perfil foi interrompido por ameaças à segurança. A investigação revelou envolvimento interno. O leiloeiro foi encontrado morto na sala dos fundos.'),
    (11, 19871030, 'Fisher Island Club', 'Membros relataram perturbações incomuns durante o serviço de jantar. Funcionários testemunharam indivíduos suspeitos nas dependências.'),
    (12, 19871031, 'Bayside Marketplace', 'Várias lojas relataram arrombamentos após a meia-noite. Os sistemas de segurança foram desativados profissionalmente.'),
    (13, 19871030, 'Port of Miami Terminal', 'Contêineres de carga apresentaram sinais de adulteração durante a madrugada. Trabalhadores do porto relataram movimentação de veículos não autorizados.'),
    (14, 19871031, 'Venetian Pool', 'As instalações históricas foram vandalizadas após o horário de funcionamento. As evidências sugeriram o envolvimento de múltiplos autores.'),
    (15, 19871030, 'Calle Ocho Plaza', 'Os preparativos para o festival de rua foram sabotados durante a madrugada. Os organizadores encontraram equipamentos deliberadamente danificados.'),
    (16, 19871031, 'Fairchild Tropical Garden', 'Espécimes raras foram roubadas de estufas com segurança reforçada. A segurança reportou invasão nos sistemas de perímetro.'),
    (17, 19871030, 'Miami River District', 'Invasões a armazéns foram relatadas por várias empresas. A investigação mostrou atividade criminosa coordenada.'),
    (18, 19871031, 'Miracle Mile Shopping Center', 'Uma joalheria relatou uma tentativa sofisticada de arrombamento. Os sistemas de alarme foram contornados profissionalmente. O proprietário da loja foi encontrado morto na sala dos fundos.'),
    (19, 19871030, 'Miami Seaquarium', 'As instalações de pesquisa apresentaram sinais de acesso não autorizado. Amostras de biologia marinha foram reportadas como desaparecidas.'),
    (20, 19871031, 'Freedom Tower', 'Documentos históricos foram encontrados perturbados na sala de arquivos. As câmeras de segurança capturaram intrusos não identificados.'),
    (21, 19871030, 'Matheson Hammock Marina', 'Várias embarcações relataram furto de equipamentos durante a madrugada. A patrulha do porto encontrou evidências de crime organizado.'),
    (22, 19871031, 'Deering Estate', 'Artefatos históricos foram retirados do armazenamento seguro. Funcionários relataram atividade incomum durante o período noturno.'),
    (23, 19871030, 'Olympia Theater', 'Objetos de cena valiosos foram roubados durante a madrugada. Os equipamentos de palco apresentaram sinais de adulteração.'),
    (24, 19871031, 'Jungle Island', 'Recintos de animais foram encontrados destrancados após o horário de funcionamento. Funcionários relataram equipamentos de manutenção desaparecidos.'),
    (25, 19871030, 'Miami City Cemetery', 'Monumentos históricos foram vandalizados durante a madrugada. Os zeladores relataram reuniões suspeitas.'),
    (26, 19871031, 'Marlins Park Area', 'O canteiro de obras relatou materiais e equipamentos desaparecidos. As imagens de segurança mostraram veículos não autorizados.'),
    (27, 19871030, 'Miami Science Museum', 'Exposições valiosas foram adulteradas após o fechamento. Funcionários descobriram materiais de pesquisa desaparecidos.'),
    (28, 19871031, 'Bayfront Park', 'Obras de arte públicas foram danificadas durante o período noturno. A segurança do parque relatou atividade suspeita em grupo.'),
    (29, 19871030, 'Miami Childrens Museum', 'Exibições educativas foram vandalizadas durante a madrugada. Os sistemas de segurança apresentaram sinais de interferência.'),
    (30, 19871031, 'Pérez Art Museum', 'Obras de arte contemporânea foram encontradas danificadas no depósito. Funcionários relataram acesso não autorizado a áreas restritas.'),
    (31, 19871030, 'Adrienne Arsht Center', 'Equipamentos de espetáculo foram sabotados antes do início da apresentação. A equipe técnica encontrou evidências de adulteração deliberada.'),
    (32, 19871031, 'Lummus Park', 'Estruturas históricas apresentaram sinais de vandalismo. Os guardas do parque relataram atividade suspeita noturna.'),
    (33, 19871030, 'Miami Beach Botanical Garden', 'Plantas raras foram roubadas da estufa de pesquisa. A segurança reportou invasão nos sistemas de monitoramento.'),
    (34, 19871031, 'Pinecrest Gardens', 'Instalações de arte foram danificadas durante a madrugada. A vigilância mostrou acesso não autorizado.'),
    (35, 19871030, 'Crandon Park', 'As instalações da praia relataram vandalismo extenso. Funcionários descobriram evidências de atividade criminosa noturna.'),
    (36, 19871031, 'Greynolds Park', 'Estruturas históricas foram danificadas após o horário de funcionamento. A segurança do parque encontrou sinais de arrombamento.'),
    (37, 19871030, 'Tropical Park', 'Instalações esportivas relataram furto de equipamentos durante a madrugada. As câmeras de segurança mostraram atividade suspeita.'),
    (38, 19871031, 'Simpson Park', 'Espécimes raras de plantas foram roubadas do conservatório. Funcionários encontraram evidências de furto profissional.'),
    (39, 19871030, 'Virginia Key Beach', 'Equipamentos de pesquisa marinha foram roubados durante a madrugada. A segurança reportou atividade não autorizada de embarcações.'),
    (40, 19871031, 'Morningside Park', 'As quadras de tênis relataram vandalismo e furto. As imagens de segurança mostraram atividade criminosa coordenada.'),
    (41, 19871030, 'Legion Park', 'O centro comunitário relatou um arrombamento durante a madrugada. Funcionários encontraram evidências de assalto profissional.'),
    (42, 19871031, 'Kennedy Park', 'As instalações à beira-mar apresentaram sinais de vandalismo. A patrulha do parque relatou reuniões suspeitas.'),
    (43, 19871030, 'Alice Wainwright Park', 'Estruturas do parque foram danificadas durante a madrugada. A segurança encontrou evidências de atividade organizada.'),
    (44, 19871031, 'Margaret Pace Park', 'Equipamentos recreativos foram roubados após o horário de funcionamento. Funcionários relataram movimentação suspeita de veículos.'),
    (45, 19871030, 'Peacock Park', 'Instalações esportivas foram vandalizadas durante a madrugada. As câmeras de segurança mostraram acesso não autorizado.'),
    (46, 19871031, 'South Pointe Park', 'Equipamentos da patrulha de praia foram roubados após o horário de funcionamento. Funcionários relataram atividade suspeita em grupo.'),
    (47, 19871030, 'Biscayne National Park', 'Estações de pesquisa marinha relataram arrombamentos. A segurança encontrou evidências de furto profissional.'),
    (48, 19870520, 'Fontainebleau Hotel', 'O colar Coração de Atlântida desapareceu. Muitos hóspedes foram interrogados, mas apenas dois forneceram pistas valiosas. Um deles é um ator muito famoso. A outra é uma mulher que trabalha como consultora em uma grande empresa e cujo primeiro nome termina com "an".'),
    (49, 19871030, 'Bill Baggs Cape Park', 'O farol histórico apresentou sinais de vandalismo. Os guardas do parque relataram atividade suspeita.'),
    (50, 19871031, 'Haulover Park', 'As instalações da marina relataram furto de equipamentos durante a madrugada. As imagens de segurança mostraram atividade coordenada.'),
    (51, 19871030, 'North Shore Park', 'As instalações da praia apresentaram sinais de vandalismo. Funcionários encontraram evidências de atividade criminosa.'),
    (52, 19871031, 'Surfside Community Center', 'Equipamentos recreativos foram roubados após o horário de funcionamento. A segurança reportou acesso não autorizado.'),
    (53, 19871030, 'Golden Beach Pavilion', 'A patrulha de praia relatou vandalismo durante a madrugada. Funcionários descobriram evidências de crime organizado.'),
    (54, 19871031, 'Sunny Isles Pier', 'Equipamentos de pesca foram roubados durante a madrugada. As câmeras de segurança mostraram atividade suspeita.'),
    (55, 19871030, 'Bal Harbour Beach Club', 'Instalações privadas relataram um arrombamento sofisticado. Funcionários encontraram evidências de furto profissional.'),
    (56, 19871031, 'Indian Creek Country Club', 'Equipamentos de golfe foram roubados durante a madrugada. A segurança reportou acesso não autorizado de veículos.'),
    (57, 19871030, 'Miami Shores Country Club', 'As instalações do clube apresentaram sinais de vandalismo. Funcionários descobriram evidências de atividade coordenada.'),
    (58, 19871031, 'Normandy Shores Golf Club', 'A loja do clube relatou uma tentativa sofisticada de assalto. Os sistemas de segurança foram desativados profissionalmente.'),
    (59, 19871030, 'La Gorce Country Club', 'As quadras de tênis relataram furto de equipamentos. Funcionários encontraram evidências de crime organizado.'),
    (60, 19871031, 'Riviera Country Club', 'A garagem de carrinhos de golfe relatou furto extenso. As imagens de segurança mostraram atividade suspeita.'),
    (61, 19871030, 'Granada Golf Course', 'Equipamentos de manutenção foram roubados durante a madrugada. Funcionários relataram acesso não autorizado.'),
    (62, 19871031, 'Biltmore Golf Course', 'A loja do clube apresentou sinais de arrombamento sofisticado. A segurança encontrou evidências de furto profissional.'),
    (63, 19871030, 'Miami Beach Golf Club', 'A sede do clube relatou vandalismo após o horário de funcionamento. Funcionários descobriram sinais de arrombamento.'),
    (64, 19871031, 'Melreese Country Club', 'Equipamentos de golfe foram roubados durante a madrugada. A segurança reportou movimentação suspeita de veículos.'),
    (65, 19871030, 'International Links Miami', 'A instalação de manutenção relatou furto extenso. Funcionários encontraram evidências de atividade coordenada.'),
    (66, 19871031, 'Briar Bay Golf Course', 'A loja do clube apresentou sinais de tentativa de assalto. As câmeras de segurança capturaram atividade suspeita.'),
    (67, 19871030, 'Palmetto Golf Course', 'As instalações do clube relataram vandalismo durante a madrugada. Funcionários descobriram evidências de furto profissional. O proprietário do clube foi encontrado morto na sala dos fundos. O segurança foi encontrado morto no estacionamento.'),
    (68, 19871031, 'Country Club of Miami', 'As quadras de tênis apresentaram sinais de arrombamento. A segurança encontrou evidências de acesso não autorizado.'),
    (69, 19871030, 'California Club', 'A garagem de carrinhos de golfe relatou furto sofisticado. Funcionários relataram atividade suspeita em grupo.'),
    (70, 19871031, 'Shulas Golf Club', 'Equipamentos da loja do clube foram roubados após o horário de funcionamento. As imagens de segurança mostraram atividade coordenada.'),
    (71, 19871030, 'Miami National Golf Club', 'Equipamentos de manutenção apresentaram sinais de furto. Funcionários encontraram evidências de assalto profissional.'),
    (72, 19871031, 'Killian Greens Golf Club', 'A sede do clube relatou vandalismo durante a madrugada. A segurança descobriu acesso não autorizado.'),
    (73, 19871030, 'Costa Del Sol Golf Club', 'Equipamentos de golfe foram roubados durante a madrugada. Funcionários relataram movimentação suspeita de veículos.'),
    (74, 19871031, 'Keys Gate Golf Club', 'A loja do clube apresentou sinais de arrombamento sofisticado. A segurança encontrou evidências de crime organizado.'),
    (75, 19871031, 'Miami Mansion, Coconut Grove', 'Durante um baile de máscaras, um corpo foi encontrado no jardim. Testemunhas mencionaram uma reserva de hotel e atividade telefônica suspeita.'),
    (76, 19871031, 'Coral Pine Golf Course', 'As instalações do clube apresentaram sinais de vandalismo. A segurança reportou atividade suspeita.'),
    (77, 19871030, 'Miami Springs Golf Club', 'A garagem de carrinhos de golfe relatou furto sofisticado. Funcionários encontraram evidências de assalto profissional.'),
    (78, 19871031, 'Normandy Shores Club', 'Equipamentos de tênis foram roubados durante a madrugada. As câmeras de segurança mostraram atividade suspeita.'),
    (79, 19871030, 'Fisher Island Club Course', 'A loja do clube relatou tentativa de arrombamento. Funcionários descobriram evidências de atividade coordenada.'),
    (80, 19871031, 'Deering Bay Yacht Club', 'As instalações do clube apresentaram sinais de vandalismo. A segurança encontrou evidências de acesso não autorizado.'),
    (81, 19871030, 'Williams Island Club', 'As quadras de tênis relataram furto de equipamentos. Funcionários relataram atividade suspeita em grupo.'),
    (82, 19871031, 'Turnberry Isle Resort', 'Equipamentos de golfe foram roubados após o horário de funcionamento. As imagens de segurança mostraram atividade coordenada.'),
    (83, 19871030, 'Doral Golf Resort', 'A instalação de manutenção relatou furto extenso. Funcionários encontraram evidências de furto profissional. O proprietário da instalação foi encontrado morto na sala dos fundos. O segurança foi encontrado morto no estacionamento.'),
    (84, 19871031, 'Trump National Doral', 'A loja do clube apresentou sinais de arrombamento sofisticado. A segurança descobriu acesso não autorizado.'),
    (85, 19871030, 'Blue Monster Course', 'A sede do clube relatou vandalismo durante a madrugada. Funcionários relataram movimentação suspeita de veículos.'),
    (86, 19871031, 'Silver Fox Course', 'A garagem de carrinhos de golfe apresentou sinais de furto. A segurança encontrou evidências de crime organizado.'),
    (87, 19871030, 'Golden Palm Course', 'Equipamentos de tênis foram roubados durante a madrugada. Funcionários descobriram sinais de arrombamento.'),
    (88, 19871031, 'Red Tiger Course', 'A instalação de manutenção relatou furto sofisticado. A segurança reportou atividade suspeita.'),
    (89, 19871030, 'Great White Course', 'A loja do clube apresentou sinais de tentativa de assalto. Funcionários encontraram evidências de furto profissional.'),
    (90, 19871031, 'Jim McLean Golf School', 'Equipamentos de treinamento foram roubados durante a madrugada. As câmeras de segurança mostraram atividade suspeita.'),
    (91, 19871030, 'Miami Beach Golf Academy', 'A instalação de prática relatou furto extenso. Funcionários descobriram evidências de atividade coordenada. O proprietário da academia foi encontrado morto na sala dos fundos. O segurança foi encontrado morto no estacionamento.'),
    (92, 19871031, 'Don Shula Golf Academy', 'Equipamentos de treinamento apresentaram sinais de vandalismo. A segurança encontrou evidências de acesso não autorizado.'),
    (93, 19871030, 'David Leadbetter Academy', 'Equipamentos de golfe foram roubados após o horário de funcionamento. Funcionários relataram atividade suspeita em grupo.'),
    (94, 19871031, 'Rick Smith Golf Performance', 'A instalação de prática relatou furto sofisticado. As imagens de segurança mostraram atividade coordenada.'),
    (95, 19871030, 'Claude Harmon Golf School', 'Equipamentos de treinamento apresentaram sinais de arrombamento. Funcionários encontraram evidências de assalto profissional.'),
    (96, 19871031, 'Mitchell Spearman Academy', 'A instalação de prática relatou vandalismo durante a madrugada. A segurança descobriu acesso não autorizado.'),
    (97, 19871030, 'Dave Pelz Golf School', 'Equipamentos de treinamento foram roubados durante a madrugada. Funcionários relataram movimentação suspeita de veículos.'),
    (98, 19871031, 'Golf Institute Miami', 'A instalação de prática apresentou sinais de furto sofisticado. A segurança encontrou evidências de crime organizado.'),
    (99, 19871030, 'Miami Golf Learning Center', 'Os equipamentos de treinamento relataram vandalismo extenso. Funcionários descobriram sinais de arrombamento.'),
    (100, 19871031, 'South Florida Golf Academy', 'A instalação de prática apresentou sinais de tentativa de assalto. A segurança reportou atividade suspeita.')
  ;`,

  // 2. Guests
  `CREATE TABLE guest (
    id INTEGER PRIMARY KEY,
    name TEXT,
    occupation TEXT,
    invitation_code TEXT
  );`,
  `INSERT INTO guest (id, name, occupation, invitation_code) VALUES
    (1, 'Hristo Bogoev', 'Engineer', 'VIP-R'),
    (2, 'John Doe', 'Software Developer', 'VIP-R'),
    (3, 'James Bond', 'Spy', 'VIP-R'),
    (4, 'Marcus Chen', 'Software Developer', 'VIP-R'),
    (5, 'Isabella Rodriguez', 'Architect', 'VIP-B'),
    (6, 'James Wilson', 'Doctor', 'VIP-G'),
    (7, 'Sofia Patel', 'Investment Banker', 'VIP-R'),
    (8, 'Lucas Kim', 'Professor', 'VIP-B'),
    (9, 'Emma Thompson', 'Lawyer', 'VIP-G'),
    (10, 'Alexander Wang', 'CEO', 'VIP-R'),
    (11, 'Olivia Brown', 'Artist', 'VIP-B'),
    (12, 'William Davis', 'Entrepreneur', 'VIP-G'),
    (13, 'Ava Martinez', 'Surgeon', 'VIP-R'),
    (14, 'Ethan Taylor', 'Financial Analyst', 'VIP-B'),
    (15, 'Sophia Lee', 'Marketing Director', 'VIP-G'),
    (16, 'Benjamin Garcia', 'Real Estate Developer', 'VIP-R'),
    (17, 'Mia Anderson', 'Fashion Designer', 'VIP-B'),
    (18, 'Daniel Murphy', 'Executive Chef', 'VIP-G'),
    (19, 'Charlotte Wong', 'Venture Capitalist', 'VIP-R'),
    (20, 'Henry Johnson', 'Film Producer', 'VIP-B'),
    (21, 'Amelia Clark', 'Biotech Researcher', 'VIP-G'),
    (22, 'Sebastian Lewis', 'Music Producer', 'VIP-R'),
    (23, 'Victoria White', 'Gallery Owner', 'VIP-B'),
    (24, 'Jack Robinson', 'Sports Agent', 'VIP-G'),
    (25, 'Zoe Campbell', 'Interior Designer', 'VIP-R'),
    (26, 'Oliver Scott', 'Hotel Manager', 'VIP-B'),
    (27, 'Luna Phillips', 'Tech Entrepreneur', 'VIP-G'),
    (28, 'Theodore Green', 'Restaurant Owner', 'VIP-R'),
    (29, 'Grace Turner', 'Publishing Executive', 'VIP-B'),
    (30, 'Leo Mitchell', 'Hedge Fund Manager', 'VIP-G'),
    (31, 'Aria Foster', 'Jewelry Designer', 'VIP-R'),
    (32, 'Owen Ross', 'Film Director', 'VIP-B'),
    (33, 'Scarlett Hayes', 'Art Curator', 'VIP-G'),
    (34, 'Felix Morgan', 'Aerospace Engineer', 'VIP-R'),
    (35, 'Chloe Bennett', 'Fashion Editor', 'VIP-B'),
    (36, 'Max Cooper', 'Consultant', 'VIP-G'),
    (37, 'Lily Stewart', 'PR Executive', 'VIP-R'),
    (38, 'Hugo Price', 'Wine Importer', 'VIP-B'),
    (39, 'Audrey Gray', 'Theater Director', 'VIP-G'),
    (40, 'Julian Wood', 'Sports Team Owner', 'VIP-R'),
    (41, 'Hazel Reed', 'Philanthropist', 'VIP-B'),
    (42, 'Oscar Kelly', 'University Dean', 'VIP-G'),
    (43, 'Ruby Baker', 'Actor', 'VIP-R'),
    (44, 'Arthur Collins', 'Investment Manager', 'VIP-B'),
    (45, 'Violet Ward', 'Museum Director', 'VIP-G'),
    (46, 'Miles Richardson', 'Record Producer', 'VIP-R'),
    (47, 'Penelope Hughes', 'Magazine Editor', 'VIP-B'),
    (48, 'Caleb Morris', 'Real Estate Investor', 'VIP-G'),
    (49, 'Stella James', 'Art Dealer', 'VIP-R'),
    (50, 'Finn Russell', 'Startup Founder', 'VIP-B'),
    (51, 'Eleanor Brooks', 'Corporate Lawyer', 'VIP-G'),
    (52, 'Atlas Powell', 'Hotel Developer', 'VIP-R'),
    (53, 'Ivy Peterson', 'Fashion Consultant', 'VIP-B'),
    (54, 'Liam Henderson', 'Restaurant Critic', 'VIP-G'),
    (55, 'Nova Watson', 'Tech Investor', 'VIP-R'),
    (56, 'Jasper Cox', 'Theater Producer', 'VIP-B'),
    (57, 'Clara Howard', 'Gallery Director', 'VIP-G'),
    (58, 'Silas Butler', 'Luxury Car Dealer', 'VIP-R'),
    (59, 'Aurora Long', 'Event Planner', 'VIP-B'),
    (60, 'Roman Fisher', 'Nightclub Owner', 'VIP-G'),
    (61, 'Delilah Marshall', 'Fashion Photographer', 'VIP-R'),
    (62, 'Kai Barnes', 'Sports Manager', 'VIP-B'),
    (63, 'Iris Fleming', 'Interior Architect', 'VIP-G'),
    (64, 'Apollo Grant', 'Film Investor', 'VIP-R'),
    (65, 'Eden Shaw', 'Jewelry Collector', 'VIP-B'),
    (66, 'River Harrison', 'Music Executive', 'VIP-G'),
    (67, 'Thea Gibson', 'Art Collector', 'VIP-R'),
    (68, 'Atlas Wallace', 'Property Developer', 'VIP-B'),
    (69, 'Sage Johnston', 'Fashion Designer', 'VIP-G'),
    (70, 'Phoenix Ellis', 'Tech CEO', 'VIP-R'),
    (71, 'Willow Stevens', 'Publishing Director', 'VIP-B'),
    (72, 'Orion Chapman', 'Investment Banker', 'VIP-G'),
    (73, 'Luna West', 'Art Gallery Owner', 'VIP-R'),
    (74, 'Atlas Hunt', 'Venture Capitalist', 'VIP-B'),
    (75, 'Aurora Palmer', 'Fashion Editor', 'VIP-G'),
    (76, 'Kai Spencer', 'Real Estate Mogul', 'VIP-R'),
    (77, 'Nova Ferguson', 'Theater Owner', 'VIP-B'),
    (78, 'Phoenix Mason', 'Tech Entrepreneur', 'VIP-G'),
    (79, 'Eden Tucker', 'Film Producer', 'VIP-R'),
    (80, 'River Wells', 'Hotel Chain Owner', 'VIP-B'),
    (81, 'Sage Crawford', 'Art Director', 'VIP-G'),
    (82, 'Atlas Bradley', 'Investment Manager', 'VIP-R'),
    (83, 'Luna Griffin', 'Fashion House Owner', 'VIP-B'),
    (84, 'Phoenix McDonald', 'Tech Investor', 'VIP-G'),
    (85, 'Eden Carroll', 'Gallery Curator', 'VIP-R'),
    (86, 'River Hopkins', 'Restaurant Owner', 'VIP-B'),
    (87, 'Sage Hawkins', 'Jewelry Designer', 'VIP-G'),
    (88, 'Atlas Perkins', 'Property Investor', 'VIP-R'),
    (89, 'Luna Matthews', 'Fashion Consultant', 'VIP-B'),
    (90, 'Phoenix Morrison', 'Tech Executive', 'VIP-G'),
    (91, 'Eden Robertson', 'Art Collector', 'VIP-R'),
    (92, 'River Kennedy', 'Hotel Developer', 'VIP-B'),
    (93, 'Sage Lawrence', 'Theater Producer', 'VIP-G'),
    (94, 'Atlas Dixon', 'Investment Banker', 'VIP-R'),
    (95, 'Luna Ramos', 'Gallery Owner', 'VIP-B'),
    (96, 'Phoenix Boyd', 'Tech Founder', 'VIP-G'),
    (97, 'Eden Cole', 'Fashion Designer', 'VIP-R'),
    (98, 'River Fox', 'Real Estate Developer', 'VIP-B'),
    (99, 'Sage Warren', 'Art Dealer', 'VIP-G'),
    (100, 'Atlas Holmes', 'Venture Capitalist', 'VIP-R'),
    (101, 'Luna Reeves', 'Fashion Buyer', 'VIP-B'),
    (102, 'Phoenix Lloyd', 'Tech Director', 'VIP-G'),
    (103, 'Eden Walsh', 'Art Curator', 'VIP-R'),
    (104, 'River Santos', 'Hotel Manager', 'VIP-B'),
    (105, 'Mike Manning', 'Wealth Reallocation Expert', 'VIP-R'),
    (106, 'Atlas Ortiz', 'Investment Advisor', 'VIP-R'),
    (107, 'Luna Delgado', 'Gallery Manager', 'VIP-B'),
    (108, 'Phoenix Barton', 'Consultant', 'VIP-G'),
    (109, 'Eden Cruz', 'Fashion Buyer', 'VIP-R'),
    (110, 'River Mendoza', 'Real Estate Agent', 'VIP-B'),
    (111, 'Sage Zimmerman', 'Art Dealer', 'VIP-G'),
    (112, 'Atlas Owens', 'Venture Partner', 'VIP-G'),
    (113, 'Luna Watts', 'Fashion Editor', 'VIP-B'),
    (114, 'Phoenix Klein', 'Tech Advisor', 'VIP-G'),
    (115, 'Eden Burgess', 'Gallery Director', 'VIP-R'),
    (116, 'Vivian Nair', 'Consultant', 'VIP-R'),
    (117, 'Sage Daniels', 'Theater Manager', 'VIP-G'),
    (118, 'Atlas Guerrero', 'Investment Director', 'VIP-R'),
    (119, 'Luna Chandler', 'Fashion Consultant', 'VIP-B'),
    (120, 'Phoenix Barker', 'Tech Manager', 'VIP-G'),
    (121, 'Eden Norris', 'Art Collector', 'VIP-R'),
    (122, 'River Quinn', 'Property Manager', 'VIP-B'),
    (123, 'Sage Vaughn', 'Theater Producer', 'VIP-G'),
    (124, 'Atlas Poole', 'Investment Banker', 'VIP-R'),
    (125, 'Luna Wolfe', 'Gallery Owner', 'VIP-B'),
    (126, 'Phoenix Shields', 'Tech Executive', 'VIP-G'),
    (127, 'Eden Pearson', 'Fashion Designer', 'VIP-R'),
    (128, 'River Dawson', 'Real Estate Broker', 'VIP-B'),
    (129, 'Clint Eastwood', 'Actor', 'VIP-G'),
    (130, 'Atlas Malone', 'Venture Capitalist', 'VIP-R'),
    (131, 'Luna Rojas', 'Fashion Buyer', 'VIP-B'),
    (132, 'Phoenix Gibbs', 'Tech Director', 'VIP-G'),
    (133, 'Eden Ballard', 'Gallery Manager', 'VIP-R'),
    (134, 'River Vega', 'Hotel Developer', 'VIP-B'),
    (135, 'Sage Russo', 'Consultant', 'VIP-G'),
    (136, 'Atlas Wise', 'Investment Advisor', 'VIP-R'),
    (137, 'Luna Kirby', 'Fashion Editor', 'VIP-B'),
    (138, 'Phoenix Sandoval', 'Consultant', 'VIP-G'),
    (139, 'Eden Huff', 'Art Dealer', 'VIP-R'),
    (140, 'River Frost', 'Property Developer', 'VIP-B'),
    (141, 'Sage Morse', 'Theater Producer', 'VIP-G'),
    (142, 'Atlas Whitehead', 'Investment Director', 'VIP-R'),
    (143, 'Luna Bullock', 'Gallery Owner', 'VIP-B'),
    (144, 'Phoenix Rich', 'Tech Manager', 'VIP-G'),
    (145, 'Eden Todd', 'Fashion Consultant', 'VIP-G'),
    (146, 'River Glass', 'Hotel Executive', 'VIP-B'),
    (147, 'Sage Hendricks', 'Art Curator', 'VIP-G'),
    (148, 'Atlas Cummings', 'Venture Partner', 'VIP-R'),
    (149, 'Luna Hutchinson', 'Fashion Designer', 'VIP-B'),
    (150, 'Phoenix Golden', 'Tech Executive', 'VIP-G'),
    (151, 'Eden Skinner', 'Gallery Director', 'VIP-R'),
    (152, 'River Wilkinson', 'Real Estate Agent', 'VIP-B'),
    (153, 'Sage Pruitt', 'Theater Manager', 'VIP-G'),
    (154, 'Atlas Hogan', 'Investment Banker', 'VIP-R'),
    (155, 'Luna Conley', 'Consultant', 'VIP-B'),
    (156, 'Phoenix Velazquez', 'Tech Director', 'VIP-G'),
    (157, 'Eden Combs', 'Art Collector', 'VIP-R'),
    (158, 'River Hood', 'Hotel Manager', 'VIP-B'),
    (159, 'Sage Kaufman', 'Theater Producer', 'VIP-G'),
    (160, 'Atlas Dudley', 'Investment Advisor', 'VIP-R'),
    (161, 'Luna Horne', 'Gallery Manager', 'VIP-B'),
    (162, 'Phoenix Farley', 'Consultant', 'VIP-G'),
    (163, 'Eden Lowery', 'Fashion Editor', 'VIP-R'),
    (164, 'River Bowers', 'Actor', 'VIP-B'),
    (165, 'Sage Phelps', 'Art Dealer', 'VIP-G'),
    (166, 'Atlas Crane', 'Venture Capitalist', 'VIP-R'),
    (167, 'Luna Dalton', 'Fashion Designer', 'VIP-B'),
    (168, 'Phoenix Browning', 'Tech Executive', 'VIP-G'),
    (169, 'Eden Shepherd', 'Gallery Owner', 'VIP-R'),
    (170, 'River Griffith', 'Hotel Developer', 'VIP-B'),
    (171, 'Sage Merritt', 'Theater Director', 'VIP-G'),
    (172, 'Atlas Chaney', 'Investment Director', 'VIP-R'),
    (173, 'Luna Odom', 'Fashion Consultant', 'VIP-B'),
    (174, 'Phoenix Hendrix', 'Tech Manager', 'VIP-G'),
    (175, 'Eden Stark', 'Art Curator', 'VIP-R'),
    (176, 'River Meyers', 'Real Estate Broker', 'VIP-B'),
    (177, 'Sage Sloan', 'Theater Producer', 'VIP-G'),
    (178, 'Atlas Hinton', 'Investment Banker', 'VIP-R'),
    (179, 'Luna Terrell', 'Fashion Buyer', 'VIP-B'),
    (180, 'Phoenix Riggs', 'Tech Director', 'VIP-G'),
    (181, 'Eden Hess', 'Gallery Manager', 'VIP-R'),
    (182, 'River Weeks', 'Hotel Executive', 'VIP-B'),
    (183, 'Sage Wilcox', 'Art Dealer', 'VIP-G'),
    (184, 'Atlas Melton', 'Venture Partner', 'VIP-R'),
    (185, 'Luna Gilmore', 'Fashion Editor', 'VIP-B'),
    (186, 'Phoenix Kinney', 'Consultant', 'VIP-G'),
    (187, 'Eden Whitaker', 'Gallery Director', 'VIP-R'),
    (188, 'River Madden', 'Property Manager', 'VIP-B'),
    (189, 'Sage Dillon', 'Actor', 'VIP-G'),
    (190, 'Atlas Roach', 'Investment Advisor', 'VIP-B'),
    (191, 'Luna Blanchard', 'Fashion Designer', 'VIP-B'),
    (192, 'Phoenix Pitts', 'Actor', 'VIP-G'),
    (193, 'Eden McCall', 'Art Collector', 'VIP-R'),
    (194, 'River Marsh', 'Hotel Developer', 'VIP-B'),
    (195, 'Sage Lindsey', 'Theater Producer', 'VIP-G'),
    (196, 'Atlas Thorton', 'Investment Director', 'VIP-R'),
    (197, 'Luna Graves', 'Fashion Consultant', 'VIP-B'),
    (198, 'Phoenix Savage', 'Tech Manager', 'VIP-G'),
    (199, 'Eden Meadows', 'Gallery Owner', 'VIP-R'),
    (200, 'River Frost', 'Real Estate Agent', 'VIP-B')
  ;`,

  // 3. Witness Statements
  `CREATE TABLE witness_statements (
    id INTEGER PRIMARY KEY,
    guest_id INTEGER,
    clue TEXT,
    FOREIGN KEY (guest_id) REFERENCES guest(id)
  );`,
  `INSERT INTO witness_statements (id, guest_id, clue) VALUES
    (1, 123, 'Eu estava passeando com meu cachorro quando vi alguém suspeito escalando pela janela da estufa de pesquisa tarde da noite.'),
    (2, 45, 'Durante o turno da madrugada, ouvi claramente o som de vidro quebrando vindo da ala leste do edifício.'),
    (3, 167, 'Durante meu cooper noturno, notei uma van preta estacionada do lado de fora com os faróis apagados por mais de duas horas.'),
    (4, 23, 'Lembro de sentir cheiro de queimado por volta da meia-noite, o que pareceu muito estranho para aquela hora.'),
    (5, 91, 'Quando estava fechando a loja, vi três pessoas com roupas escuras correndo pela saída dos fundos.'),
    (6, 34, 'Da janela do meu apartamento, observei alguém mexendo nas câmeras de segurança com algum tipo de ferramenta.'),
    (7, 67, 'Durante minha ronda de segurança, ouvi barulhos altos vindo da área de armazenamento por volta das 2h da manhã.'),
    (8, 89, 'Avistei uma pessoa usando uniforme de manutenção em um horário incomum, quando não havia nenhuma manutenção agendada.'),
    (9, 12, 'Voltando para casa a pé, vi alguém jogando o que pareciam ser documentos numa lixeira atrás do edifício.'),
    (10, 56, 'Ouvi um alarme disparar brevemente antes de ser silenciado de forma incomum.'),
    (11, 78, 'Da minha varanda, observei alguém arrombando a entrada lateral usando ferramentas profissionais.'),
    (12, 34, 'Durante meu turno noturno, percebi que as câmeras de segurança estavam exibindo imagens em loop de corredores vazios.'),
    (13, 90, 'Vi um grupo de pessoas carregando grandes caixotes em um caminhão branco por volta da meia-noite.'),
    (14, 23, 'Enquanto fechava o café do outro lado da rua, testemunhei alguém desligando as luzes externas sistematicamente.'),
    (15, 45, 'Ouvi o que parecia ser ferramentas elétricas sendo usadas dentro do edifício bem depois do horário de fechamento.'),
    (16, 116, 'Vi alguém segurando um convite terminado em "-R". Ele usava um terno azul-marinho e gravata branca.'),
    (17, 89, 'Percebi que o sistema de alarme já estava desativado quando cheguei para meu turno matinal às 5h.'),
    (18, 12, 'Durante meu passeio noturno, vi várias lanternas se movendo dentro do edifício fechado.'),
    (19, 34, 'Lembro de ouvir uma discussão acalorada em idioma estrangeiro vindo da garagem.'),
    (20, 56, 'Ao entregar encomendas, notei que a porta lateral tinha marcas recentes de arranhões ao redor da fechadura.'),
    (21, 78, 'Vi alguém fotografando repetidamente os locais das câmeras de segurança do edifício mais cedo naquele dia.'),
    (22, 90, 'Durante meu turno na cafeteria, ouvi por acaso alguém discutindo plantas detalhadas do layout do edifício.'),
    (23, 23, 'Notei uma escada encostada na parede dos fundos perto da janela do segundo andar ao entardecer.'),
    (24, 45, 'Do meu táxi, vi alguém usando balaclava apesar do tempo quente entrando no edifício.'),
    (25, 67, 'Ouvi o som de vidro quebrando seguido de passos rápidos por volta de 1h da manhã.'),
    (26, 89, 'Passeando com meu cachorro, notei veículos desconhecidos estacionados na área exclusiva para funcionários.'),
    (27, 12, 'Vi alguém copiando o que pareciam ser códigos de segurança perto do teclado da entrada.'),
    (28, 34, 'Durante minha patrulha noturna, encontrei marcas frescas de pneus levando até a doca de carga normalmente sem uso.'),
    (29, 56, 'Testemunhei alguém em uniforme de entrega, mas o logotipo da empresa parecia obviamente falso.'),
    (30, 78, 'Da minha janela, vi pessoas carregando obras de arte em uma van sem identificação às 3h da manhã.'),
    (31, 90, 'Notei que as luzes de segurança foram deliberadamente cobertas com algum tipo de material escuro.'),
    (32, 23, 'Enquanto limpava as janelas, vi alguém testando chaves diferentes na entrada dos fundos.'),
    (33, 45, 'Ouvi sons incomuns de perfuração vindos da área do cofre após o expediente.'),
    (34, 67, 'Durante meu cooper noturno, vi várias pessoas usando roupas idênticas entrando por portas diferentes.'),
    (35, 89, 'Notei alguém fazendo anotações detalhadas enquanto observava a escala de rotação dos guardas.'),
    (36, 12, 'Da minha mesa, vi uma pessoa com uniforme de manutenção que parecia desconhecer o layout básico do local.'),
    (37, 34, 'Ouvi o que parecia ser comunicações por rádio em código vindas da estrutura de estacionamento.'),
    (38, 56, 'Ao entregar correspondências, notei que o painel de segurança havia sido adulterado recentemente.'),
    (39, 78, 'Vi alguém fotografando a entrada de funcionários durante a troca de turnos.'),
    (40, 90, 'Durante meu intervalo, notei uma pessoa suspeita monitorando os padrões de patrulha da segurança.'),
    (41, 23, 'Observei alguém tentando acessar o telhado pela escada de incêndio.'),
    (42, 45, 'Do meu apartamento, vi lanternas se movendo pelo edifício muito depois do fechamento.'),
    (43, 67, 'Ouvi o som de latas de spray sendo usadas dentro da galeria fechada.'),
    (44, 89, 'Ao fechar, percebi que alguém havia deixado várias saídas de emergência abertas.'),
    (45, 12, 'Vi um grupo de pessoas usando máscaras entrando pela entrada de serviço.'),
    (46, 34, 'Durante meu turno, percebi que as câmeras de segurança estavam sendo redirecionadas sistematicamente.'),
    (47, 56, 'Ouvi sons de bipes incomuns vindos do painel de controle do alarme.'),
    (48, 78, 'Do estacionamento, vi alguém anotando a escala de patrulha da segurança.'),
    (49, 90, 'Notei danos recentes na fechadura da entrada do depósito nos fundos.'),
    (50, 129, 'Ouvi por acaso alguém dizer: "Me encontre na marina, doca 3.'),
    (51, 45, 'Observei alguém usando equipamento sofisticado para contornar os leitores de cartão.'),
    (52, 67, 'Durante minha patrulha, encontrei evidências de alguém monitorando as transmissões das câmeras de segurança.'),
    (53, 89, 'Vi atividade incomum perto dos pontos de acesso ao sistema de ventilação.'),
    (54, 12, 'Do meu escritório, notei alguém tentando acessar áreas restritas repetidamente.'),
    (55, 34, 'Ouvi ferramentas elétricas sendo usadas na área de armazenamento de artefatos após o expediente.'),
    (56, 56, 'Enquanto limpava, encontrei ferramentas profissionais de arrombamento descartadas.'),
    (57, 78, 'Observei várias pessoas se comunicando por sinais de mão perto da entrada.'),
    (58, 90, 'Durante meu turno, percebi que as saídas de emergência haviam sido adulteradas.'),
    (59, 23, 'Vi alguém com uniforme de segurança falso inspecionando os sistemas de alarme.'),
    (60, 45, 'Da rua, notei atividade incomum no andar superior normalmente vazio.'),
    (61, 67, 'Ouvi o que parecia ser equipamentos pesados sendo movidos tarde da noite.'),
    (62, 89, 'Ao passar, vi alguém desativando as luzes de segurança externas.'),
    (63, 12, 'Notei uma reunião suspeita na garagem após o horário de funcionamento.'),
    (64, 34, 'Durante minhas rondas, encontrei evidências de alguém monitorando a movimentação dos funcionários.'),
    (65, 56, 'Observei várias pessoas usando disfarces idênticos entrando separadamente.'),
    (66, 78, 'Da minha janela, vi alguém testando o tempo de resposta do sistema de segurança.'),
    (67, 90, 'Notei marcas incomuns ao redor dos painéis de acesso ao sistema de ventilação.'),
    (68, 23, 'Trabalhando até tarde, ouvi ruídos estranhos vindos das exposições lacradas.'),
    (69, 45, 'Vi alguém tentando acessar a sala de controle de segurança repetidamente.'),
    (70, 67, 'Durante meu turno, encontrei evidências de equipamentos de vigilância sendo instalados.'),
    (71, 89, 'Observei alguém tirando fotos detalhadas das medidas de segurança.'),
    (72, 12, 'Do edifício vizinho, vi atividade incomum nas áreas restritas.'),
    (73, 34, 'Notei alguém tentando clonar cartões de acesso de segurança.'),
    (74, 56, 'Durante minha patrulha, encontrei ferramentas usadas para contornar fechaduras eletrônicas.'),
    (75, 78, 'Ouvi comunicações de rádio codificadas vindas de múltiplas direções.'),
    (76, 90, 'Durante meu intervalo, vi alguém mapeando os pontos cegos das câmeras.'),
    (77, 23, 'Observei várias pessoas se coordenando por meio de fones de ouvido ocultos.'),
    (78, 45, 'Do meu posto, notei alguém cronometrando os intervalos de patrulha da segurança.'),
    (79, 67, 'Vi movimentação incomum de veículos perto da entrada de serviço.'),
    (80, 89, 'Ao fechar, encontrei evidências de alguém acessando arquivos restritos.'),
    (81, 12, 'Ouvi o que parecia ser ferramentas de corte profissionais sendo usadas.'),
    (82, 34, 'Durante meu turno, percebi que o sistema de vigilância havia sido comprometido.'),
    (83, 75, 'Ouvi por acaso uma reserva no The Grand Regency.'),
    (84, 78, 'Da rua, vi várias pessoas em uniformes de serviço após o expediente.'),
    (85, 90, 'Notei atividade incomum ao redor das escadarias de saída de emergência.'),
    (86, 23, 'Enquanto trabalhava, encontrei evidências de violações sistemáticas de segurança.'),
    (87, 45, 'Ouvi sons mecânicos incomuns vindos da área de armazenamento seguro.'),
    (88, 67, 'Durante minhas rondas, vi alguém adulterando o sistema de controle de acesso.'),
    (89, 75, 'Notei alguém na recepção discutindo o Quarto 707 para uma reserva feita no dia anterior.'),
    (90, 12, 'Da minha posição, notei alguém desativando os sensores de segurança sistematicamente.'),
    (91, 34, 'Vi padrões incomuns de movimentação perto das áreas restritas.'),
    (92, 56, 'Durante minha patrulha, encontrei equipamentos sofisticados de hacking escondidos nas proximidades.'),
    (93, 78, 'Ouvi o que parecia ser ferramentas profissionais sendo usadas nas fechaduras.'),
    (94, 90, 'Durante meu turno, percebi alguém monitorando a rotação dos funcionários.'),
    (95, 23, 'Observei várias pessoas usando crachás de identificação falsos.'),
    (96, 45, 'Do estacionamento, vi alguém instalando dispositivos desconhecidos perto das câmeras.'),
    (97, 67, 'Notei atividade incomum em áreas tipicamente restritas do edifício.'),
    (98, 89, 'Enquanto trabalhava, encontrei evidências de adulteração coordenada do sistema de segurança.'),
    (99, 12, 'Ouvi comunicações de rádio criptografadas vindas de múltiplos locais.'),
    (100, 34, 'Durante minha patrulha, observei alguém contornando os scanners biométricos.')
  ;`,

  // 4. Attire Registry
  `CREATE TABLE attire_registry (
    id INTEGER PRIMARY KEY,
    guest_id INTEGER,
    note TEXT,
    FOREIGN KEY (guest_id) REFERENCES guest(id)
  );`,
  `INSERT INTO attire_registry (id, guest_id, note) VALUES
    (1, 1, 'black tuxedo, emerald cufflinks'),
    (2, 2, 'navy suit, red tie'),
    (3, 3, 'red gown, diamond necklace'),
    (4, 4, 'navy suit, blue tie'),
    (5, 156, 'purple evening gown, sapphire earrings'),
    (6, 23, 'navy suit, green tie'),
    (7, 189, 'black velvet dress, gold bracelet'),
    (8, 45, 'navy suit, yellow tie'),
    (9, 167, 'emerald gown, diamond choker'),
    (10, 34, 'navy suit, purple tie'),
    (11, 178, 'blue silk dress, pearl necklace'),
    (12, 12, 'navy suit, orange tie'),
    (13, 190, 'red sequin gown, ruby earrings'),
    (14, 87, 'navy suit, burgundy tie'),
    (15, 145, 'navy suit, silver tie'),
    (16, 89, 'navy suit, gold tie'),
    (17, 112, 'gold evening gown, topaz necklace'),
    (18, 167, 'navy suit, crimson tie'),
    (19, 134, 'silver cocktail dress, diamond bracelet'),
    (20, 178, 'navy suit, navy tie'),
    (21, 156, 'champagne gown, crystal earrings'),
    (22, 190, 'navy suit, maroon tie'),
    (23, 123, 'maroon velvet dress, gold choker'),
    (24, 145, 'navy suit, teal tie'),
    (25, 189, 'navy evening gown, sapphire pendant'),
    (26, 112, 'navy suit, black tie'),
    (27, 167, 'burgundy dress, diamond drop earrings'),
    (28, 134, 'navy suit, emerald tie'),
    (29, 178, 'emerald silk gown, crystal bracelet'),
    (30, 156, 'navy suit, white tie'),
    (31, 190, 'red velvet dress, pearl choker'),
    (32, 123, 'navy suit, grey tie'),
    (33, 145, 'silver gown, emerald earrings'),
    (34, 189, 'navy suit, brown tie'),
    (35, 112, 'purple silk dress, sapphire bracelet'),
    (36, 167, 'navy suit, coral tie'),
    (37, 134, 'black lace gown, ruby necklace'),
    (38, 178, 'burgundy suit, pearl tie clip'),
    (39, 156, 'gold cocktail dress, diamond pendant'),
    (40, 190, 'charcoal tuxedo, emerald studs'),
    (41, 123, 'blue evening gown, topaz earrings'),
    (42, 145, 'navy suit, white tie'),
    (43, 189, 'red silk dress, crystal choker'),
    (44, 112, 'navy suit, onyx tie pin'),
    (45, 167, 'emerald velvet gown, pearl bracelet'),
    (46, 134, 'grey tuxedo, diamond cufflinks'),
    (47, 178, 'champagne dress, ruby pendant'),
    (48, 105, 'navy suit, white tie'),
    (49, 190, 'maroon evening gown, emerald necklace'),
    (50, 123, 'black tuxedo, crystal tie clip'),
    (51, 145, 'silver silk dress, sapphire choker'),
    (52, 189, 'navy pinstripe suit, pearl tie pin'),
    (53, 112, 'navy suit, white tie'),
    (54, 167, 'charcoal suit, ruby cufflinks'),
    (55, 134, 'burgundy velvet dress, onyx pendant'),
    (56, 178, 'cream tuxedo, emerald studs'),
    (57, 156, 'black lace gown, gold earrings'),
    (58, 190, 'navy suit, white tie'),
    (59, 123, 'blue cocktail dress, pearl necklace'),
    (60, 145, 'white suit, sapphire cufflinks'),
    (61, 189, 'navy suit, white tie'),
    (62, 112, 'navy tuxedo, topaz tie pin'),
    (63, 167, 'navy suit, white tie'),
    (64, 134, 'black pinstripe suit, pearl studs'),
    (65, 178, 'gold velvet gown, crystal pendant'),
    (66, 156, 'burgundy suit, emerald cufflinks'),
    (67, 190, 'navy suit, white tie'),
    (68, 123, 'charcoal tuxedo, diamond tie clip'),
    (69, 145, 'champagne silk gown, sapphire earrings'),
    (70, 189, 'black velvet dress, pearl bracelet'),
    (71, 112, 'navy suit, ruby cufflinks'),
    (72, 167, 'red lace gown, crystal choker'),
    (73, 134, 'grey pinstripe suit, emerald tie pin'),
    (74, 178, 'purple evening gown, diamond pendant'),
    (75, 129, 'black tuxedo, patent leather dress shoes'),
    (76, 190, 'emerald velvet dress, gold earrings'),
    (77, 123, 'burgundy suit, sapphire cufflinks'),
    (78, 145, 'blue silk gown, pearl necklace'),
    (79, 189, 'charcoal tuxedo, crystal tie clip'),
    (80, 112, 'silver cocktail dress, ruby bracelet'),
    (81, 167, 'black suit, diamond studs'),
    (82, 134, 'maroon evening gown, emerald choker'),
    (83, 178, 'navy pinstripe suit, topaz cufflinks'),
    (84, 156, 'gold lace dress, pearl pendant'),
    (85, 190, 'grey tuxedo, sapphire tie pin'),
    (86, 123, 'cream silk gown, onyx bracelet'),
    (87, 145, 'burgundy velvet suit, crystal studs'),
    (88, 189, 'black dress, ruby necklace'),
    (89, 112, 'emerald tuxedo, diamond cufflinks'),
    (90, 167, 'purple silk dress, gold choker'),
    (91, 134, 'white suit, pearl tie clip'),
    (92, 178, 'red evening gown, sapphire pendant'),
    (93, 156, 'navy velvet tuxedo, emerald studs'),
    (94, 190, 'charcoal dress, crystal bracelet'),
    (95, 123, 'silver suit, ruby cufflinks'),
    (96, 145, 'black lace gown, diamond earrings'),
    (97, 189, 'burgundy pinstripe suit, onyx tie pin'),
    (98, 116, 'blue velvet dress, pearl choker'),
    (99, 167, 'grey tuxedo, gold studs'),
    (100, 134, 'emerald silk gown, sapphire necklace'),
    (101, 178, 'white suit, crystal cufflinks'),
    (102, 156, 'red lace dress, diamond pendant'),
    (103, 190, 'navy tuxedo, emerald tie clip'),
    (104, 123, 'purple evening gown, pearl bracelet')
  ;`,

  // 5. Marina Rentals
  `CREATE TABLE marina_rentals (
      id INTEGER PRIMARY KEY,
      dock_number INTEGER,
      renter_guest_id INTEGER,
      rental_date INTEGER,
      boat_name TEXT,
      FOREIGN KEY (renter_guest_id) REFERENCES guest(id)
    );`,
  `INSERT INTO marina_rentals (id, dock_number, renter_guest_id, rental_date, boat_name) VALUES
    (1, 4, 156, 19871025, 'Sea Whisper'),
    (2, 2, 89, 19871027, 'Ocean Breeze'),
    (3, 1, 134, 19871028, 'Wave Dancer'),
    (4, 3, 45, 19870520, 'Coastal Dream'),
    (5, 5, 178, 19871026, 'Marina Belle'),
    (6, 2, 23, 19871029, 'Blue Horizon'),
    (7, 4, 167, 19871025, 'Sunset Chaser'),
    (8, 1, 91, 19871027, 'Wind Spirit'),
    (9, 3, 112, 19870520, 'Sea Serenade'),
    (10, 5, 145, 19871026, 'Ocean Mist'),
    (11, 2, 89, 19871029, 'Wave Runner'),
    (12, 4, 34, 19871025, 'Coastal Jewel'),
    (13, 1, 167, 19871027, 'Marina Star'),
    (14, 3, 78, 19870520, 'Blue Pearl'),
    (15, 5, 123, 19871026, 'Sunset Dream'),
    (16, 2, 45, 19871029, 'Wind Dancer'),
    (17, 4, 190, 19871025, 'Sea Princess'),
    (18, 1, 56, 19871027, 'Ocean Spray'),
    (19, 3, 145, 19870520, 'Wave Seeker'),
    (20, 5, 89, 19871026, 'Coastal Beauty'),
    (21, 2, 112, 19871029, 'Marina Mist'),
    (22, 4, 78, 19871025, 'Blue Wave'),
    (23, 1, 23, 19871027, 'Sunset Lady'),
    (24, 3, 167, 19870520, 'Wind Song'),
    (25, 5, 34, 19871026, 'Sea Breeze'),
    (26, 2, 156, 19871029, 'Ocean Dream'),
    (27, 4, 91, 19871025, 'Wave Spirit'),
    (28, 1, 145, 19871027, 'Coastal Star'),
    (29, 3, 78, 19870520, 'Marina Belle II'),
    (30, 5, 112, 19871026, 'Blue Moon'),
    (31, 2, 34, 19871029, 'Sunset Wave'),
    (32, 4, 167, 19871025, 'Wind Seeker'),
    (33, 1, 23, 19871027, 'Sea Pearl'),
    (34, 3, 190, 19870520, 'Ocean Spirit'),
    (35, 5, 56, 19871026, 'Wave Princess'),
    (36, 2, 145, 19871029, 'Coastal Spray'),
    (37, 4, 89, 19871025, 'Marina Dream'),
    (38, 1, 112, 19871027, 'Blue Lady'),
    (39, 3, 78, 19870520, 'Sunset Mist'),
    (40, 5, 167, 19871026, 'Wind Star'),
    (41, 2, 34, 19871029, 'Sea Song'),
    (42, 4, 156, 19871025, 'Ocean Beauty'),
    (43, 1, 91, 19871027, 'Wave Moon'),
    (44, 3, 105, 19870520, 'Coastal Spirit'),
    (45, 5, 23, 19871026, 'Marina Wave'),
    (46, 2, 78, 19871029, 'Blue Seeker'),
    (47, 4, 112, 19871025, 'Sunset Pearl'),
    (48, 1, 167, 19871027, 'Wind Princess'),
    (49, 3, 34, 19870520, 'Sea Spray'),
    (50, 5, 190, 19871026, 'Ocean Lady'),
    (51, 2, 56, 19871029, 'Wave Star'),
    (52, 4, 145, 19871025, 'Coastal Mist'),
    (53, 1, 89, 19871027, 'Marina Moon'),
    (54, 3, 112, 19871028, 'Blue Spirit'),
    (55, 5, 78, 19871026, 'Sunset Beauty'),
    (56, 2, 167, 19871029, 'Wind Wave'),
    (57, 4, 34, 19871025, 'Sea Seeker'),
    (58, 1, 156, 19871027, 'Ocean Pearl'),
    (59, 3, 91, 19871028, 'Wave Lady'),
    (60, 5, 145, 19871026, 'Coastal Star II'),
    (61, 2, 23, 19871029, 'Marina Spirit'),
    (62, 4, 78, 19871025, 'Blue Princess'),
    (63, 1, 112, 19871027, 'Sunset Spray'),
    (64, 3, 167, 19871028, 'Wind Moon'),
    (65, 5, 34, 19871026, 'Sea Star'),
    (66, 2, 190, 19871029, 'Ocean Mist II'),
    (67, 4, 56, 19871025, 'Wave Beauty'),
    (68, 1, 145, 19871027, 'Coastal Wave'),
    (69, 3, 89, 19871028, 'Marina Seeker'),
    (70, 5, 112, 19871026, 'Blue Pearl II'),
    (71, 2, 78, 19871029, 'Sunset Spirit'),
    (72, 4, 167, 19871025, 'Wind Lady'),
    (73, 1, 34, 19871027, 'Sea Moon'),
    (74, 3, 156, 19871028, 'Ocean Star II'),
    (75, 5, 91, 19871026, 'Wave Spirit II'),
    (76, 2, 145, 19871029, 'Coastal Princess'),
    (77, 4, 23, 19871025, 'Marina Spray'),
    (78, 1, 78, 19871027, 'Blue Mist'),
    (79, 3, 112, 19871028, 'Sunset Wave II'),
    (80, 5, 167, 19871026, 'Wind Beauty'),
    (81, 2, 34, 19871029, 'Sea Princess II'),
    (82, 4, 190, 19871025, 'Ocean Spirit II'),
    (83, 1, 56, 19871027, 'Wave Seeker II'),
    (84, 3, 145, 19871028, 'Coastal Lady'),
    (85, 5, 89, 19871026, 'Marina Pearl'),
    (86, 2, 112, 19871029, 'Blue Star'),
    (87, 4, 78, 19871025, 'Sunset Moon'),
    (88, 1, 167, 19871027, 'Wind Spirit II'),
    (89, 3, 34, 19871028, 'Sea Beauty'),
    (90, 5, 156, 19871026, 'Ocean Wave'),
    (91, 2, 91, 19871029, 'Wave Pearl'),
    (92, 4, 145, 19871025, 'Coastal Spirit II'),
    (93, 1, 23, 19871027, 'Marina Star II'),
    (94, 3, 78, 19871028, 'Blue Moon II'),
    (95, 5, 112, 19871026, 'Sunset Seeker'),
    (96, 2, 167, 19871029, 'Wind Wave II'),
    (97, 4, 34, 19871025, 'Sea Spirit II'),
    (98, 1, 190, 19871027, 'Ocean Beauty II'),
    (99, 3, 56, 19871028, 'Wave Star II'),
    (100, 5, 145, 19871026, 'Coastal Dream II')
    ;`,

  // 6. Final Interviews
  `CREATE TABLE final_interviews (
      id INTEGER PRIMARY KEY,
      guest_id INTEGER,
      confession TEXT,
      FOREIGN KEY (guest_id) REFERENCES guest(id)
    );`,
  `INSERT INTO final_interviews (id, guest_id, confession) VALUES
      (1, 1, 'Eu não matei ninguém, juro. Quem pensaria que eu seria capaz disso?'),
      (2, 2, 'Olha, eu estava na academia naquele dia. Eu jamais mataria outro ser humano.'),
      (3, 3, 'Minha mãe me criou melhor do que isso. Eu não matei ninguém, ponto final.'),
      (4, 4, 'Que acusação ridícula! Eu não seria capaz de matar nem se quisesse.'),
      (5, 5, 'Você pegou a pessoa errada. Eu não sou alguém que mataria.'),
      (6, 6, 'Verifique meu álibi se quiser. Eu não matei ninguém naquela noite.'),
      (7, 7, 'Eu estava assistindo TV em casa. Como eu poderia matar alguém?'),
      (8, 8, 'Isso é absurdo! Nunca matei nada maior do que uma aranha.'),
      (9, 9, 'Eu tenho cara de quem mata? Desmaio só de ver sangue.'),
      (10, 10, 'Deixa eu ser claro sobre isso. Eu não matei essa pessoa.'),
      (11, 11, 'Sou uma pessoa pacífica. Eu não mataria ninguém jamais.'),
      (12, 12, 'Você está latindo para a árvore errada. Eu não matei ninguém.'),
      (13, 13, 'Eu estava com minha família naquela noite. Eu não mataria ninguém nem se quisesse.'),
      (14, 14, 'Isso é um erro. Eu não sou o tipo de pessoa que mataria.'),
      (15, 15, 'Pergunte aos meus vizinhos, eu estava em casa. Eu jamais mataria alguém.'),
      (16, 16, 'Sou inocente em tudo isso. Eu não matei essa pessoa nem ninguém mais.'),
      (17, 17, 'Olhe minha ficha, está limpa. Nunca tentei matar ninguém.'),
      (18, 18, 'Você entendeu tudo errado. Eu não mataria nem uma mosca.'),
      (19, 19, 'Eu estava trabalhando o dia todo. Como eu poderia matar alguém?'),
      (20, 20, 'Que ridículo! Não sou capaz de tentar matar ninguém.'),
      (21, 21, 'Verifique as câmeras de segurança. Eu não matei ninguém naquele dia.'),
      (22, 22, 'Sou vegetariano, pelo amor de Deus. Eu não mataria ninguém!'),
      (23, 23, 'Você está cometendo um erro grave. Eu nunca tentei matar ninguém.'),
      (24, 24, 'Eu estava no cinema naquela noite. Seria impossível eu matar alguém.'),
      (25, 25, 'Isso está errado. Eu não sou alguém que mataria.'),
      (26, 26, 'Tenho testemunhas que podem confirmar minha história. Eu não matei ninguém.'),
      (27, 27, 'Minha consciência está limpa. Eu jamais mataria outra pessoa.'),
      (28, 28, 'Sou um cidadão pacífico. Eu não conseguiria matar nem tentando.'),
      (29, 29, 'Tudo isso é loucura. Eu não sou uma pessoa que mataria.'),
      (30, 30, 'Eu estava fora da cidade naquela semana. Como eu poderia matar alguém?'),
      (31, 31, 'Você está muito enganado aqui. Eu não matei ninguém.'),
      (32, 32, 'Trabalho na área da saúde. Salvo vidas, não as tiro.'),
      (33, 33, 'Isso é um completo mal-entendido. Eu jamais mataria ninguém.'),
      (34, 34, 'Tenho um álibi infalível. Eu não matei essa pessoa.'),
      (35, 35, 'Você está olhando para a pessoa errada. Eu não conseguiria matar ninguém.'),
      (36, 36, 'Eu estava dormindo naquele momento. Como eu poderia matar alguém?'),
      (37, 37, 'Isso simplesmente não é possível. Eu não sou alguém que mataria.'),
      (38, 38, 'Sou um cidadão cumpridor da lei. Eu não mataria ninguém.'),
      (39, 39, 'Verifique meu histórico de ligações. Eu não matei ninguém naquela noite.'),
      (40, 40, 'Sou completamente inocente. Eu jamais mataria outra pessoa.'),
      (41, 41, 'Isso está tudo errado. Eu não conseguiria matar alguém.'),
      (42, 42, 'Tenho provas de onde eu estava. Eu não matei ninguém.'),
      (43, 43, 'Você pegou a pessoa errada. Eu não sou alguém que mataria.'),
      (44, 44, 'Eu estava em uma festa naquela noite. Eu não poderia matar ninguém.'),
      (45, 45, 'Isso é um erro. Eu jamais mataria outro ser humano.'),
      (46, 46, 'Estou chocado com essas acusações. Eu não matei ninguém.'),
      (47, 47, 'Olhe meu histórico. Não sou capaz de tentar matar.'),
      (48, 48, 'Tenho um álibi à prova de falhas. Eu não mataria ninguém.'),
      (49, 49, 'Isso é completamente falso. Eu não conseguiria matar alguém nem tentando.'),
      (50, 50, 'Eu estava com meus filhos naquele dia. Eu jamais mataria ninguém.'),
      (51, 51, 'Você está cometendo um erro. Eu não matei essa pessoa.'),
      (52, 52, 'Sou uma pessoa pacífica. Eu não conseguiria matar ninguém.'),
      (53, 53, 'Isso é absurdo! Eu jamais mataria outro ser humano.'),
      (54, 54, 'Tenho testemunhas. Eu não matei ninguém naquela noite.'),
      (55, 55, 'Você entendeu tudo errado. Eu não sou alguém que mataria.'),
      (56, 56, 'Eu estava na missa naquela manhã. Eu não poderia matar ninguém.'),
      (57, 57, 'Isso é um enorme mal-entendido. Eu jamais mataria.'),
      (58, 58, 'Eu não matei Leo propriamente. Fui apenas um intermediário.'),
      (59, 59, 'Sou inocente nisso. Eu não conseguiria matar alguém.'),
      (60, 60, 'Você está latindo para a árvore errada. Eu não mataria ninguém.'),
      (61, 61, 'Tenho um álibi sólido. Eu não matei ninguém naquele dia.'),
      (62, 62, 'Isso está errado. Eu não sou do tipo que mata.'),
      (63, 63, 'Eu estava na academia a noite toda. Eu não poderia matar ninguém.'),
      (64, 64, 'Você pegou a pessoa errada. Eu jamais mataria.'),
      (65, 65, 'Sou uma alma gentil. Eu não matei ninguém.'),
      (66, 66, 'Que ridículo. Eu não conseguiria matar nem se quisesse.'),
      (67, 67, 'Tenho provas do meu paradeiro. Eu não sou alguém que mataria.'),
      (68, 68, 'Você está enganado. Eu não matei essa pessoa.'),
      (69, 69, 'Eu estava em uma reunião então. Eu jamais mataria ninguém.'),
      (70, 70, 'Isso está tudo errado. Eu não conseguiria matar ninguém.'),
      (71, 71, 'Verifique as fitas de vigilância. Eu não matei ninguém.'),
      (72, 72, 'Sou pacifista. Eu não mataria nenhum ser vivo.'),
      (73, 73, 'Você confundiu tudo. Eu não conseguiria matar ninguém.'),
      (74, 74, 'Eu estava dando aula naquele momento. Eu jamais mataria.'),
      (75, 75, 'Isso é um erro. Eu não matei essa pessoa.'),
      (76, 76, 'Tenho pessoas que podem confirmar minha história. Eu não conseguiria matar.'),
      (77, 77, 'Você está muito enganado. Eu não mataria ninguém.'),
      (78, 78, 'Eu estava no consultório médico. Eu não matei ninguém.'),
      (79, 79, 'Isso está completamente errado. Eu não sou alguém que mataria.'),
      (80, 80, 'Tenho documentação do meu paradeiro. Eu não conseguiria matar ninguém.'),
      (81, 81, 'Você está enganado sobre isso. Eu jamais mataria.'),
      (82, 82, 'Eu estava fazendo compras naquele momento. Eu não matei ninguém.'),
      (83, 83, 'Isso é falso. Eu não conseguiria matar alguém.'),
      (84, 84, 'Tenho recibos para provar onde eu estava. Eu não sou do tipo que mata.'),
      (85, 85, 'Você pegou a pessoa errada. Eu não mataria ninguém.'),
      (86, 86, 'Eu estava em um show naquela noite. Eu não matei essa pessoa.'),
      (87, 87, 'Isso simplesmente não é verdade. Eu não conseguiria matar nem tentando.'),
      (88, 88, 'Tenho evidências em vídeo do meu paradeiro. Eu jamais mataria.'),
      (89, 89, 'Você está olhando para o suspeito errado. Eu não matei ninguém.'),
      (90, 90, 'Eu estava visitando meus pais. Eu não conseguiria matar alguém.'),
      (91, 91, 'Isso é um erro completo. Eu não sou alguém que mataria.'),
      (92, 92, 'Tenho um álibi para aquele horário. Eu não mataria ninguém.'),
      (93, 93, 'Você entendeu tudo errado. Eu não matei essa pessoa.'),
      (94, 94, 'Eu estava em um casamento naquele dia. Eu não poderia matar ninguém.'),
      (95, 95, 'Isso é absolutamente falso. Eu jamais mataria.'),
      (96, 96, 'Tenho testemunhas para confirmar minha história. Eu não matei ninguém.'),
      (97, 97, 'Eu mandei fazer o serviço. Fui eu. Você me pegou.'),
      (98, 98, 'Eu estava na biblioteca então. Eu não mataria ninguém.'),
      (99, 99, 'Isso está tudo incorreto. Eu não sou alguém que mataria.'),
      (100, 100, 'Tenho imagens de segurança para provar. Eu não matei ninguém.'),
      (101, 101, 'Eu estava alimentando pombos no parque naquele dia. Assassinato vai contra meus princípios.'),
      (102, 102, 'Você pode verificar minhas postagens no Instagram daquele horário. Eu jamais tiraria uma vida.'),
      (103, 103, 'Eu estava transmitindo ao vivo na Twitch a noite toda. Violência me dá náusea.'),
      (104, 104, 'Meu Fitbit mostra que eu estava correndo então. Eu não poderia ter matado ninguém.'),
      (105, 105, 'Fui eu quem pegou o cristal. Acho que preciso de um advogado agora?'),
      (106, 106, 'Verifique meu histórico de navegação, eu estava fazendo compras online. Não sou uma pessoa violenta.'),
      (107, 107, 'Eu estava fazendo uma tatuagem exatamente naquele horário. Eu não machucaria nem uma mosca.'),
      (108, 108, 'Meu histórico no Uber prova que eu estava do outro lado da cidade. Nunca me envolvi em uma briga sequer.'),
      (109, 109, 'Eu estava em uma corrida beneficente naquela manhã. Violência não faz parte da minha natureza.'),
      (110, 110, 'O GPS do meu celular mostra que eu estava em outro lugar. Eu não conseguiria machucar outra pessoa.'),
      (111, 111, 'Eu estava na minha aula de cerâmica então. Sou um criador, não um destruidor.'),
      (112, 112, 'As câmeras de segurança da academia me mostram lá. Sou inocente desse crime.'),
      (113, 113, 'Eu estava em cirurgia odontológica naquele dia. Não sou capaz de cometer assassinato.'),
      (114, 114, 'Meus registros de cartão de crédito mostram que eu estava fazendo compras. Nunca machuquei ninguém.'),
      (115, 115, 'Eu estava transmitindo ao vivo no Facebook. Matar vai contra tudo o que defendo.'),
      (116, 116, 'Verifique os registros do meu computador no trabalho. Eu jamais cometeria um ato tão horrível.'),
      (117, 117, 'Eu estava em uma aula de culinária naquela noite. Violência não faz parte de quem eu sou.'),
      (118, 118, 'Meu histórico da Netflix mostra que eu estava em casa assistindo filmes. Não sou um assassino.'),
      (119, 119, 'Eu estava fazendo voluntariado no abrigo de animais. Eu jamais tiraria uma vida.'),
      (120, 120, 'Meu passe de trem mostra que eu estava viajando então. Não sou capaz de cometer assassinato.'),
      (121, 121, 'Eu estava no recital de piano do meu filho. Nunca pensei sequer em matar.'),
      (122, 122, 'Os registros da biblioteca mostram que eu estava estudando. Sou uma pessoa pacífica.'),
      (123, 123, 'Eu estava fazendo o cabelo no salão. Violência não é o meu jeito.'),
      (124, 124, 'Minha campainha inteligente mostra quando eu estava em casa. Eu não machucaria ninguém.'),
      (125, 125, 'Eu estava em um workshop de ioga naquele dia. Tirar uma vida vai contra minhas crenças.'),
      (126, 126, 'Verifique meus recibos de estacionamento no centro. Não sou esse tipo de pessoa.'),
      (127, 127, 'Eu estava na minha reunião semanal do clube do livro. Eu não conseguiria matar outro ser humano.'),
      (128, 128, 'Os registros da minha academia provam minha localização. Sou inocente disso.'),
      (129, 129, 'Eu estava cuidando da minha mãe doente. Eu jamais cometeria um assassinato.'),
      (130, 130, 'A boliche tem minhas imagens nas câmeras. Não sou capaz de tamanha violência.'),
      (131, 131, 'Eu estava na minha aula de pintura então. Crio arte, não destruição.'),
      (132, 132, 'Os registros do cartão-chave do meu hotel mostram minha localização. Não sou uma pessoa violenta.'),
      (133, 133, 'Eu estava em um casamento naquele dia. Eu não poderia ter matado ninguém.'),
      (134, 134, 'Verifique os registros do meu serviço de internet. Não sou o assassino que você procura.'),
      (135, 135, 'Eu estava em uma conferência de negócios. Violência vai contra minha natureza.'),
      (136, 136, 'Meu histórico do metrô prova meu paradeiro. Não sou um assassino.'),
      (137, 137, 'Eu estava tomando café com amigos. Eu jamais tiraria a vida de alguém.'),
      (138, 138, 'A câmera do caixa eletrônico me filmou fazendo um saque então. Eu não poderia ter feito isso.'),
      (139, 139, 'Eu estava na minha sessão semanal de terapia. Não sou capaz de cometer assassinato.'),
      (140, 140, 'Meu registro de ligações mostra que eu estava em outro lugar. Nunca machuquei ninguém.'),
      (141, 141, 'Eu estava cuidando dos filhos do meu vizinho. Eu não cometeria tal crime.'),
      (142, 142, 'Verifique os registros de presença na igreja. Sou uma pessoa pacífica.'),
      (143, 143, 'Eu estava em uma pré-estreia de filme naquela noite. Eu não poderia ter matado ninguém.'),
      (144, 144, 'Meu clube de jardinagem pode confirmar minha história. Eu cultivo a vida, não a tiro.'),
      (145, 145, 'Eu estava levando meu carro para fazer a revisão então. Não sou uma pessoa violenta.'),
      (146, 146, 'As câmeras do supermercado me mostram fazendo compras. Eu não machucaria ninguém.'),
      (147, 147, 'Eu estava na minha aula de dança naquela noite. Violência não faz parte da minha natureza.'),
      (148, 148, 'As imagens de segurança do meu prédio provam minha inocência. Não sou um assassino.'),
      (149, 149, 'Eu estava em uma reunião de pais e professores. Eu jamais tiraria uma vida.'),
      (150, 150, 'Verifique os registros de acesso do meu crachá no trabalho. Sou inocente desse crime.'),
      (151, 151, 'Eu estava em um show de música então. Eu não machucaria outra pessoa.'),
      (152, 152, 'Minhas postagens nas redes sociais mostram minha localização. Não sou capaz de matar.'),
      (153, 153, 'Eu estava fazendo meu exame de direção naquele dia. Violência não faz parte de quem eu sou.'),
      (154, 154, 'O recibo do restaurante mostra que eu estava jantando. Eu não poderia ter feito isso.'),
      (155, 155, 'Eu estava em uma entrevista de emprego então. Não sou do tipo que comete assassinato.'),
      (156, 156, 'Meu passe de ônibus mostra que eu estava viajando. Eu jamais tiraria a vida de alguém.'),
      (157, 157, 'Eu estava na minha reunião do clube de xadrez. Sou uma pessoa de paz, não de violência.'),
      (158, 158, 'Verifique os registros de visitantes do hospital. Eu não poderia ter matado ninguém.'),
      (159, 159, 'Eu estava em um jogo de futebol naquele dia. Não sou capaz de tais atos.'),
      (160, 160, 'Meu cartão de crédito mostra que eu estava no shopping. Eu não machucaria nenhuma alma.'),
      (161, 161, 'Eu estava em uma aula de culinária então. Crio comida, não destruição.'),
      (162, 162, 'As câmeras de segurança da farmácia me mostram lá. Não sou uma pessoa violenta.'),
      (163, 163, 'Eu estava no jogo de futebol da minha filha. Eu não poderia ter cometido assassinato.'),
      (164, 164, 'Meu personal trainer pode confirmar minha presença. Sou inocente dessa acusação.'),
      (165, 165, 'Eu estava em uma degustação de vinhos. Violência não é algo que sou capaz de fazer.'),
      (166, 166, 'Verifique minha passagem aérea daquele dia. Eu jamais mataria ninguém.'),
      (167, 167, 'Eu estava em um workshop de fotografia. Eu capturo a vida, não a tiro.'),
      (168, 168, 'O registro da minha consulta no dentista prova meu álibi. Não sou um assassino.'),
      (169, 169, 'Eu estava em uma festa de aniversário então. Eu não poderia ter cometido esse crime.'),
      (170, 170, 'As imagens do posto de gasolina me mostram abastecendo. Não sou violento de forma alguma.'),
      (171, 171, 'Eu estava levando meu cachorro ao veterinário. Eu jamais machucaria ninguém.'),
      (172, 172, 'Verifique meus registros de cartão da biblioteca. Sou um cidadão pacífico.'),
      (173, 173, 'Eu estava em um seminário de treinamento profissional. Eu não poderia ter matado ninguém.'),
      (174, 174, 'Minha ficha da academia de natação mostra que eu estava lá. Não sou capaz de cometer assassinato.'),
      (175, 175, 'Eu estava em uma reunião de família então. Violência não está no meu caráter.'),
      (176, 176, 'As câmeras do banco me filmaram fazendo um depósito. Eu não tiraria uma vida.'),
      (177, 177, 'Eu estava no meu grupo de oração semanal. Sou dedicado à paz, não à violência.'),
      (178, 178, 'Verifique meu ticket de estacionamento. Eu não poderia ter feito isso.'),
      (179, 179, 'Eu estava fazendo uma massagem naquele horário. Não sou uma pessoa violenta.'),
      (180, 180, 'Meu cartão de sócio do museu foi usado então. Aprecio arte, não violência.'),
      (181, 181, 'Eu estava em uma aula de idiomas naquele dia. Eu não poderia ter matado ninguém.'),
      (182, 182, 'As câmeras da cafeteria me mostram trabalhando. Não sou capaz de cometer assassinato.'),
      (183, 183, 'Eu estava em um workshop de cerâmica então. Crio beleza, não destruição.'),
      (184, 184, 'Meu talão do teatro prova minha localização. Eu não machucaria ninguém.'),
      (185, 185, 'Eu estava em uma reunião comunitária. Violência não faz parte da minha natureza.'),
      (186, 186, 'Verifique o histórico de localização do meu celular. Sou inocente desse crime.'),
      (187, 187, 'Eu estava em uma competição de dança. Eu não poderia ter cometido assassinato.'),
      (188, 188, 'Meu recibo do hotel mostra que eu estava fora da cidade. Não sou uma pessoa violenta.'),
      (189, 189, 'Eu estava na abertura de uma galeria de arte. Valorizo muito a vida para tirá-la.'),
      (190, 190, 'Os registros da cancela mostram meu carro em outro lugar. Eu não mataria ninguém.'),
      (191, 191, 'Eu estava em uma arrecadação de fundos para caridade. Ajudo pessoas, não as machucho.'),
      (192, 192, 'Verifique meus registros de login no computador. Eu não poderia ter feito isso.'),
      (193, 193, 'Eu estava em um retiro de ioga naquela semana. Sou comprometido com a não-violência.'),
      (194, 194, 'Meu ticket do teleférico prova que eu estava nas pistas. Não sou um assassino.'),
      (195, 195, 'Eu estava em uma competição de culinária então. Crio pratos, não destruição.'),
      (196, 196, 'As imagens de segurança do fliperama me mostram jogando. Eu não machucaria ninguém.'),
      (197, 197, 'Eu estava em uma aula de meditação. Violência vai contra minhas crenças.'),
      (198, 198, 'Verifique meus registros de check-in na academia. Eu não poderia ter matado ninguém.'),
      (199, 199, 'Eu estava em uma aula de piano naquele dia. Faço música, não caos.')
    ;`,
];
