export default [
  // 1. Crime Scenes
  `CREATE TABLE crime_scene (
    id INTEGER PRIMARY KEY,
    date INTEGER,
    location TEXT,
    description TEXT
  );`,
  `INSERT INTO crime_scene (id, date, location, description) VALUES
    (1, 19871030, 'Miami Beach Botanical Garden', 'Rare plants were stolen from research greenhouse. Security reported breach in monitoring systems.'),
    (2, 19871031, 'Coral Gables Country Club', 'A suspicious gathering was reported by multiple attendees. Security footage showed unusual activity near the premises.'),
    (3, 19871030, 'South Beach Marina', 'Several boats were damaged during a late night storm. Investigators found evidence of tampering with the moorings.'),
    (4, 19871031, 'Little Havana Theater', 'An evening performance was disrupted by a power outage. Technical inspection revealed signs of deliberate sabotage.'),
    (5, 19871030, 'Brickell Financial Center', 'Documents were found shredded in executive offices. Security cameras showed unauthorized access after hours.'),
    (6, 19871031, 'Vizcaya Museum Gardens', 'Historical artifacts were reported missing from display cases. Alarm systems had been professionally disabled. The curator was found dead in the back room. The security guard was found dead in the parking lot.'),
    (7, 19871030, 'Coconut Grove Yacht Club', 'A luxury vessel was found adrift in the marina. The owner reported signs of forced entry and theft.'),
    (8, 19871031, 'Design District Gallery', 'Valuable artwork was discovered damaged during exhibition. Surveillance footage showed suspicious movement after closing.'),
    (9, 19871030, 'Wynwood Arts Complex', 'Multiple studios reported vandalism overnight. Evidence suggested coordinated criminal activity.'),
    (10, 19871031, 'Miami Beach Convention Center', 'A high-profile auction was disrupted by security threats. Investigation revealed inside involvement. The auctioneer was found dead in the back room.'),
    (11, 19871030, 'Fisher Island Club', 'Members reported unusual disturbances during dinner service. Staff witnessed suspicious individuals on premises.'),
    (12, 19871031, 'Bayside Marketplace', 'Several shops reported break-ins after midnight. Security systems were found professionally disabled.'),
    (13, 19871030, 'Port of Miami Terminal', 'Cargo containers showed signs of tampering overnight. Dock workers reported unauthorized vehicle movements.'),
    (14, 19871031, 'Venetian Pool', 'Historic facilities were vandalized after hours. Evidence suggested multiple perpetrators were involved.'),
    (15, 19871030, 'Calle Ocho Plaza', 'Street festival preparations were sabotaged overnight. Organizers found equipment deliberately damaged.'),
    (16, 19871031, 'Fairchild Tropical Garden', 'Rare specimens were stolen from secured greenhouses. Security reported breach in perimeter systems.'),
    (17, 19871030, 'Miami River District', 'Warehouse break-ins were reported by multiple businesses. Investigation showed coordinated criminal activity.'),
    (18, 19871031, 'Miracle Mile Shopping Center', 'Jewelry store reported sophisticated burglary attempt. Alarm systems were found professionally bypassed. The owner of the store was found dead in the back room.'),
    (19, 19871030, 'Miami Seaquarium', 'Research facilities showed signs of unauthorized access. Marine biology samples were reported missing.'),
    (20, 19871031, 'Freedom Tower', 'Historical documents were found disturbed in archive room. Security cameras captured unidentified intruders.'),
    (21, 19871030, 'Matheson Hammock Marina', 'Several vessels reported equipment theft overnight. Harbor patrol found evidence of organized crime.'),
    (22, 19871031, 'Deering Estate', 'Historical artifacts were displaced from secure storage. Staff reported unusual activity during evening hours.'),
    (23, 19871030, 'Olympia Theater', 'Valuable props were stolen during overnight hours. Stage equipment showed signs of tampering.'),
    (24, 19871031, 'Jungle Island', 'Animal enclosures were found unlocked after hours. Staff reported missing maintenance equipment.'),
    (25, 19871030, 'Miami City Cemetery', 'Historical monuments were vandalized overnight. Groundskeepers reported suspicious gatherings.'),
    (26, 19871031, 'Marlins Park Area', 'Construction site reported missing materials and equipment. Security footage showed unauthorized vehicles.'),
    (27, 19871030, 'Miami Science Museum', 'Valuable exhibits were tampered with after closing. Staff discovered missing research materials.'),
    (28, 19871031, 'Bayfront Park', 'Public artwork was damaged during evening hours. Park security reported suspicious group activity.'),
    (29, 19871030, 'Miami Childrens Museum', 'Educational displays were vandalized overnight. Security systems showed signs of interference.'),
    (30, 19871031, 'Pérez Art Museum', 'Contemporary artwork was found damaged in storage. Staff reported unauthorized access to restricted areas.'),
    (31, 19871030, 'Adrienne Arsht Center', 'Performance equipment was sabotaged before show time. Technical staff found evidence of deliberate tampering.'),
    (32, 19871031, 'Lummus Park', 'Historical structures showed signs of vandalism. Park rangers reported suspicious night activity.'),
    (33, 19871030, 'Miami Beach Botanical Garden', 'Rare plants were stolen from research greenhouse. Security reported breach in monitoring systems.'),
    (34, 19871031, 'Pinecrest Gardens', 'Art installations were damaged during night hours. Surveillance showed unauthorized access.'),
    (35, 19871030, 'Crandon Park', 'Beach facilities reported extensive vandalism. Staff discovered evidence of overnight criminal activity.'),
    (36, 19871031, 'Greynolds Park', 'Historical structures were damaged after hours. Park security found signs of forced entry.'),
    (37, 19871030, 'Tropical Park', 'Sports facilities reported equipment theft overnight. Security cameras showed suspicious activity.'),
    (38, 19871031, 'Simpson Park', 'Rare plant specimens were stolen from conservatory. Staff found evidence of professional theft.'),
    (39, 19871030, 'Virginia Key Beach', 'Marine research equipment was stolen overnight. Security reported unauthorized boat activity.'),
    (40, 19871031, 'Morningside Park', 'Tennis facilities reported vandalism and theft. Security footage showed coordinated criminal activity.'),
    (41, 19871030, 'Legion Park', 'Community center reported break-in overnight. Staff found evidence of professional burglary.'),
    (42, 19871031, 'Kennedy Park', 'Waterfront facilities showed signs of vandalism. Park patrol reported suspicious gatherings.'),
    (43, 19871030, 'Alice Wainwright Park', 'Park structures were damaged during night hours. Security found evidence of organized activity.'),
    (44, 19871031, 'Margaret Pace Park', 'Recreational equipment was stolen after hours. Staff reported suspicious vehicle movements.'),
    (45, 19871030, 'Peacock Park', 'Sports facilities were vandalized overnight. Security cameras showed unauthorized access.'),
    (46, 19871031, 'South Pointe Park', 'Beach patrol equipment was stolen after hours. Staff reported suspicious group activity.'),
    (47, 19871030, 'Biscayne National Park', 'Marine research stations reported break-ins. Security found evidence of professional theft.'),
    (48, 19870520, 'Fontainebleau Hotel', 'O colar Coração de Atlântida desapareceu. Muitos convidados foram interrogados mas apenas dois deles deram pistas valiosas. Um deles é um ator muito famoso. A outra é uma mulher que trabalha como consultora de uma grande empresa e seu primeiro nome termina com "an".'),
    (49, 19871030, 'Bill Baggs Cape Park', 'Historical lighthouse showed signs of vandalism. Park rangers reported suspicious activity.'),
    (50, 19871031, 'Haulover Park', 'Marina facilities reported equipment theft overnight. Security footage showed coordinated activity.'),
    (51, 19871030, 'North Shore Park', 'Beach facilities showed signs of vandalism. Staff found evidence of criminal activity.'),
    (52, 19871031, 'Surfside Community Center', 'Recreational equipment was stolen after hours. Security reported unauthorized access.'),
    (53, 19871030, 'Golden Beach Pavilion', 'Beach patrol reported vandalism overnight. Staff discovered evidence of organized crime.'),
    (54, 19871031, 'Sunny Isles Pier', 'Fishing equipment was stolen during night hours. Security cameras showed suspicious activity.'),
    (55, 19871030, 'Bal Harbour Beach Club', 'Private facilities reported sophisticated break-in. Staff found evidence of professional theft.'),
    (56, 19871031, 'Indian Creek Country Club', 'Golf equipment was stolen overnight. Security reported unauthorized vehicle access.'),
    (57, 19871030, 'Miami Shores Country Club', 'Club facilities showed signs of vandalism. Staff discovered evidence of coordinated activity.'),
    (58, 19871031, 'Normandy Shores Golf Club', 'Pro shop reported sophisticated burglary attempt. Security systems were professionally disabled.'),
    (59, 19871030, 'La Gorce Country Club', 'Tennis facilities reported equipment theft. Staff found evidence of organized crime.'),
    (60, 19871031, 'Riviera Country Club', 'Golf cart facility reported extensive theft. Security footage showed suspicious activity.'),
    (61, 19871030, 'Granada Golf Course', 'Maintenance equipment was stolen overnight. Staff reported unauthorized access.'),
    (62, 19871031, 'Biltmore Golf Course', 'Pro shop showed signs of sophisticated break-in. Security found evidence of professional theft.'),
    (63, 19871030, 'Miami Beach Golf Club', 'Club house reported vandalism after hours. Staff discovered signs of forced entry.'),
    (64, 19871031, 'Melreese Country Club', 'Golf equipment was stolen during night hours. Security reported suspicious vehicle movements.'),
    (65, 19871030, 'International Links Miami', 'Maintenance facility reported extensive theft. Staff found evidence of coordinated activity.'),
    (66, 19871031, 'Briar Bay Golf Course', 'Pro shop showed signs of attempted burglary. Security cameras captured suspicious activity.'),
    (67, 19871030, 'Palmetto Golf Course', 'Club facilities reported vandalism overnight. Staff discovered evidence of professional theft. The owner of the club was found dead in the back room. The security guard was found dead in the parking lot.'),
    (68, 19871031, 'Country Club of Miami', 'Tennis facilities showed signs of break-in. Security found unauthorized access evidence.'),
    (69, 19871030, 'California Club', 'Golf cart facility reported sophisticated theft. Staff reported suspicious group activity.'),
    (70, 19871031, 'Shulas Golf Club', 'Pro shop equipment was stolen after hours. Security footage showed coordinated activity.'),
    (71, 19871030, 'Miami National Golf Club', 'Maintenance equipment showed signs of theft. Staff found evidence of professional burglary.'),
    (72, 19871031, 'Killian Greens Golf Club', 'Club house reported vandalism overnight. Security discovered unauthorized access.'),
    (73, 19871030, 'Costa Del Sol Golf Club', 'Golf equipment was stolen during night hours. Staff reported suspicious vehicle movements.'),
    (74, 19871031, 'Keys Gate Golf Club', 'Pro shop showed signs of sophisticated break-in. Security found evidence of organized crime.'),
    (75, 19871031, 'Miami Mansion, Coconut Grove', 'During a masked ball, a body was found in the garden. Witnesses mentioned a hotel booking and suspicious phone activity.'),
    (76, 19871031, 'Coral Pine Golf Course', 'Club facilities showed signs of vandalism. Security reported suspicious activity.'),
    (77, 19871030, 'Miami Springs Golf Club', 'Golf cart facility reported sophisticated theft. Staff found evidence of professional burglary.'),
    (78, 19871031, 'Normandy Shores Club', 'Tennis equipment was stolen overnight. Security cameras showed suspicious activity.'),
    (79, 19871030, 'Fisher Island Club Course', 'Pro shop reported attempted break-in. Staff discovered evidence of coordinated activity.'),
    (80, 19871031, 'Deering Bay Yacht Club', 'Club facilities showed signs of vandalism. Security found unauthorized access evidence.'),
    (81, 19871030, 'Williams Island Club', 'Tennis facilities reported equipment theft. Staff reported suspicious group activity.'),
    (82, 19871031, 'Turnberry Isle Resort', 'Golf equipment was stolen after hours. Security footage showed coordinated activity.'),
    (83, 19871030, 'Doral Golf Resort', 'Maintenance facility reported extensive theft. Staff found evidence of professional theft. The owner of the facility was found dead in the back room. The security guard was found dead in the parking lot.'),
    (84, 19871031, 'Trump National Doral', 'Pro shop showed signs of sophisticated break-in. Security discovered unauthorized access.'),
    (85, 19871030, 'Blue Monster Course', 'Club house reported vandalism overnight. Staff reported suspicious vehicle movements.'),
    (86, 19871031, 'Silver Fox Course', 'Golf cart facility showed signs of theft. Security found evidence of organized crime.'),
    (87, 19871030, 'Golden Palm Course', 'Tennis equipment was stolen during night hours. Staff discovered signs of forced entry.'),
    (88, 19871031, 'Red Tiger Course', 'Maintenance facility reported sophisticated theft. Security reported suspicious activity.'),
    (89, 19871030, 'Great White Course', 'Pro shop showed signs of attempted burglary. Staff found evidence of professional theft.'),
    (90, 19871031, 'Jim McLean Golf School', 'Training equipment was stolen overnight. Security cameras showed suspicious activity.'),
    (91, 19871030, 'Miami Beach Golf Academy', 'Practice facility reported extensive theft. Staff discovered evidence of coordinated activity. The owner of the academy was found dead in the back room. The security guard was found dead in the parking lot.'),
    (92, 19871031, 'Don Shula Golf Academy', 'Training equipment showed signs of vandalism. Security found unauthorized access evidence.'),
    (93, 19871030, 'David Leadbetter Academy', 'Golf equipment was stolen after hours. Staff reported suspicious group activity.'),
    (94, 19871031, 'Rick Smith Golf Performance', 'Practice facility reported sophisticated theft. Security footage showed coordinated activity.'),
    (95, 19871030, 'Claude Harmon Golf School', 'Training equipment showed signs of break-in. Staff found evidence of professional burglary.'),
    (96, 19871031, 'Mitchell Spearman Academy', 'Practice facility reported vandalism overnight. Security discovered unauthorized access.'),
    (97, 19871030, 'Dave Pelz Golf School', 'Training equipment was stolen during night hours. Staff reported suspicious vehicle movements.'),
    (98, 19871031, 'Golf Institute Miami', 'Practice facility showed signs of sophisticated theft. Security found evidence of organized crime.'),
    (99, 19871030, 'Miami Golf Learning Center', 'Training equipment reported extensive vandalism. Staff discovered signs of forced entry.'),
    (100, 19871031, 'South Florida Golf Academy', 'Practice facility showed signs of attempted burglary. Security reported suspicious activity.')
  ;`,

  // 2. Guests
  `CREATE TABLE guest (
    id INTEGER PRIMARY KEY,
    name TEXT,
    occupation TEXT,
    invitation_code TEXT
  );`,
  `INSERT INTO guest (id, name, occupation, invitation_code) VALUES
    (1, 'Hristo Bogoev', 'Engenheiro', 'VIP-R'),
    (2, 'John Doe', 'Desenvolvedor de Software', 'VIP-R'),
    (3, 'James Bond', 'Espião', 'VIP-R'),
    (4, 'Marcus Chen', 'Desenvolvedor de Software', 'VIP-R'),
    (5, 'Isabella Rodriguez', 'Arquiteto', 'VIP-B'),
    (6, 'James Wilson', 'Doctor', 'VIP-G'),
    (7, 'Sofia Patel', 'Banqueira de Investimentos', 'VIP-R'),
    (8, 'Lucas Kim', 'Professor', 'VIP-B'),
    (9, 'Emma Thompson', 'Lawyer', 'VIP-G'),
    (10, 'Alexander Wang', 'CEO', 'VIP-R'),
    (11, 'Olivia Brown', 'Artist', 'VIP-B'),
    (12, 'William Davis', 'Entrepreneur', 'VIP-G'),
    (13, 'Ava Martinez', 'Cirurgião', 'VIP-R'),
    (14, 'Ethan Taylor', 'Financial Analyst', 'VIP-B'),
    (15, 'Sophia Lee', 'Marketing Director', 'VIP-G'),
    (16, 'Benjamin Garcia', 'Incorporador Imobiliário', 'VIP-R'),
    (17, 'Mia Anderson', 'Estilista', 'VIP-B'),
    (18, 'Daniel Murphy', 'Executive Chef', 'VIP-G'),
    (19, 'Charlotte Wong', 'Capitalista de Risco', 'VIP-R'),
    (20, 'Henry Johnson', 'Film Producer', 'VIP-B'),
    (21, 'Amelia Clark', 'Biotech Researcher', 'VIP-G'),
    (22, 'Sebastian Lewis', 'Produtor Musical', 'VIP-R'),
    (23, 'Victoria White', 'Dono de Galeria', 'VIP-B'),
    (24, 'Jack Robinson', 'Sports Agent', 'VIP-G'),
    (25, 'Zoe Campbell', 'Designer de Interiores', 'VIP-R'),
    (26, 'Oliver Scott', 'Hotel Manager', 'VIP-B'),
    (27, 'Luna Phillips', 'Tech Entrepreneur', 'VIP-G'),
    (28, 'Theodore Green', 'Dono de Restaurante', 'VIP-R'),
    (29, 'Grace Turner', 'Publishing Executive', 'VIP-B'),
    (30, 'Leo Mitchell', 'Gestor de Fundos', 'VIP-G'),
    (31, 'Aria Foster', 'Designer de Joias', 'VIP-R'),
    (32, 'Owen Ross', 'Diretor de Cinema', 'VIP-B'),
    (33, 'Scarlett Hayes', 'Art Curator', 'VIP-G'),
    (34, 'Felix Morgan', 'Engenheiro Aeroespacial', 'VIP-R'),
    (35, 'Chloe Bennett', 'Fashion Editor', 'VIP-B'),
    (36, 'Max Cooper', 'Consultora', 'VIP-G'),
    (37, 'Lily Stewart', 'Executiva de RP', 'VIP-R'),
    (38, 'Hugo Price', 'Wine Importer', 'VIP-B'),
    (39, 'Audrey Gray', 'Theater Director', 'VIP-G'),
    (40, 'Julian Wood', 'Dono de Equipe Esportiva', 'VIP-R'),
    (41, 'Hazel Reed', 'Filantropo', 'VIP-B'),
    (42, 'Oscar Kelly', 'University Dean', 'VIP-G'),
    (43, 'Ruby Baker', 'Ator', 'VIP-R'),
    (44, 'Arthur Collins', 'Investment Manager', 'VIP-B'),
    (45, 'Violet Ward', 'Museum Director', 'VIP-G'),
    (46, 'Miles Richardson', 'Produtor de Discos', 'VIP-R'),
    (47, 'Penelope Hughes', 'Magazine Editor', 'VIP-B'),
    (48, 'Caleb Morris', 'Real Estate Investor', 'VIP-G'),
    (49, 'Stella James', 'Negociante de Arte', 'VIP-R'),
    (50, 'Finn Russell', 'Startup Founder', 'VIP-B'),
    (51, 'Eleanor Brooks', 'Corporate Lawyer', 'VIP-G'),
    (52, 'Atlas Powell', 'Hotel Developer', 'VIP-R'),
    (53, 'Ivy Peterson', 'Fashion Consultant', 'VIP-B'),
    (54, 'Liam Henderson', 'Restaurant Critic', 'VIP-G'),
    (55, 'Nova Watson', 'Tech Investor', 'VIP-R'),
    (56, 'Jasper Cox', 'Theater Producer', 'VIP-B'),
    (57, 'Clara Howard', 'Gallery Director', 'VIP-G'),
    (58, 'Silas Butler', 'Luxury Car Dealer', 'VIP-R'),
    (59, 'Aurora Long', 'Event Planner', 'VIP-B'),
    (60, 'Roman Fisher', 'Nightclub Owner', 'VIP-G'),
    (61, 'Delilah Marshall', 'Fashion Photographer', 'VIP-R'),
    (62, 'Kai Barnes', 'Sports Manager', 'VIP-B'),
    (63, 'Iris Fleming', 'Interior Architect', 'VIP-G'),
    (64, 'Apollo Grant', 'Film Investor', 'VIP-R'),
    (65, 'Eden Shaw', 'Jewelry Collector', 'VIP-B'),
    (66, 'River Harrison', 'Music Executive', 'VIP-G'),
    (67, 'Thea Gibson', 'Art Collector', 'VIP-R'),
    (68, 'Atlas Wallace', 'Property Developer', 'VIP-B'),
    (69, 'Sage Johnston', 'Estilista', 'VIP-G'),
    (70, 'Phoenix Ellis', 'Tech CEO', 'VIP-R'),
    (71, 'Willow Stevens', 'Publishing Director', 'VIP-B'),
    (72, 'Orion Chapman', 'Banqueira de Investimentos', 'VIP-G'),
    (73, 'Luna West', 'Art Gallery Owner', 'VIP-R'),
    (74, 'Atlas Hunt', 'Capitalista de Risco', 'VIP-B'),
    (75, 'Aurora Palmer', 'Fashion Editor', 'VIP-G'),
    (76, 'Kai Spencer', 'Real Estate Mogul', 'VIP-R'),
    (77, 'Nova Ferguson', 'Theater Owner', 'VIP-B'),
    (78, 'Phoenix Mason', 'Tech Entrepreneur', 'VIP-G'),
    (79, 'Eden Tucker', 'Film Producer', 'VIP-R'),
    (80, 'River Wells', 'Hotel Chain Owner', 'VIP-B'),
    (81, 'Sage Crawford', 'Art Director', 'VIP-G'),
    (82, 'Atlas Bradley', 'Investment Manager', 'VIP-R'),
    (83, 'Luna Griffin', 'Fashion House Owner', 'VIP-B'),
    (84, 'Phoenix McDonald', 'Tech Investor', 'VIP-G'),
    (85, 'Eden Carroll', 'Gallery Curator', 'VIP-R'),
    (86, 'River Hopkins', 'Dono de Restaurante', 'VIP-B'),
    (87, 'Sage Hawkins', 'Designer de Joias', 'VIP-G'),
    (88, 'Atlas Perkins', 'Property Investor', 'VIP-R'),
    (89, 'Luna Matthews', 'Fashion Consultant', 'VIP-B'),
    (90, 'Phoenix Morrison', 'Tech Executive', 'VIP-G'),
    (91, 'Eden Robertson', 'Art Collector', 'VIP-R'),
    (92, 'River Kennedy', 'Hotel Developer', 'VIP-B'),
    (93, 'Sage Lawrence', 'Theater Producer', 'VIP-G'),
    (94, 'Atlas Dixon', 'Banqueira de Investimentos', 'VIP-R'),
    (95, 'Luna Ramos', 'Dono de Galeria', 'VIP-B'),
    (96, 'Phoenix Boyd', 'Tech Founder', 'VIP-G'),
    (97, 'Eden Cole', 'Estilista', 'VIP-R'),
    (98, 'River Fox', 'Incorporador Imobiliário', 'VIP-B'),
    (99, 'Sage Warren', 'Negociante de Arte', 'VIP-G'),
    (100, 'Atlas Holmes', 'Capitalista de Risco', 'VIP-R'),
    (101, 'Luna Reeves', 'Fashion Buyer', 'VIP-B'),
    (102, 'Phoenix Lloyd', 'Tech Director', 'VIP-G'),
    (103, 'Eden Walsh', 'Art Curator', 'VIP-R'),
    (104, 'River Santos', 'Hotel Manager', 'VIP-B'),
    (105, 'Mike Manning', 'Especialista em Realocação de Patrimônio', 'VIP-R'),
    (106, 'Atlas Ortiz', 'Investment Advisor', 'VIP-R'),
    (107, 'Luna Delgado', 'Gallery Manager', 'VIP-B'),
    (108, 'Phoenix Barton', 'Consultora', 'VIP-G'),
    (109, 'Eden Cruz', 'Fashion Buyer', 'VIP-R'),
    (110, 'River Mendoza', 'Real Estate Agent', 'VIP-B'),
    (111, 'Sage Zimmerman', 'Negociante de Arte', 'VIP-G'),
    (112, 'Atlas Owens', 'Venture Partner', 'VIP-G'),
    (113, 'Luna Watts', 'Fashion Editor', 'VIP-B'),
    (114, 'Phoenix Klein', 'Tech Advisor', 'VIP-G'),
    (115, 'Eden Burgess', 'Gallery Director', 'VIP-R'),
    (116, 'Vivian Nair', 'Consultora', 'VIP-R'),
    (117, 'Sage Daniels', 'Theater Manager', 'VIP-G'),
    (118, 'Atlas Guerrero', 'Investment Director', 'VIP-R'),
    (119, 'Luna Chandler', 'Fashion Consultant', 'VIP-B'),
    (120, 'Phoenix Barker', 'Tech Manager', 'VIP-G'),
    (121, 'Eden Norris', 'Art Collector', 'VIP-R'),
    (122, 'River Quinn', 'Property Manager', 'VIP-B'),
    (123, 'Sage Vaughn', 'Theater Producer', 'VIP-G'),
    (124, 'Atlas Poole', 'Banqueira de Investimentos', 'VIP-R'),
    (125, 'Luna Wolfe', 'Dono de Galeria', 'VIP-B'),
    (126, 'Phoenix Shields', 'Tech Executive', 'VIP-G'),
    (127, 'Eden Pearson', 'Estilista', 'VIP-R'),
    (128, 'River Dawson', 'Real Estate Broker', 'VIP-B'),
    (129, 'Clint Eastwood', 'Ator', 'VIP-G'),
    (130, 'Atlas Malone', 'Capitalista de Risco', 'VIP-R'),
    (131, 'Luna Rojas', 'Fashion Buyer', 'VIP-B'),
    (132, 'Phoenix Gibbs', 'Tech Director', 'VIP-G'),
    (133, 'Eden Ballard', 'Gallery Manager', 'VIP-R'),
    (134, 'River Vega', 'Hotel Developer', 'VIP-B'),
    (135, 'Sage Russo', 'Consultora', 'VIP-G'),
    (136, 'Atlas Wise', 'Investment Advisor', 'VIP-R'),
    (137, 'Luna Kirby', 'Fashion Editor', 'VIP-B'),
    (138, 'Phoenix Sandoval', 'Consultora', 'VIP-G'),
    (139, 'Eden Huff', 'Negociante de Arte', 'VIP-R'),
    (140, 'River Frost', 'Property Developer', 'VIP-B'),
    (141, 'Sage Morse', 'Theater Producer', 'VIP-G'),
    (142, 'Atlas Whitehead', 'Investment Director', 'VIP-R'),
    (143, 'Luna Bullock', 'Dono de Galeria', 'VIP-B'),
    (144, 'Phoenix Rich', 'Tech Manager', 'VIP-G'),
    (145, 'Eden Todd', 'Fashion Consultant', 'VIP-G'),
    (146, 'River Glass', 'Hotel Executive', 'VIP-B'),
    (147, 'Sage Hendricks', 'Art Curator', 'VIP-G'),
    (148, 'Atlas Cummings', 'Venture Partner', 'VIP-R'),
    (149, 'Luna Hutchinson', 'Estilista', 'VIP-B'),
    (150, 'Phoenix Golden', 'Tech Executive', 'VIP-G'),
    (151, 'Eden Skinner', 'Gallery Director', 'VIP-R'),
    (152, 'River Wilkinson', 'Real Estate Agent', 'VIP-B'),
    (153, 'Sage Pruitt', 'Theater Manager', 'VIP-G'),
    (154, 'Atlas Hogan', 'Banqueira de Investimentos', 'VIP-R'),
    (155, 'Luna Conley', 'Consultora', 'VIP-B'),
    (156, 'Phoenix Velazquez', 'Tech Director', 'VIP-G'),
    (157, 'Eden Combs', 'Art Collector', 'VIP-R'),
    (158, 'River Hood', 'Hotel Manager', 'VIP-B'),
    (159, 'Sage Kaufman', 'Theater Producer', 'VIP-G'),
    (160, 'Atlas Dudley', 'Investment Advisor', 'VIP-R'),
    (161, 'Luna Horne', 'Gallery Manager', 'VIP-B'),
    (162, 'Phoenix Farley', 'Consultora', 'VIP-G'),
    (163, 'Eden Lowery', 'Fashion Editor', 'VIP-R'),
    (164, 'River Bowers', 'Ator', 'VIP-B'),
    (165, 'Sage Phelps', 'Negociante de Arte', 'VIP-G'),
    (166, 'Atlas Crane', 'Capitalista de Risco', 'VIP-R'),
    (167, 'Luna Dalton', 'Estilista', 'VIP-B'),
    (168, 'Phoenix Browning', 'Tech Executive', 'VIP-G'),
    (169, 'Eden Shepherd', 'Dono de Galeria', 'VIP-R'),
    (170, 'River Griffith', 'Hotel Developer', 'VIP-B'),
    (171, 'Sage Merritt', 'Theater Director', 'VIP-G'),
    (172, 'Atlas Chaney', 'Investment Director', 'VIP-R'),
    (173, 'Luna Odom', 'Fashion Consultant', 'VIP-B'),
    (174, 'Phoenix Hendrix', 'Tech Manager', 'VIP-G'),
    (175, 'Eden Stark', 'Art Curator', 'VIP-R'),
    (176, 'River Meyers', 'Real Estate Broker', 'VIP-B'),
    (177, 'Sage Sloan', 'Theater Producer', 'VIP-G'),
    (178, 'Atlas Hinton', 'Banqueira de Investimentos', 'VIP-R'),
    (179, 'Luna Terrell', 'Fashion Buyer', 'VIP-B'),
    (180, 'Phoenix Riggs', 'Tech Director', 'VIP-G'),
    (181, 'Eden Hess', 'Gallery Manager', 'VIP-R'),
    (182, 'River Weeks', 'Hotel Executive', 'VIP-B'),
    (183, 'Sage Wilcox', 'Negociante de Arte', 'VIP-G'),
    (184, 'Atlas Melton', 'Venture Partner', 'VIP-R'),
    (185, 'Luna Gilmore', 'Fashion Editor', 'VIP-B'),
    (186, 'Phoenix Kinney', 'Consultora', 'VIP-G'),
    (187, 'Eden Whitaker', 'Gallery Director', 'VIP-R'),
    (188, 'River Madden', 'Property Manager', 'VIP-B'),
    (189, 'Sage Dillon', 'Ator', 'VIP-G'),
    (190, 'Atlas Roach', 'Investment Advisor', 'VIP-B'),
    (191, 'Luna Blanchard', 'Estilista', 'VIP-B'),
    (192, 'Phoenix Pitts', 'Ator', 'VIP-G'),
    (193, 'Eden McCall', 'Art Collector', 'VIP-R'),
    (194, 'River Marsh', 'Hotel Developer', 'VIP-B'),
    (195, 'Sage Lindsey', 'Theater Producer', 'VIP-G'),
    (196, 'Atlas Thorton', 'Investment Director', 'VIP-R'),
    (197, 'Luna Graves', 'Fashion Consultant', 'VIP-B'),
    (198, 'Phoenix Savage', 'Tech Manager', 'VIP-G'),
    (199, 'Eden Meadows', 'Dono de Galeria', 'VIP-R'),
    (200, 'River Frost', 'Real Estate Agent', 'VIP-B')
  ;`,

  // 3. Witness Statements
  `CREATE TABLE witness_statements (
    id INTEGER PRIMARY KEY,
    guest_id INTEGER,
    clue TEXT,
    FOREIGN KEY (guest_id) REFERENCES guest(id)
  );`,
  `INSERT INTO witness_statements (id, guest_id, clue) VALUES
    (1, 123, 'I was walking my dog when I saw someone suspicious climbing through the window of the research greenhouse late at night.'),
    (2, 45, 'While working the late shift, I distinctly heard the sound of breaking glass coming from the east wing of the building.'),
    (3, 167, 'During my evening jog, I noticed a black van parked outside with its lights off for over two hours.'),
    (4, 23, 'I remember smelling something burning around midnight, which seemed very unusual for that time.'),
    (5, 91, 'As I was closing up shop, I saw three people in dark clothes running from the back entrance.'),
    (6, 34, 'From my apartment window, I watched someone tampering with the security cameras using some kind of tool.'),
    (7, 67, 'During my security rounds, I heard loud banging noises coming from the storage area around 2 AM.'),
    (8, 89, 'I spotted a person wearing a maintenance uniform at an odd hour when no maintenance was scheduled.'),
    (9, 12, 'While walking home, I saw someone throwing what looked like documents into a dumpster behind the building.'),
    (10, 56, 'I heard an alarm going off briefly before it was suddenly silenced in an unusual way.'),
    (11, 78, 'From my balcony, I observed someone picking the lock on the side entrance using professional tools.'),
    (12, 34, 'During my night shift, I noticed the security cameras were showing looped footage of empty hallways.'),
    (13, 90, 'I saw a group of people loading large crates into a white truck around midnight.'),
    (14, 23, 'While closing up the cafe across the street, I witnessed someone disabling the exterior lights systematically.'),
    (15, 45, 'I heard what sounded like power tools being used inside the building well past closing time.'),
    (16, 116, 'Vi alguém segurando um convite terminando com "-R". Ele usava um terno azul-marinho e uma gravata branca.'),
    (17, 89, 'I noticed the alarm system was already disabled when I arrived for my morning shift at 5 AM.'),
    (18, 12, 'During my evening walk, I saw multiple flashlights moving around inside the closed building.'),
    (19, 34, 'I remember hearing a heated argument in a foreign language coming from the parking garage.'),
    (20, 56, 'While delivering packages, I noticed the side door had fresh scratch marks around the lock.'),
    (21, 78, 'I saw someone repeatedly taking photos of the buildings security camera locations earlier that day.'),
    (22, 90, 'During my shift at the coffee shop, I overheard someone discussing detailed plans of the buildings layout.'),
    (23, 23, 'I noticed a ladder propped against the back wall near the second-floor window around dusk.'),
    (24, 45, 'From my taxi, I saw someone wearing a ski mask despite the warm weather entering the building.'),
    (25, 67, 'I heard the sound of glass breaking followed by quick footsteps around 1 AM.'),
    (26, 89, 'While walking my dog, I noticed unfamiliar vehicles parked in the staff-only area.'),
    (27, 12, 'I saw someone copying what looked like security codes near the entrance keypad.'),
    (28, 34, 'During my night patrol, I found fresh tire tracks leading to the normally unused loading dock.'),
    (29, 56, 'I witnessed someone in a delivery uniform but the company logo looked obviously fake.'),
    (30, 78, 'From my window, I saw people loading artwork into an unmarked van at 3 AM.'),
    (31, 90, 'I noticed the security lights were deliberately covered with some kind of dark material.'),
    (32, 23, 'While cleaning the windows, I saw someone testing different keys on the back entrance.'),
    (33, 45, 'I heard unusual drilling sounds coming from the vault area after hours.'),
    (34, 67, 'During my evening run, I saw multiple people wearing identical outfits entering through different doors.'),
    (35, 89, 'I noticed someone taking detailed notes while observing the guard rotation schedule.'),
    (36, 12, 'From my desk, I saw a person in a maintenance uniform but they seemed unfamiliar with the basic layout.'),
    (37, 34, 'I heard what sounded like radio communications in code coming from the parking structure.'),
    (38, 56, 'While delivering mail, I noticed the security panel had been recently tampered with.'),
    (39, 78, 'I saw someone photographing the employee entrance during shift changes.'),
    (40, 90, 'During my break, I noticed a suspicious person monitoring the security patrol patterns.'),
    (41, 23, 'I observed someone attempting to access the roof through the fire escape.'),
    (42, 45, 'From my apartment, I saw flashlights moving through the building long after closing.'),
    (43, 67, 'I heard the sound of spray paint cans being used inside the closed gallery.'),
    (44, 89, 'While closing up, I noticed someone had propped open several emergency exits.'),
    (45, 12, 'I saw a group of people wearing masks entering through the service entrance.'),
    (46, 34, 'During my shift, I noticed the security cameras were being systematically redirected.'),
    (47, 56, 'I heard unusual beeping sounds coming from the alarm control panel.'),
    (48, 78, 'From the parking lot, I saw someone copying down the security patrol schedule.'),
    (49, 90, 'I noticed fresh damage to the lock on the rear storage entrance.'),
    (50, 129, 'Ouvi alguém dizer, "Me encontre na marina, doca 3.'),
    (51, 45, 'I observed someone using sophisticated equipment to bypass the card readers.'),
    (52, 67, 'During my patrol, I found evidence of someone monitoring the security camera feeds.'),
    (53, 89, 'I saw unusual activity near the ventilation system access points.'),
    (54, 12, 'From my office, I noticed someone attempting to access restricted areas repeatedly.'),
    (55, 34, 'I heard power tools being used in the artifact storage area after hours.'),
    (56, 56, 'While cleaning, I found discarded professional lock-picking tools.'),
    (57, 78, 'I observed multiple people communicating via hand signals near the entrance.'),
    (58, 90, 'During my shift, I noticed the emergency exits had been tampered with.'),
    (59, 23, 'I saw someone in a fake security uniform inspecting the alarm systems.'),
    (60, 45, 'From the street, I noticed unusual activity on the normally empty top floor.'),
    (61, 67, 'I heard what sounded like heavy equipment being moved late at night.'),
    (62, 89, 'While passing by, I saw someone disabling the external security lights.'),
    (63, 12, 'I noticed a suspicious gathering in the parking garage after hours.'),
    (64, 34, 'During my rounds, I found evidence of someone monitoring staff movements.'),
    (65, 56, 'I observed multiple people wearing identical disguises entering separately.'),
    (66, 78, 'From my window, I saw someone testing the response time of the security system.'),
    (67, 90, 'I noticed unusual marks around the ventilation system access panels.'),
    (68, 23, 'While working late, I heard strange noises coming from the sealed exhibits.'),
    (69, 45, 'I saw someone attempting to access the security control room repeatedly.'),
    (70, 67, 'During my shift, I found evidence of surveillance equipment being installed.'),
    (71, 89, 'I observed someone taking detailed photos of the security measures.'),
    (72, 12, 'From the adjacent building, I saw unusual activity in the restricted areas.'),
    (73, 34, 'I noticed someone attempting to clone security access cards.'),
    (74, 56, 'While on patrol, I found tools used for bypassing electronic locks.'),
    (75, 78, 'I heard coded radio communications coming from multiple directions.'),
    (76, 90, 'During my break, I saw someone mapping out the camera blind spots.'),
    (77, 23, 'I observed multiple people coordinating through hidden earpieces.'),
    (78, 45, 'From my post, I noticed someone timing the security patrol intervals.'),
    (79, 67, 'I saw unusual vehicle movements near the service entrance.'),
    (80, 89, 'While closing, I found evidence of someone accessing restricted files.'),
    (81, 12, 'I heard what sounded like professional cutting tools being used.'),
    (82, 34, 'During my shift, I noticed the surveillance system had been compromised.'),
    (83, 75, 'I overheard a booking at The Grand Regency.'),
    (84, 78, 'From the street, I saw multiple people wearing service uniforms after hours.'),
    (85, 90, 'I noticed unusual activity around the emergency exit stairwells.'),
    (86, 23, 'While working, I found evidence of systematic security breaches.'),
    (87, 45, 'I heard unusual mechanical sounds coming from the secured storage area.'),
    (88, 67, 'During my rounds, I saw someone tampering with the access control system.'),
    (89, 75, 'I noticed someone at the front desk discussing Room 707 for a reservation made yesterday.'),
    (90, 12, 'From my position, I noticed someone disabling security sensors systematically.'),
    (91, 34, 'I saw unusual patterns of movement near the restricted areas.'),
    (92, 56, 'While patrolling, I found sophisticated hacking equipment hidden nearby.'),
    (93, 78, 'I heard what sounded like professional tools being used on the locks.'),
    (94, 90, 'During my shift, I noticed someone monitoring the staff rotations.'),
    (95, 23, 'I observed multiple people using fake identification badges.'),
    (96, 45, 'From the parking lot, I saw someone installing unknown devices near cameras.'),
    (97, 67, 'I noticed unusual activity in typically restricted areas of the building.'),
    (98, 89, 'While working, I found evidence of coordinated security system tampering.'),
    (99, 12, 'I heard encrypted radio communications from multiple locations.'),
    (100, 34, 'During my patrol, I observed someone bypassing the biometric scanners.')
  ;`,

  // 4. Attire Registry
  `CREATE TABLE attire_registry (
    id INTEGER PRIMARY KEY,
    guest_id INTEGER,
    note TEXT,
    FOREIGN KEY (guest_id) REFERENCES guest(id)
  );`,
  `INSERT INTO attire_registry (id, guest_id, note) VALUES
    (1, 1, 'black tuxedo, emerald cufflinks'),
    (2, 2, 'terno azul-marinho, gravata vermelha'),
    (3, 3, 'red gown, diamond necklace'),
    (4, 4, 'terno azul-marinho, gravata azul'),
    (5, 156, 'purple evening gown, sapphire earrings'),
    (6, 23, 'terno azul-marinho, gravata verde'),
    (7, 189, 'black velvet dress, gold bracelet'),
    (8, 45, 'terno azul-marinho, gravata amarela'),
    (9, 167, 'emerald gown, diamond choker'),
    (10, 34, 'terno azul-marinho, gravata roxa'),
    (11, 178, 'blue silk dress, pearl necklace'),
    (12, 12, 'terno azul-marinho, gravata laranja'),
    (13, 190, 'red sequin gown, ruby earrings'),
    (14, 87, 'terno azul-marinho, gravata bordô'),
    (15, 145, 'terno azul-marinho, gravata prateada'),
    (16, 89, 'terno azul-marinho, gravata dourada'),
    (17, 112, 'gold evening gown, topaz necklace'),
    (18, 167, 'terno azul-marinho, gravata carmesim'),
    (19, 134, 'silver cocktail dress, diamond bracelet'),
    (20, 178, 'terno azul-marinho, gravata marinho'),
    (21, 156, 'champagne gown, crystal earrings'),
    (22, 190, 'terno azul-marinho, gravata vinho'),
    (23, 123, 'maroon velvet dress, gold choker'),
    (24, 145, 'terno azul-marinho, gravata azul-petróleo'),
    (25, 189, 'navy evening gown, sapphire pendant'),
    (26, 112, 'terno azul-marinho, gravata preta'),
    (27, 167, 'burgundy dress, diamond drop earrings'),
    (28, 134, 'terno azul-marinho, gravata esmeralda'),
    (29, 178, 'emerald silk gown, crystal bracelet'),
    (30, 156, 'terno azul-marinho, gravata branca'),
    (31, 190, 'red velvet dress, pearl choker'),
    (32, 123, 'terno azul-marinho, gravata cinza'),
    (33, 145, 'silver gown, emerald earrings'),
    (34, 189, 'terno azul-marinho, gravata marrom'),
    (35, 112, 'purple silk dress, sapphire bracelet'),
    (36, 167, 'terno azul-marinho, gravata coral'),
    (37, 134, 'black lace gown, ruby necklace'),
    (38, 178, 'burgundy suit, gravata pérola clip'),
    (39, 156, 'gold cocktail dress, diamond pendant'),
    (40, 190, 'charcoal tuxedo, emerald studs'),
    (41, 123, 'blue evening gown, topaz earrings'),
    (42, 145, 'terno azul-marinho, gravata branca'),
    (43, 189, 'red silk dress, crystal choker'),
    (44, 112, 'terno azul-marinho, gravata ônix pin'),
    (45, 167, 'emerald velvet gown, pearl bracelet'),
    (46, 134, 'grey tuxedo, diamond cufflinks'),
    (47, 178, 'champagne dress, ruby pendant'),
    (48, 105, 'terno azul-marinho, gravata branca'),
    (49, 190, 'maroon evening gown, emerald necklace'),
    (50, 123, 'black tuxedo, crystal tie clip'),
    (51, 145, 'silver silk dress, sapphire choker'),
    (52, 189, 'navy pinstripe suit, gravata pérola pin'),
    (53, 112, 'terno azul-marinho, gravata branca'),
    (54, 167, 'charcoal suit, ruby cufflinks'),
    (55, 134, 'burgundy velvet dress, onyx pendant'),
    (56, 178, 'cream tuxedo, emerald studs'),
    (57, 156, 'black lace gown, gold earrings'),
    (58, 190, 'terno azul-marinho, gravata branca'),
    (59, 123, 'blue cocktail dress, pearl necklace'),
    (60, 145, 'white suit, sapphire cufflinks'),
    (61, 189, 'terno azul-marinho, gravata branca'),
    (62, 112, 'navy tuxedo, gravata topázio pin'),
    (63, 167, 'terno azul-marinho, gravata branca'),
    (64, 134, 'black pinstripe suit, pearl studs'),
    (65, 178, 'gold velvet gown, crystal pendant'),
    (66, 156, 'burgundy suit, emerald cufflinks'),
    (67, 190, 'terno azul-marinho, gravata branca'),
    (68, 123, 'charcoal tuxedo, diamond tie clip'),
    (69, 145, 'champagne silk gown, sapphire earrings'),
    (70, 189, 'black velvet dress, pearl bracelet'),
    (71, 112, 'terno azul-marinho, ruby cufflinks'),
    (72, 167, 'red lace gown, crystal choker'),
    (73, 134, 'grey pinstripe suit, gravata esmeralda pin'),
    (74, 178, 'purple evening gown, diamond pendant'),
    (75, 129, 'black tuxedo, patent leather dress shoes'),
    (76, 190, 'emerald velvet dress, gold earrings'),
    (77, 123, 'burgundy suit, sapphire cufflinks'),
    (78, 145, 'blue silk gown, pearl necklace'),
    (79, 189, 'charcoal tuxedo, crystal tie clip'),
    (80, 112, 'silver cocktail dress, ruby bracelet'),
    (81, 167, 'black suit, diamond studs'),
    (82, 134, 'maroon evening gown, emerald choker'),
    (83, 178, 'navy pinstripe suit, topaz cufflinks'),
    (84, 156, 'gold lace dress, pearl pendant'),
    (85, 190, 'grey tuxedo, gravata safira pin'),
    (86, 123, 'cream silk gown, onyx bracelet'),
    (87, 145, 'burgundy velvet suit, crystal studs'),
    (88, 189, 'black dress, ruby necklace'),
    (89, 112, 'emerald tuxedo, diamond cufflinks'),
    (90, 167, 'purple silk dress, gold choker'),
    (91, 134, 'white suit, gravata pérola clip'),
    (92, 178, 'red evening gown, sapphire pendant'),
    (93, 156, 'navy velvet tuxedo, emerald studs'),
    (94, 190, 'charcoal dress, crystal bracelet'),
    (95, 123, 'silver suit, ruby cufflinks'),
    (96, 145, 'black lace gown, diamond earrings'),
    (97, 189, 'burgundy pinstripe suit, gravata ônix pin'),
    (98, 116, 'blue velvet dress, pearl choker'),
    (99, 167, 'grey tuxedo, gold studs'),
    (100, 134, 'emerald silk gown, sapphire necklace'),
    (101, 178, 'white suit, crystal cufflinks'),
    (102, 156, 'red lace dress, diamond pendant'),
    (103, 190, 'navy tuxedo, gravata esmeralda clip'),
    (104, 123, 'purple evening gown, pearl bracelet')
  ;`,

  // 5. Marina Rentals
  `CREATE TABLE marina_rentals (
      id INTEGER PRIMARY KEY,
      dock_number INTEGER,
      renter_guest_id INTEGER,
      rental_date INTEGER,
      boat_name TEXT,
      FOREIGN KEY (renter_guest_id) REFERENCES guest(id)
    );`,
  `INSERT INTO marina_rentals (id, dock_number, renter_guest_id, rental_date, boat_name) VALUES
    (1, 4, 156, 19871025, 'Sea Whisper'),
    (2, 2, 89, 19871027, 'Ocean Breeze'),
    (3, 1, 134, 19871028, 'Wave Dancer'),
    (4, 3, 45, 19870520, 'Coastal Dream'),
    (5, 5, 178, 19871026, 'Marina Belle'),
    (6, 2, 23, 19871029, 'Blue Horizon'),
    (7, 4, 167, 19871025, 'Sunset Chaser'),
    (8, 1, 91, 19871027, 'Wind Spirit'),
    (9, 3, 112, 19870520, 'Sea Serenade'),
    (10, 5, 145, 19871026, 'Ocean Mist'),
    (11, 2, 89, 19871029, 'Wave Runner'),
    (12, 4, 34, 19871025, 'Coastal Jewel'),
    (13, 1, 167, 19871027, 'Marina Star'),
    (14, 3, 78, 19870520, 'Blue Pearl'),
    (15, 5, 123, 19871026, 'Sunset Dream'),
    (16, 2, 45, 19871029, 'Wind Dancer'),
    (17, 4, 190, 19871025, 'Sea Princess'),
    (18, 1, 56, 19871027, 'Ocean Spray'),
    (19, 3, 145, 19870520, 'Wave Seeker'),
    (20, 5, 89, 19871026, 'Coastal Beauty'),
    (21, 2, 112, 19871029, 'Marina Mist'),
    (22, 4, 78, 19871025, 'Blue Wave'),
    (23, 1, 23, 19871027, 'Sunset Lady'),
    (24, 3, 167, 19870520, 'Wind Song'),
    (25, 5, 34, 19871026, 'Sea Breeze'),
    (26, 2, 156, 19871029, 'Ocean Dream'),
    (27, 4, 91, 19871025, 'Wave Spirit'),
    (28, 1, 145, 19871027, 'Coastal Star'),
    (29, 3, 78, 19870520, 'Marina Belle II'),
    (30, 5, 112, 19871026, 'Blue Moon'),
    (31, 2, 34, 19871029, 'Sunset Wave'),
    (32, 4, 167, 19871025, 'Wind Seeker'),
    (33, 1, 23, 19871027, 'Sea Pearl'),
    (34, 3, 190, 19870520, 'Ocean Spirit'),
    (35, 5, 56, 19871026, 'Wave Princess'),
    (36, 2, 145, 19871029, 'Coastal Spray'),
    (37, 4, 89, 19871025, 'Marina Dream'),
    (38, 1, 112, 19871027, 'Blue Lady'),
    (39, 3, 78, 19870520, 'Sunset Mist'),
    (40, 5, 167, 19871026, 'Wind Star'),
    (41, 2, 34, 19871029, 'Sea Song'),
    (42, 4, 156, 19871025, 'Ocean Beauty'),
    (43, 1, 91, 19871027, 'Wave Moon'),
    (44, 3, 105, 19870520, 'Coastal Spirit'),
    (45, 5, 23, 19871026, 'Marina Wave'),
    (46, 2, 78, 19871029, 'Blue Seeker'),
    (47, 4, 112, 19871025, 'Sunset Pearl'),
    (48, 1, 167, 19871027, 'Wind Princess'),
    (49, 3, 34, 19870520, 'Sea Spray'),
    (50, 5, 190, 19871026, 'Ocean Lady'),
    (51, 2, 56, 19871029, 'Wave Star'),
    (52, 4, 145, 19871025, 'Coastal Mist'),
    (53, 1, 89, 19871027, 'Marina Moon'),
    (54, 3, 112, 19871028, 'Blue Spirit'),
    (55, 5, 78, 19871026, 'Sunset Beauty'),
    (56, 2, 167, 19871029, 'Wind Wave'),
    (57, 4, 34, 19871025, 'Sea Seeker'),
    (58, 1, 156, 19871027, 'Ocean Pearl'),
    (59, 3, 91, 19871028, 'Wave Lady'),
    (60, 5, 145, 19871026, 'Coastal Star II'),
    (61, 2, 23, 19871029, 'Marina Spirit'),
    (62, 4, 78, 19871025, 'Blue Princess'),
    (63, 1, 112, 19871027, 'Sunset Spray'),
    (64, 3, 167, 19871028, 'Wind Moon'),
    (65, 5, 34, 19871026, 'Sea Star'),
    (66, 2, 190, 19871029, 'Ocean Mist II'),
    (67, 4, 56, 19871025, 'Wave Beauty'),
    (68, 1, 145, 19871027, 'Coastal Wave'),
    (69, 3, 89, 19871028, 'Marina Seeker'),
    (70, 5, 112, 19871026, 'Blue Pearl II'),
    (71, 2, 78, 19871029, 'Sunset Spirit'),
    (72, 4, 167, 19871025, 'Wind Lady'),
    (73, 1, 34, 19871027, 'Sea Moon'),
    (74, 3, 156, 19871028, 'Ocean Star II'),
    (75, 5, 91, 19871026, 'Wave Spirit II'),
    (76, 2, 145, 19871029, 'Coastal Princess'),
    (77, 4, 23, 19871025, 'Marina Spray'),
    (78, 1, 78, 19871027, 'Blue Mist'),
    (79, 3, 112, 19871028, 'Sunset Wave II'),
    (80, 5, 167, 19871026, 'Wind Beauty'),
    (81, 2, 34, 19871029, 'Sea Princess II'),
    (82, 4, 190, 19871025, 'Ocean Spirit II'),
    (83, 1, 56, 19871027, 'Wave Seeker II'),
    (84, 3, 145, 19871028, 'Coastal Lady'),
    (85, 5, 89, 19871026, 'Marina Pearl'),
    (86, 2, 112, 19871029, 'Blue Star'),
    (87, 4, 78, 19871025, 'Sunset Moon'),
    (88, 1, 167, 19871027, 'Wind Spirit II'),
    (89, 3, 34, 19871028, 'Sea Beauty'),
    (90, 5, 156, 19871026, 'Ocean Wave'),
    (91, 2, 91, 19871029, 'Wave Pearl'),
    (92, 4, 145, 19871025, 'Coastal Spirit II'),
    (93, 1, 23, 19871027, 'Marina Star II'),
    (94, 3, 78, 19871028, 'Blue Moon II'),
    (95, 5, 112, 19871026, 'Sunset Seeker'),
    (96, 2, 167, 19871029, 'Wind Wave II'),
    (97, 4, 34, 19871025, 'Sea Spirit II'),
    (98, 1, 190, 19871027, 'Ocean Beauty II'),
    (99, 3, 56, 19871028, 'Wave Star II'),
    (100, 5, 145, 19871026, 'Coastal Dream II')
    ;`,

  // 6. Final Interviews
  `CREATE TABLE final_interviews (
      id INTEGER PRIMARY KEY,
      guest_id INTEGER,
      confession TEXT,
      FOREIGN KEY (guest_id) REFERENCES guest(id)
    );`,
  `INSERT INTO final_interviews (id, guest_id, confession) VALUES
      (1, 1, 'I didnt kill anyone, I swear. Who would even think I could kill someone?'),
      (2, 2, 'Listen, I was at the gym that day. I would never kill another human being.'),
      (3, 3, 'My mother raised me better than that. I didnt kill anybody, period.'),
      (4, 4, 'What a ridiculous accusation! I couldnt kill even if I wanted to.'),
      (5, 5, 'Youve got the wrong person here. Im not someone who would kill.'),
      (6, 6, 'Check my alibi if you want. I didnt kill anyone that night.'),
      (7, 7, 'I was watching TV at home. How could I possibly kill someone?'),
      (8, 8, 'This is absurd! Ive never killed anything bigger than a spider.'),
      (9, 9, 'Do I look like someone who could kill? I faint at the sight of blood.'),
      (10, 10, 'Let me be clear about this. I did not kill that person.'),
      (11, 11, 'Im a peaceful person. I wouldnt kill anyone ever.'),
      (12, 12, 'Youre barking up the wrong tree. I didnt kill anybody.'),
      (13, 13, 'I was with my family that evening. I couldnt kill anyone even if I wanted to.'),
      (14, 14, 'This is a mistake. Im not the type of person who would kill.'),
      (15, 15, 'Ask my neighbors, I was home. I would never kill someone.'),
      (16, 16, 'Im innocent in all this. I didnt kill that person or anyone else.'),
      (17, 17, 'Look at my record, Im clean. Ive never tried to kill anyone.'),
      (18, 18, 'Youve got this all wrong. I wouldnt kill a fly.'),
      (19, 19, 'I was at work all day. How could I possibly kill someone?'),
      (20, 20, 'This is ridiculous! Im not capable of trying to kill anyone.'),
      (21, 21, 'Check the security cameras. I didnt kill anybody that day.'),
      (22, 22, 'Im a vegetarian for crying out loud. I wouldnt kill anyone!'),
      (23, 23, 'Youre making a huge mistake. Ive never tried to kill anyone.'),
      (24, 24, 'I was at the movies that night. I couldnt possibly kill someone.'),
      (25, 25, 'This is just wrong. Im not someone who would kill.'),
      (26, 26, 'I have witnesses who can vouch for me. I didnt kill anyone.'),
      (27, 27, 'My conscience is clear. I would never kill another person.'),
      (28, 28, 'Im a peace-loving citizen. I couldnt kill if I tried.'),
      (29, 29, 'This whole thing is crazy. Im not a person who would kill.'),
      (30, 30, 'I was out of town that week. How could I kill anyone?'),
      (31, 31, 'Youre way off base here. I didnt kill anybody.'),
      (32, 32, 'Im a healthcare worker. I save lives, I dont kill people.'),
      (33, 33, 'This is a complete misunderstanding. I would never kill anyone.'),
      (34, 34, 'I have an ironclad alibi. I didnt kill that person.'),
      (35, 35, 'Youre looking at the wrong person. I couldnt kill anyone.'),
      (36, 36, 'I was asleep at the time. How could I possibly kill someone?'),
      (37, 37, 'This is just not possible. Im not someone who would kill.'),
      (38, 38, 'Im a law-abiding citizen. I wouldnt kill anybody.'),
      (39, 39, 'Check my phone records. I didnt kill anyone that night.'),
      (40, 40, 'Im completely innocent. I would never kill another person.'),
      (41, 41, 'This is all wrong. I couldnt possibly kill someone.'),
      (42, 42, 'I have proof of where I was. I didnt kill anybody.'),
      (43, 43, 'Youve got the wrong person. Im not someone who would kill.'),
      (44, 44, 'I was at a party that evening. I couldnt possibly kill anyone.'),
      (45, 45, 'This is a mistake. I would never kill another human being.'),
      (46, 46, 'Im shocked by these accusations. I didnt kill anyone.'),
      (47, 47, 'Look at my background. Im not capable of trying to kill.'),
      (48, 48, 'I have an airtight alibi. I wouldnt kill anybody.'),
      (49, 49, 'This is completely false. I couldnt kill someone if I tried.'),
      (50, 50, 'I was with my kids that day. I would never kill anyone.'),
      (51, 51, 'Youre making a mistake. I didnt kill that person.'),
      (52, 52, 'Im a peaceful person. I couldnt possibly kill anyone.'),
      (53, 53, 'This is absurd! I would never kill another human being.'),
      (54, 54, 'I have witnesses. I didnt kill anybody that night.'),
      (55, 55, 'Youve got this wrong. Im not someone who would kill.'),
      (56, 56, 'I was at church that morning. I couldnt kill anyone.'),
      (57, 57, 'This is a huge misunderstanding. I would never kill.'),
      (58, 58, 'I didn’t kill Leo per se. I was just a middleman.'),
      (59, 59, 'Im innocent of this. I couldnt possibly kill someone.'),
      (60, 60, 'Youre barking up the wrong tree. I wouldnt kill anybody.'),
      (61, 61, 'I have a solid alibi. I didnt kill anyone that day.'),
      (62, 62, 'This is just wrong. Im not the type to kill.'),
      (63, 63, 'I was at the gym all evening. I couldnt possibly kill anyone.'),
      (64, 64, 'Youve got the wrong person. I would never kill.'),
      (65, 65, 'Im a gentle soul. I didnt kill anybody.'),
      (66, 66, 'This is ridiculous. I couldnt kill if I wanted to.'),
      (67, 67, 'I have proof of my whereabouts. Im not someone who would kill.'),
      (68, 68, 'Youre mistaken. I didnt kill that person.'),
      (69, 69, 'I was at a meeting then. I would never kill anyone.'),
      (70, 70, 'This is all wrong. I couldnt possibly kill somebody.'),
      (71, 71, 'Check the surveillance tapes. I didnt kill anybody.'),
      (72, 72, 'Im a pacifist. I wouldnt kill another living being.'),
      (73, 73, 'Youve got this all mixed up. I couldnt kill anyone.'),
      (74, 74, 'I was teaching a class then. I would never kill.'),
      (75, 75, 'This is a mistake. I didnt kill that person.'),
      (76, 76, 'I have people who can vouch for me. I couldnt possibly kill.'),
      (77, 77, 'Youre way off base. I wouldnt kill anybody.'),
      (78, 78, 'I was at the doctors office. I didnt kill anyone.'),
      (79, 79, 'This is completely wrong. Im not someone who would kill.'),
      (80, 80, 'I have documentation of where I was. I couldnt kill anyone.'),
      (81, 81, 'Youre mistaken about this. I would never kill.'),
      (82, 82, 'I was shopping at the time. I didnt kill anybody.'),
      (83, 83, 'This is false. I couldnt possibly kill someone.'),
      (84, 84, 'I have receipts to prove my location. Im not one to kill.'),
      (85, 85, 'Youve got the wrong person. I wouldnt kill anyone.'),
      (86, 86, 'I was at a concert that night. I didnt kill that person.'),
      (87, 87, 'This is just not true. I couldnt kill if I tried.'),
      (88, 88, 'I have video evidence of my whereabouts. I would never kill.'),
      (89, 89, 'Youre looking at the wrong suspect. I didnt kill anybody.'),
      (90, 90, 'I was visiting my parents. I couldnt possibly kill someone.'),
      (91, 91, 'This is a complete mistake. Im not someone who would kill.'),
      (92, 92, 'I have an alibi for that time. I wouldnt kill anyone.'),
      (93, 93, 'Youve got this wrong. I didnt kill that person.'),
      (94, 94, 'I was at a wedding that day. I couldnt kill anybody.'),
      (95, 95, 'This is absolutely false. I would never kill.'),
      (96, 96, 'I have witnesses to confirm my story. I didnt kill anyone.'),
      (97, 97, 'Eu ordenei o crime. Fui eu. Vocês me pegaram.'),
      (98, 98, 'I was at the library then. I wouldnt kill anybody.'),
      (99, 99, 'This is all incorrect. Im not someone who would kill.'),
      (100, 100, 'I have security footage to prove it. I didnt kill anyone.'),
      (101, 101, 'I was feeding pigeons in the park that day. Murder is against my principles.'),
      (102, 102, 'You can check my Instagram posts from that time. I would never take a life.'),
      (103, 103, 'I was live streaming on Twitch all evening. Violence makes me sick.'),
      (104, 104, 'My Fitbit shows I was jogging then. I couldnt have killed anyone.'),
      (105, 105, 'Fui eu quem pegou o cristal. Acho que preciso de um advogado agora?'),
      (106, 106, 'Check my browser history, I was online shopping. Im not a violent person.'),
      (107, 107, 'I was getting a tattoo at that exact time. I wouldnt hurt a fly.'),
      (108, 108, 'My Uber history proves I was across town. Ive never even been in a fight.'),
      (109, 109, 'I was doing a charity run that morning. Violence isnt in my nature.'),
      (110, 110, 'My phone GPS shows I was elsewhere. I couldnt harm another person.'),
      (111, 111, 'I was at my pottery class then. Im a creator, not a destroyer.'),
      (112, 112, 'The security cameras at the gym show me there. Im innocent of this crime.'),
      (113, 113, 'I was having dental surgery that day. Im not capable of murder.'),
      (114, 114, 'My credit card records show I was shopping. Ive never hurt anyone.'),
      (115, 115, 'I was broadcasting live on Facebook. Killing is against everything I stand for.'),
      (116, 116, 'Check my work computer logs. I would never commit such a horrible act.'),
      (117, 117, 'I was at a cooking class that evening. Violence isnt part of who I am.'),
      (118, 118, 'My Netflix history shows I was home watching movies. Im not a killer.'),
      (119, 119, 'I was volunteering at the animal shelter. I could never take a life.'),
      (120, 120, 'My train pass shows I was commuting then. Im not capable of murder.'),
      (121, 121, 'I was at my sons piano recital. Ive never even thought about killing.'),
      (122, 122, 'The library records show I was studying. Im a peaceful person.'),
      (123, 123, 'I was getting my hair done at the salon. Violence isnt my way.'),
      (124, 124, 'My smart doorbell shows when I was home. I wouldnt hurt anyone.'),
      (125, 125, 'I was at a yoga workshop that day. Taking life is against my beliefs.'),
      (126, 126, 'Check my parking receipts from downtown. Im not that kind of person.'),
      (127, 127, 'I was at my weekly book club meeting. I couldnt kill another human.'),
      (128, 128, 'My gym membership records prove my location. Im innocent of this.'),
      (129, 129, 'I was taking care of my sick mother. I would never commit murder.'),
      (130, 130, 'The bowling alley has me on camera. Im not capable of such violence.'),
      (131, 131, 'I was at my painting class then. I create art, not destruction.'),
      (132, 132, 'My hotel key card records show my location. Im not a violent person.'),
      (133, 133, 'I was attending a wedding that day. I couldnt have killed anyone.'),
      (134, 134, 'Check my internet service logs. Im not the murderer youre looking for.'),
      (135, 135, 'I was at a business conference. Violence goes against my nature.'),
      (136, 136, 'My metro card history proves my whereabouts. Im not a killer.'),
      (137, 137, 'I was having coffee with friends. I would never take someones life.'),
      (138, 138, 'The ATM camera caught me withdrawing cash then. I couldnt have done this.'),
      (139, 139, 'I was at my weekly therapy session. Im not capable of murder.'),
      (140, 140, 'My phone records show I was elsewhere. Ive never harmed anyone.'),
      (141, 141, 'I was watching my neighbors kids. I wouldnt commit such a crime.'),
      (142, 142, 'Check the church attendance records. Im a peaceful person.'),
      (143, 143, 'I was at a movie premiere that night. I couldnt have killed anyone.'),
      (144, 144, 'My gardening club can vouch for me. I nurture life, not take it.'),
      (145, 145, 'I was getting my car serviced then. Im not a violent individual.'),
      (146, 146, 'The supermarket cameras show me shopping. I wouldnt hurt anyone.'),
      (147, 147, 'I was at my dance class that evening. Violence isnt in my nature.'),
      (148, 148, 'My buildings security footage proves my innocence. Im not a murderer.'),
      (149, 149, 'I was at a parent-teacher conference. I could never take a life.'),
      (150, 150, 'Check my work badge swipe records. Im innocent of this crime.'),
      (151, 151, 'I was at a music concert then. I wouldnt harm another person.'),
      (152, 152, 'My social media posts show my location. Im not capable of killing.'),
      (153, 153, 'I was taking my driving test that day. Violence isnt part of who I am.'),
      (154, 154, 'The restaurant receipt shows I was dining. I couldnt have done this.'),
      (155, 155, 'I was at a job interview then. Im not the type to commit murder.'),
      (156, 156, 'My bus pass shows I was traveling. I would never take someones life.'),
      (157, 157, 'I was at my chess club meeting. Im a person of peace, not violence.'),
      (158, 158, 'Check the hospital visitor logs. I couldnt have killed anyone.'),
      (159, 159, 'I was at a football game that day. Im not capable of such acts.'),
      (160, 160, 'My credit card shows I was at the mall. I wouldnt hurt a soul.'),
      (161, 161, 'I was taking a cooking class then. I create food, not destruction.'),
      (162, 162, 'The pharmacy security cameras show me there. Im not a violent person.'),
      (163, 163, 'I was at my daughters soccer game. I couldnt have committed murder.'),
      (164, 164, 'My gym trainer can verify my presence. Im innocent of this charge.'),
      (165, 165, 'I was at a wine tasting event. Violence isnt something Im capable of.'),
      (166, 166, 'Check my airline ticket from that day. I would never kill anyone.'),
      (167, 167, 'I was at a photography workshop. I capture life, not take it.'),
      (168, 168, 'My dentist appointment record proves my alibi. Im not a murderer.'),
      (169, 169, 'I was at a birthday party then. I couldnt have done this crime.'),
      (170, 170, 'The gas station footage shows me filling up. Im not violent at all.'),
      (171, 171, 'I was taking my dog to the vet. I would never harm anyone.'),
      (172, 172, 'Check my library card records. Im a peaceful citizen.'),
      (173, 173, 'I was at a job training seminar. I couldnt have killed anyone.'),
      (174, 174, 'My swimming pool membership shows I was there. Im not capable of murder.'),
      (175, 175, 'I was at a family reunion then. Violence isnt in my character.'),
      (176, 176, 'The bank cameras caught me making a deposit. I wouldnt take a life.'),
      (177, 177, 'I was at my weekly prayer group. Im devoted to peace, not violence.'),
      (178, 178, 'Check my parking garage ticket. I couldnt have done this.'),
      (179, 179, 'I was getting a massage at that time. Im not a violent person.'),
      (180, 180, 'My museum membership card was used then. I appreciate art, not violence.'),
      (181, 181, 'I was at a language class that day. I couldnt have killed anyone.'),
      (182, 182, 'The coffee shop cameras show me working. Im not capable of murder.'),
      (183, 183, 'I was at a pottery workshop then. I create beauty, not destruction.'),
      (184, 184, 'My theater ticket stub proves my location. I wouldnt hurt anyone.'),
      (185, 185, 'I was at a community meeting. Violence isnt part of my nature.'),
      (186, 186, 'Check my phones location history. Im innocent of this crime.'),
      (187, 187, 'I was at a dance competition. I couldnt have committed murder.'),
      (188, 188, 'My hotel receipt shows I was out of town. Im not a violent person.'),
      (189, 189, 'I was at an art gallery opening. I appreciate life too much to take it.'),
      (190, 190, 'The toll booth records show my car elsewhere. I wouldnt kill anyone.'),
      (191, 191, 'I was at a charity fundraiser. I help people, not harm them.'),
      (192, 192, 'Check my computer login records. I couldnt have done this.'),
      (193, 193, 'I was at a yoga retreat that week. Im committed to non-violence.'),
      (194, 194, 'My ski lift ticket proves I was on the slopes. Im not a murderer.'),
      (195, 195, 'I was at a cooking competition then. I create dishes, not destruction.'),
      (196, 196, 'The arcade security footage shows me playing. I wouldnt harm anyone.'),
      (197, 197, 'I was at a meditation class. Violence goes against my beliefs.'),
      (198, 198, 'Check my gym check-in records. I couldnt have killed anyone.'),
      (199, 199, 'I was at a piano lesson that day. I make music, not mayhem.')
    ;`,
];
